// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package resources

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"testing"

	"github.com/ollama/ollama/api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.mondoo.com/mql/providers-sdk/v1/inventory"
	"go.mondoo.com/mql/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/providers/ollama/connection"
)

func TestModelNotFoundError(t *testing.T) {
	err := modelNotFoundError("llama3.1:latest")

	assert.True(t, errors.Is(err, errModelNotFound),
		"a missing model must stay classifiable, so ollama.runningModel.model reports null instead of failing")
	assert.Contains(t, err.Error(), `"llama3.1:latest"`, "the message still names the model")

	assert.False(t, errors.Is(fmt.Errorf("dial tcp 127.0.0.1:11434: connect: connection refused"), errModelNotFound),
		"a transport failure must never be degraded to a missing model")
}

func TestModelRef(t *testing.T) {
	t.Run("short name inherits the ollama defaults", func(t *testing.T) {
		registry, namespace, repository, tag := modelRef("llama3.1:latest")
		assert.Equal(t, "registry.ollama.ai", registry)
		assert.Equal(t, "library", namespace)
		assert.Equal(t, "llama3.1", repository)
		assert.Equal(t, "latest", tag)
	})

	t.Run("bare name gets the default tag", func(t *testing.T) {
		_, _, repository, tag := modelRef("llama3.1")
		assert.Equal(t, "llama3.1", repository)
		assert.Equal(t, "latest", tag, "an untagged name resolves to latest")
	})

	t.Run("third-party registry is reported as-is", func(t *testing.T) {
		registry, namespace, repository, tag := modelRef("registry.example.com/team/secret-model:v1")
		assert.Equal(t, "registry.example.com", registry, "a non-default registry must not be reported as registry.ollama.ai")
		assert.Equal(t, "team", namespace)
		assert.Equal(t, "secret-model", repository)
		assert.Equal(t, "v1", tag)
	})

	t.Run("unparseable name claims no provenance", func(t *testing.T) {
		registry, namespace, repository, tag := modelRef("")
		assert.Empty(t, registry, "an unreadable name must not report the default registry")
		assert.Empty(t, namespace)
		assert.Empty(t, repository)
		assert.Empty(t, tag)
	})
}

func TestModelfileAdapters(t *testing.T) {
	t.Run("no adapters", func(t *testing.T) {
		assert.Empty(t, modelfileAdapters("FROM llama3.1:latest\nPARAMETER num_ctx 4096\n"))
	})

	t.Run("empty modelfile", func(t *testing.T) {
		assert.Empty(t, modelfileAdapters(""))
	})

	t.Run("commented instructions are ignored", func(t *testing.T) {
		// `ollama show --modelfile` emits a commented FROM header; a commented
		// ADAPTER must not be reported as applied.
		modelfile := "# Modelfile generated by \"ollama show\"\n# ADAPTER /tmp/not-applied.gguf\nFROM /root/.ollama/blobs/sha256-abc\n"
		assert.Empty(t, modelfileAdapters(modelfile))
	})

	t.Run("collects every adapter", func(t *testing.T) {
		modelfile := "FROM llama3.1:latest\nADAPTER /opt/lora/first.gguf\nadapter /opt/lora/second.gguf\n"
		assert.Equal(t,
			[]string{"/opt/lora/first.gguf", "/opt/lora/second.gguf"},
			modelfileAdapters(modelfile),
			"the instruction name is case-insensitive")
	})

	t.Run("tab separator and quoted target", func(t *testing.T) {
		modelfile := "ADAPTER\t\"/opt/lora/path with spaces.gguf\"\n"
		assert.Equal(t, []string{"/opt/lora/path with spaces.gguf"}, modelfileAdapters(modelfile))
	})

	t.Run("instruction with no target is skipped", func(t *testing.T) {
		assert.Empty(t, modelfileAdapters("ADAPTER\nADAPTER   \n"))
	})

	t.Run("similarly named instructions are not matched", func(t *testing.T) {
		assert.Empty(t, modelfileAdapters("ADAPTERS /opt/lora/first.gguf\n"))
	})
}

func TestGetString(t *testing.T) {
	m := map[string]any{
		"general.architecture": "llama",
		"general.parameter":    float64(42),
		"general.nil":          nil,
	}
	assert.Equal(t, "llama", getString(m, "general.architecture"))
	assert.Equal(t, "", getString(m, "missing"), "missing key returns empty string")
	assert.Equal(t, "", getString(m, "general.parameter"), "non-string value returns empty string")
	assert.Equal(t, "", getString(m, "general.nil"), "nil value returns empty string")
}

func TestGetInt(t *testing.T) {
	// JSON numbers decode into map[string]any as float64, which is the real
	// wire type from the ollama client; int64 is covered for completeness.
	m := map[string]any{
		"float": float64(8030261248),
		"int64": int64(4096),
		"str":   "128",
		"nil":   nil,
	}
	assert.Equal(t, int64(8030261248), getInt(m, "float"), "large float64 preserved without precision loss")
	assert.Equal(t, int64(4096), getInt(m, "int64"))
	assert.Equal(t, int64(0), getInt(m, "missing"), "missing key returns zero")
	assert.Equal(t, int64(0), getInt(m, "str"), "non-numeric value returns zero")
	assert.Equal(t, int64(0), getInt(m, "nil"), "nil value returns zero")
}

func TestGetArchInt(t *testing.T) {
	m := map[string]any{
		"llama.context_length":       float64(131072),
		"llama.attention.head_count": float64(32),
		"qwen2.embedding_length":     float64(3584),
	}
	assert.Equal(t, int64(131072), getArchInt(m, "llama", "context_length"))
	assert.Equal(t, int64(32), getArchInt(m, "llama", "attention.head_count"))
	assert.Equal(t, int64(3584), getArchInt(m, "qwen2", "embedding_length"))
	assert.Equal(t, int64(0), getArchInt(m, "llama", "embedding_length"), "wrong arch prefix returns zero")
	assert.Equal(t, int64(0), getArchInt(m, "", "context_length"), "empty arch returns zero, not a panic")
}

func TestGetStringSlice(t *testing.T) {
	m := map[string]any{
		"general.languages": []any{"en", "de", "fr"},
		"mixed":             []any{"en", float64(1), "de"},
		"scalar":            "en",
		"nil":               nil,
		"empty":             []any{},
	}
	assert.Equal(t, []interface{}{"en", "de", "fr"}, getStringSlice(m, "general.languages"))
	assert.Equal(t, []interface{}{"en", "de"}, getStringSlice(m, "mixed"), "non-string elements are skipped")
	assert.Equal(t, []interface{}{}, getStringSlice(m, "scalar"), "scalar (non-array) value yields empty slice")
	assert.Equal(t, []interface{}{}, getStringSlice(m, "missing"), "missing key yields empty slice")
	assert.Equal(t, []interface{}{}, getStringSlice(m, "nil"), "nil value yields empty slice")
	assert.Equal(t, []interface{}{}, getStringSlice(m, "empty"))
}

// A Modelfile is mostly PARAMETER and TEMPLATE lines that the adapter scan
// never looks at, so splitting it into a slice of every line allocates one
// string header per line to find a handful of matches. Walking it with an
// iterator drops that slice: the scan allocates only the result.
//
// This gate is an allocation count, which is exact and does not depend on how
// busy the machine is. It does not express "the cost must not grow with the
// file" on its own -- both forms hold their count steady as the file grows --
// but any implementation that materializes the lines again pays for that slice
// and trips the ceiling.
func TestModelfileAdaptersDoesNotMaterializeLines(t *testing.T) {
	var sb strings.Builder
	sb.WriteString("# Modelfile generated by \"ollama show\"\n")
	sb.WriteString("FROM /root/.ollama/models/blobs/sha256-abcdef0123456789\n")
	for i := 0; i < 400; i++ {
		sb.WriteString("PARAMETER stop \"<|eot_id|>" + strconv.Itoa(i) + "\"\n")
	}
	sb.WriteString("ADAPTER /opt/lora/adapter.gguf\n")
	modelfile := sb.String()

	allocs := testing.AllocsPerRun(200, func() {
		sink = modelfileAdapters(modelfile)
	})

	assert.Equal(t, []string{"/opt/lora/adapter.gguf"}, sink, "the scan still finds the adapter")
	assert.LessOrEqual(t, allocs, 1.0,
		"modelfileAdapters made %.0f allocations on a 400-line Modelfile; only the result slice may allocate", allocs)
}

var sink []string

func TestClassifyAuthProbe(t *testing.T) {
	tests := []struct {
		name    string
		code    int
		open    []int
		want    bool
		wantErr bool
	}{
		// A refusal for lack of credentials means that path is gated, whether
		// the instance or a proxy in front of it did the refusing.
		{"read 401", http.StatusUnauthorized, readOpenStatuses, true, false},
		{"read 403", http.StatusForbidden, readOpenStatuses, true, false},
		{"read 407", http.StatusProxyAuthRequired, readOpenStatuses, true, false},
		{"write 401", http.StatusUnauthorized, writeOpenStatuses, true, false},
		{"write 403", http.StatusForbidden, writeOpenStatuses, true, false},
		{"write 407", http.StatusProxyAuthRequired, writeOpenStatuses, true, false},

		// A served read, and a write turned away only for its unparseable body.
		{"read 200", http.StatusOK, readOpenStatuses, false, false},
		{"write 400", http.StatusBadRequest, writeOpenStatuses, false, false},
		{"write 422", http.StatusUnprocessableEntity, writeOpenStatuses, false, false},

		// A 400 says nothing about reads, and a 200 to an unparseable create
		// body is not an Ollama create handler answering.
		{"read 400", http.StatusBadRequest, readOpenStatuses, false, true},
		{"write 200", http.StatusOK, writeOpenStatuses, false, true},

		// An endpoint that is not served, a login redirect, and a gateway
		// failure are all "could not tell", never a posture claim.
		{"404", http.StatusNotFound, writeOpenStatuses, false, true},
		{"405", http.StatusMethodNotAllowed, writeOpenStatuses, false, true},
		{"302", http.StatusFound, readOpenStatuses, false, true},
		{"500", http.StatusInternalServerError, writeOpenStatuses, false, true},
		{"502", http.StatusBadGateway, readOpenStatuses, false, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := classifyAuthProbe(tt.code, tt.open, "write")
			if tt.wantErr {
				assert.Error(t, err, "an unclassifiable answer must not be reported as a posture finding")
				assert.False(t, got)
				return
			}
			assert.NoError(t, err)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestWriteOpenStatusesDoNotOverlapAuthRequired(t *testing.T) {
	for _, code := range writeOpenStatuses {
		assert.NotContains(t, authRequiredStatuses, code,
			"a status cannot mean both that writes are gated and that they are open")
	}
	for _, code := range readOpenStatuses {
		assert.NotContains(t, authRequiredStatuses, code)
	}
}

// The executor resolves the fields of one resource concurrently, so two
// Show-backed accessors on the same model enter fetchShow at the same time.
// fetchShow keeps a lock-free fast path, which means its flag is read outside
// the mutex and written under it: with a plain bool that is a data race, and
// this test reports it as one under -race.
//
// The call count is the second half. The re-check inside the lock is what keeps
// a burst of accessors down to a single /api/show call, and dropping it would
// leave this green under -race while costing one request per field.
func TestFetchShowIsSafeUnderConcurrentAccessors(t *testing.T) {
	var calls atomic.Int32
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls.Add(1)
		assert.Equal(t, "/api/show", r.URL.Path)
		_ = json.NewEncoder(w).Encode(api.ShowResponse{
			License:    "  MIT  ",
			Modelfile:  "FROM llama3.1:latest\nADAPTER /opt/lora/a.gguf\n",
			System:     "You are a helpful assistant.",
			Template:   "{{ .System }}",
			Parameters: "  stop \"<|eot_id|>\"  ",
			Renderer:   "harmony",
			Parser:     "qwen3-coder",
		})
	}))
	defer srv.Close()

	conn, err := connection.NewOllamaConnection(1, &inventory.Asset{}, &inventory.Config{
		Options: map[string]string{connection.HostOption: srv.URL},
	})
	require.NoError(t, err)

	model := &mqlOllamaModel{MqlRuntime: &plugin.Runtime{Connection: conn}}
	model.Name = plugin.TValue[string]{Data: "llama3.1:latest", State: plugin.StateIsSet}

	accessors := []struct {
		field string
		read  func() (string, error)
		want  string
	}{
		{"license", model.license, "MIT"},
		{"modelfile", model.modelfile, "FROM llama3.1:latest\nADAPTER /opt/lora/a.gguf\n"},
		{"system", model.system, "You are a helpful assistant."},
		{"template", model.template, "{{ .System }}"},
		{"parameters", model.parameters, `stop "<|eot_id|>"`},
		{"renderer", model.renderer, "harmony"},
		{"parser", model.parser, "qwen3-coder"},
	}

	got := make([]string, len(accessors))
	errs := make([]error, len(accessors))
	start := make(chan struct{})
	var wg sync.WaitGroup
	for i, a := range accessors {
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-start
			got[i], errs[i] = a.read()
		}()
	}
	close(start)
	wg.Wait()

	for i, a := range accessors {
		require.NoError(t, errs[i], a.field)
		// Each accessor must return its own field of the Show answer. A
		// crossed pair, renderer reading show.Parser, fails here.
		assert.Equal(t, a.want, got[i], a.field)
	}

	assert.Equal(t, int32(1), calls.Load(),
		"every Show-backed field on one model must share a single /api/show call")
}

func TestClassifyCorsProbe(t *testing.T) {
	const probe = "https://0123456789abcdef.example.com"

	tests := []struct {
		name        string
		allowOrigin string
		observed    bool
		want        bool
		wantKnown   bool
	}{
		// OLLAMA_ORIGINS=* turns the allowlist into every origin, and
		// gin-contrib/cors then names `*` rather than the caller's origin.
		{"every origin", "*", true, true, true},

		// A wildcard pattern that happens to cover the unrelated origin is
		// echoed back instead. Same exposure, different wire form.
		{"unrelated origin echoed back", probe, true, true, true},
		{"echo differing only in case", strings.ToUpper(probe), true, true, true},

		// The stock allowlist: the instance answers cross-origin requests and
		// allows this one nothing.
		{"refused with no origin named", "", true, false, true},
		{"another origin named", "http://localhost", true, false, true},

		// Nothing on the instance handles cross-origin requests, so it has said
		// nothing about them. A false here would pass a check the instance
		// never earned.
		{"no cross-origin handling anywhere", "", false, false, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, known := classifyCorsProbe(tt.allowOrigin, probe, tt.observed)
			assert.Equal(t, tt.wantKnown, known)
			assert.Equal(t, tt.want, got)
		})
	}

	t.Run("an empty probe origin never matches an empty allowance", func(t *testing.T) {
		got, known := classifyCorsProbe("", "", true)
		assert.True(t, known)
		assert.False(t, got, "no origin asked about and none allowed is not permission for every origin")
	})
}

func TestClassifyForeignHostProbe(t *testing.T) {
	tests := []struct {
		name          string
		controlStatus int
		foreignStatus int
		want          bool
		wantErr       bool
	}{
		// The instance serves its own host name and refuses the unrelated one.
		{"refused", http.StatusOK, http.StatusForbidden, true, false},
		// It serves both, so a page that points a domain it controls at this
		// address is answered.
		{"served", http.StatusOK, http.StatusOK, false, false},

		// The control was not served, so whatever turned it away would have
		// turned the other away too and the pair proves nothing. A 403 control
		// is the case that matters: crediting that refusal to the host name
		// would report a gated instance as protected.
		{"gated control", http.StatusUnauthorized, http.StatusUnauthorized, false, true},
		{"forbidden control", http.StatusForbidden, http.StatusForbidden, false, true},
		{"failing control", http.StatusBadGateway, http.StatusForbidden, false, true},
		{"redirected control", http.StatusFound, http.StatusForbidden, false, true},

		// The control was served but the answer to the unrelated name is
		// neither of the two that mean anything.
		{"unreadable answer", http.StatusOK, http.StatusBadGateway, false, true},
		{"redirected answer", http.StatusOK, http.StatusFound, false, true},
		{"not found", http.StatusOK, http.StatusNotFound, false, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := classifyForeignHostProbe(tt.controlStatus, tt.foreignStatus)
			if tt.wantErr {
				assert.Error(t, err, "an unreadable pair must not be reported as a posture finding")
				assert.False(t, got)
				return
			}
			assert.NoError(t, err)
			assert.Equal(t, tt.want, got)
		})
	}
}
