// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package upstream_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestEveryProtoPackageIsWiredIntoTheMakefile pins that a package which
// generates protobuf code is actually regenerated by `make`.
//
// `make clean/proto` deletes every *.pb.go in the repository and the generate
// targets put them back from a hand-maintained list. A package with a
// //go:generate directive that nobody calls is therefore not merely
// un-regenerated: its committed output is deleted and never restored, so the
// package loses its types and everything importing it stops compiling.
//
// That is what happened to providers-sdk/v1/upstream/fex. It was added with a
// correct directive and correct committed output, but never added to
// shared/generate, so `make clean/proto` emptied it. Because
// providers-sdk/v1/upstream/sbomscan imports fex, the failure reached every
// provider build rather than staying local.
//
// It stayed hidden because the pull-request check regenerates only the
// providers a branch changed, while the push-to-main check regenerates all of
// them -- main does strictly more work than any pull request, so no pull
// request could have caught it.
func TestEveryProtoPackageIsWiredIntoTheMakefile(t *testing.T) {
	root := repoRoot(t)

	makefile, err := os.ReadFile(filepath.Join(root, "Makefile"))
	require.NoError(t, err)
	rules := string(makefile)

	upstreamDir := filepath.Join(root, "providers-sdk", "v1", "upstream")

	entries, err := os.ReadDir(upstreamDir)
	require.NoError(t, err)

	checked := 0
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		pkgDir := filepath.Join(upstreamDir, entry.Name())
		if !generatesProto(t, pkgDir) {
			continue
		}
		checked++

		// The path as `go generate` is invoked with it in the Makefile.
		target := "./providers-sdk/v1/upstream/" + entry.Name()
		require.Contains(t, rules, "go generate "+target,
			"providers-sdk/v1/upstream/%s has a //go:generate protoc directive that no make "+
				"target calls. `make clean/proto` deletes its generated files and nothing "+
				"restores them, so the package stops compiling. Add `go generate %s` to "+
				"shared/generate.", entry.Name(), target)
	}

	// Guard the guard: if the directory layout moves, this test must fail
	// rather than silently pass over an empty set.
	require.Greater(t, checked, 3, "found almost no proto packages; the scan is probably looking in the wrong place")
}

// generatesProto reports whether any .go file in dir asks protoc to run.
func generatesProto(t *testing.T, dir string) bool {
	t.Helper()

	entries, err := os.ReadDir(dir)
	require.NoError(t, err)

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		require.NoError(t, err)

		for _, line := range strings.Split(string(data), "\n") {
			if strings.HasPrefix(line, "//go:generate") && strings.Contains(line, "protoc") {
				return true
			}
		}
	}
	return false
}

// repoRoot walks up until it finds the Makefile beside go.mod.
func repoRoot(t *testing.T) string {
	t.Helper()

	dir, err := os.Getwd()
	require.NoError(t, err)

	for i := 0; i < 10; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			if _, err := os.Stat(filepath.Join(dir, "Makefile")); err == nil {
				return dir
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	t.Fatal("could not locate the repository root")
	return ""
}
