// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package resources

import (
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.mondoo.com/mql/llx"
	"go.mondoo.com/mql/providers/os/connection/mock"
)

func TestAixIpsec(t *testing.T) {
	v4, err := os.ReadFile("aix/testdata/lsfilt_v4_aix73.txt")
	require.NoError(t, err)
	rt := newAixRuntime(t, aixPlatform, nil, map[string]*mock.Command{
		// ipsec_v4 loaded, ipsec_v6 never defined
		"lsdev -C -c ipsec -F name:status": {Stdout: "ipsec_v4:Available\n"},
		"lsfilt -v4":                       {Stdout: string(v4)},
		"lsfilt -v6":                       {Stdout: "Beginning of IPv6 filter rules.\nEnd of IPv6 filter rules.\n"},
	})
	r, err := CreateResource(rt, "aix.ipsec", map[string]*llx.RawData{})
	require.NoError(t, err)
	ipsec := r.(*mqlAixIpsec)

	assert.True(t, ipsec.GetIpv4Active().Data)
	assert.False(t, ipsec.GetIpv6Active().Data)

	filters := ipsec.GetFilters()
	require.NoError(t, filters.Error)
	require.Len(t, filters.Data, 3)
	deny := filters.Data[1].(*mqlAixIpsecFilter)
	assert.Equal(t, "deny", deny.Action.Data)
	assert.Equal(t, "eq 47999", deny.DestinationPort.Data)
	assert.Equal(t, "all", deny.InterfaceName.Data)
	assert.False(t, deny.AutoGenerated.Data)
	assert.True(t, filters.Data[0].(*mqlAixIpsecFilter).AutoGenerated.Data)
}

func TestAixIpsecDefinedDeviceIsInactive(t *testing.T) {
	rt := newAixRuntime(t, aixPlatform, nil, map[string]*mock.Command{
		"lsdev -C -c ipsec -F name:status": {Stdout: "ipsec_v4:Defined\n"},
	})
	r, err := CreateResource(rt, "aix.ipsec", map[string]*llx.RawData{})
	require.NoError(t, err)
	assert.False(t, r.(*mqlAixIpsec).GetIpv4Active().Data)
}
