// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package resources

import (
	"strconv"
	"strings"

	"go.mondoo.com/mql/llx"
	"go.mondoo.com/mql/providers/os/resources/aix"
)

func (i *mqlAixIpsec) id() (string, error) {
	return "aix.ipsec", nil
}

// deviceAvailable reports whether an IPsec device is loaded: lsdev prints
// nothing for a device that was never defined and "Defined" for one that is
// not loaded.
func (i *mqlAixIpsec) deviceAvailable(name string) (bool, error) {
	if err := requireAix(i.MqlRuntime, "aix.ipsec"); err != nil {
		return false, err
	}
	out, _, err := runAixCommand(i.MqlRuntime, "lsdev -C -c ipsec -F name:status")
	if err != nil {
		return false, err
	}
	for _, line := range strings.Split(out, "\n") {
		n, status, ok := strings.Cut(strings.TrimSpace(line), ":")
		if ok && n == name {
			return status == "Available", nil
		}
	}
	return false, nil
}

func (i *mqlAixIpsec) ipv4Active() (bool, error) {
	return i.deviceAvailable("ipsec_v4")
}

func (i *mqlAixIpsec) ipv6Active() (bool, error) {
	return i.deviceAvailable("ipsec_v6")
}

func (i *mqlAixIpsec) filters() ([]any, error) {
	if err := requireAix(i.MqlRuntime, "aix.ipsec"); err != nil {
		return nil, err
	}
	res := []any{}
	for _, version := range []int{4, 6} {
		out, _, err := runAixCommand(i.MqlRuntime, "lsfilt -v"+strconv.Itoa(version))
		if err != nil {
			return nil, err
		}
		for _, f := range aix.ParseLsfilt(out, version) {
			a := f.Attrs
			r, err := CreateResource(i.MqlRuntime, "aix.ipsec.filter", map[string]*llx.RawData{
				"__id":               llx.StringData("aix.ipsec.filter/" + strconv.Itoa(version) + "/" + strconv.Itoa(f.ID)),
				"version":            llx.IntData(version),
				"id":                 llx.IntData(f.ID),
				"action":             llx.StringData(a["Rule action"]),
				"sourceAddress":      llx.StringData(a["Source Address"]),
				"sourceMask":         llx.StringData(a["Source Mask"]),
				"destinationAddress": llx.StringData(a["Destination Address"]),
				"destinationMask":    llx.StringData(a["Destination Mask"]),
				"protocol":           llx.StringData(a["Protocol"]),
				"sourcePort":         llx.StringData(a["Source Port"]),
				"destinationPort":    llx.StringData(a["Destination Port"]),
				"direction":          llx.StringData(a["Direction"]),
				"scope":              llx.StringData(a["Scope"]),
				"interfaceName":      llx.StringData(a["Interface"]),
				"log":                llx.BoolData(a["Logging control"] == "yes"),
				"autoGenerated":      llx.BoolData(a["Auto-Generated"] == "yes"),
				"description":        llx.StringData(a["Description"]),
			})
			if err != nil {
				return nil, err
			}
			res = append(res, r)
		}
	}
	return res, nil
}
