// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package resources

import (
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.mondoo.com/mql/providers/os/resources/haproxy"
)

// mustParseEximConfig parses a config that tests no built-in macro.
func mustParseEximConfig(t *testing.T, content string) map[string]any {
	t.Helper()
	params, err := parseEximConfig(content, nil)
	require.NoError(t, err)
	return params
}

func readEximTestdata(t *testing.T, name string) string {
	t.Helper()
	data, err := os.ReadFile("testdata/exim/" + name)
	require.NoError(t, err)
	return string(data)
}

// eximMacrosFrom returns a lookup backed by captured `exim -bP macros` output.
func eximMacrosFrom(t *testing.T, name string) eximBuiltinLookup {
	m := parseEximMacrosOutput(readEximTestdata(t, name))
	require.NotNil(t, m)
	return m.defined
}

func TestParseEximConfig(t *testing.T) {
	t.Run("Debian split-config key='value' form", func(t *testing.T) {
		content := "# update-exim4.conf.conf\n" +
			"dc_eximconfig_configtype='internet'\n" +
			"dc_local_interfaces='127.0.0.1 ; ::1'\n" +
			"dc_readhost=''\n"
		got := mustParseEximConfig(t, content)
		assert.Equal(t, "internet", got["dc_eximconfig_configtype"])
		assert.Equal(t, "127.0.0.1 ; ::1", got["dc_local_interfaces"])
		assert.Equal(t, "", got["dc_readhost"])
	})

	t.Run("monolithic key = value form with macros", func(t *testing.T) {
		content := "# exim.conf\n" +
			"MACRO = /var/spool/exim\n" +
			"local_interfaces = <; 127.0.0.1 ; ::1\n" +
			"primary_hostname = mail.example.com\n"
		got := mustParseEximConfig(t, content)
		assert.Equal(t, "/var/spool/exim", got["MACRO"])
		assert.Equal(t, "<; 127.0.0.1 ; ::1", got["local_interfaces"])
		assert.Equal(t, "mail.example.com", got["primary_hostname"])
	})

	t.Run("stops at the first begin block", func(t *testing.T) {
		content := "primary_hostname = mail.example.com\n" +
			"begin acl\n" +
			"acl_check_rcpt:\n" +
			"  accept hosts = +relay = something\n"
		got := mustParseEximConfig(t, content)
		assert.Equal(t, "mail.example.com", got["primary_hostname"])
		_, hasAcl := got["acl_check_rcpt:"]
		assert.False(t, hasAcl)
		// an option-looking line inside the section must not leak in
		_, leaked := got["accept hosts"]
		assert.False(t, leaked)
	})

	t.Run("hide prefix and named lists", func(t *testing.T) {
		content := "hide mysql_servers = localhost/db/user/secret\n" +
			"domainlist local_domains = @\n"
		got := mustParseEximConfig(t, content)
		assert.Equal(t, "localhost/db/user/secret", got["mysql_servers"])
		// named-list left-hand side has two tokens; it is not a simple option
		_, hasNamedList := got["domainlist local_domains"]
		assert.False(t, hasNamedList)
	})

	t.Run("backslash continuation", func(t *testing.T) {
		content := "local_interfaces = <; 127.0.0.1 ; \\\n  ::1\n"
		got := mustParseEximConfig(t, content)
		assert.Equal(t, "<; 127.0.0.1 ; ::1", got["local_interfaces"])
	})
}

func TestUnquoteEximValue(t *testing.T) {
	assert.Equal(t, "127.0.0.1 ; ::1", unquoteEximValue("'127.0.0.1 ; ::1'"))
	assert.Equal(t, "internet", unquoteEximValue(`"internet"`))
	assert.Equal(t, "", unquoteEximValue("''"))
	assert.Equal(t, "unquoted", unquoteEximValue("unquoted"))
	assert.Equal(t, "'mismatched", unquoteEximValue("'mismatched"))
}

func TestParseEximListValue(t *testing.T) {
	// custom separator via the <sep prefix (needed for IPv6)
	assert.Equal(t, []any{"127.0.0.1", "::1"}, parseEximListValue("<; 127.0.0.1 ; ::1"))
	// default ':' separator
	assert.Equal(t, []any{"127.0.0.1", "192.168.0.1"}, parseEximListValue("127.0.0.1 : 192.168.0.1"))
	assert.Equal(t, []any{"127.0.0.1"}, parseEximListValue("127.0.0.1"))
}

func TestSplitEximList(t *testing.T) {
	assert.Equal(t, []any{"127.0.0.1", "::1"}, splitEximList("127.0.0.1 ; ::1", ";"))
	assert.Equal(t, []any{}, splitEximList("", ";"))
}

// debianAutogenerated is the main section of /var/lib/exim4/config.autogenerated
// as written by update-exim4.conf on Ubuntu 24.04 (exim4 4.97) with
// dc_local_interfaces='127.0.0.1 ; ::1'.
const debianAutogenerated = `exim_path = /usr/sbin/exim4

.ifndef CONFDIR
CONFDIR = /etc/exim4
.endif

UPEX4CmacrosUPEX4C = 1
##############################################
# the following macro definitions were created
# dynamically by /usr/sbin/update-exim4.conf
.ifndef MAIN_LOCAL_INTERFACES
MAIN_LOCAL_INTERFACES=<; 127.0.0.1 ; ::1
.endif
.ifndef MAIN_LOCAL_DOMAINS
MAIN_LOCAL_DOMAINS=@:localhost:mail.example.test
.endif
.ifndef ETC_MAILNAME
ETC_MAILNAME=mail.example.test
.endif
##############################################

domainlist local_domains = MAIN_LOCAL_DOMAINS

.ifndef MAIN_PRIMARY_HOSTNAME_AS_QUALIFY_DOMAIN
.ifndef MAIN_QUALIFY_DOMAIN
qualify_domain = ETC_MAILNAME
.else
qualify_domain = MAIN_QUALIFY_DOMAIN
.endif
.endif

.ifdef MAIN_LOCAL_INTERFACES
local_interfaces = MAIN_LOCAL_INTERFACES
.endif

.ifndef LOCAL_DELIVERY
LOCAL_DELIVERY=mail_spool
.endif
`

func TestParseEximConfigMacros(t *testing.T) {
	t.Run("macro reference in an option is resolved", func(t *testing.T) {
		got := mustParseEximConfig(t, debianAutogenerated)
		assert.Equal(t, "<; 127.0.0.1 ; ::1", got["MAIN_LOCAL_INTERFACES"])
		assert.Equal(t, "<; 127.0.0.1 ; ::1", got["local_interfaces"])
		assert.Equal(t, []any{"127.0.0.1", "::1"}, eximLocalInterfaces(got))
	})

	t.Run(".ifndef/.else picks the branch for undefined macros", func(t *testing.T) {
		got := mustParseEximConfig(t, debianAutogenerated)
		// MAIN_QUALIFY_DOMAIN is undefined, so the .ifndef branch applies
		assert.Equal(t, "mail.example.test", got["qualify_domain"])
	})

	t.Run(".ifndef skips a redefinition of a defined macro", func(t *testing.T) {
		got := mustParseEximConfig(t, "CONFDIR = /srv/exim\n"+debianAutogenerated)
		assert.Equal(t, "/srv/exim", got["CONFDIR"])
	})

	t.Run("an earlier macro overrides the generated default", func(t *testing.T) {
		// exim4.conf.localmacros content lands ahead of the generated block
		got := mustParseEximConfig(t, "MAIN_LOCAL_INTERFACES = <; 0.0.0.0 ; ::0\n"+debianAutogenerated)
		assert.Equal(t, []any{"0.0.0.0", "::0"}, eximLocalInterfaces(got))
	})

	t.Run("undefined macro leaves local_interfaces unset", func(t *testing.T) {
		// update-exim4.conf omits the MAIN_LOCAL_INTERFACES block when
		// dc_local_interfaces is empty, so the .ifdef is false
		content := strings.Replace(debianAutogenerated,
			".ifndef MAIN_LOCAL_INTERFACES\nMAIN_LOCAL_INTERFACES=<; 127.0.0.1 ; ::1\n.endif\n", "", 1)
		got := mustParseEximConfig(t, content)
		_, ok := got["local_interfaces"]
		assert.False(t, ok)
		assert.Equal(t, []any{"::0", "0.0.0.0"}, eximLocalInterfaces(got))
	})

	t.Run("macro names match whole words only", func(t *testing.T) {
		got := mustParseEximConfig(t, "PORT = 25\nPORTS = 587\ndaemon_smtp_ports = PORTS : PORT\n")
		assert.Equal(t, "587 : 25", got["daemon_smtp_ports"])
	})

	t.Run("== redefines a macro", func(t *testing.T) {
		got := mustParseEximConfig(t, "IFACES = 127.0.0.1\nIFACES == 192.0.2.10\nlocal_interfaces = IFACES\n")
		assert.Equal(t, "192.0.2.10", got["local_interfaces"])
	})
}

func TestEximLocalInterfaces(t *testing.T) {
	t.Run("Debian dc_local_interfaces", func(t *testing.T) {
		assert.Equal(t, []any{"127.0.0.1", "::1"},
			eximLocalInterfaces(map[string]any{"dc_local_interfaces": "127.0.0.1 ; ::1"}))
	})

	t.Run("empty Debian dc_local_interfaces listens on all interfaces", func(t *testing.T) {
		// update-exim4.conf.conf from Ubuntu with dc_local_interfaces=''; exim4 -bP
		// local_interfaces then reports `<; ::0 ; 0.0.0.0` and binds 0.0.0.0:25 and [::]:25
		params := mustParseEximConfig(t, "dc_eximconfig_configtype='local'\n"+
			"dc_local_interfaces=''\n"+
			"dc_use_split_config='false'\n")
		assert.Equal(t, []any{"::0", "0.0.0.0"}, eximLocalInterfaces(params))
	})

	t.Run("monolithic local_interfaces", func(t *testing.T) {
		assert.Equal(t, []any{"0.0.0.0", "::0"},
			eximLocalInterfaces(map[string]any{"local_interfaces": "<; 0.0.0.0 ; ::0"}))
	})

	t.Run("monolithic config without local_interfaces listens on all interfaces", func(t *testing.T) {
		assert.Equal(t, []any{"::0", "0.0.0.0"},
			eximLocalInterfaces(map[string]any{"primary_hostname": "mail.example.com"}))
	})

	t.Run("no configuration yields no interfaces", func(t *testing.T) {
		assert.Equal(t, []any{}, eximLocalInterfaces(map[string]any{}))
	})
}

func TestParseEximConfigBuiltinMacros(t *testing.T) {
	// main-section excerpt of the stock /etc/exim/exim.conf on RHEL 9 (exim
	// 4.99.5 from EPEL); RHEL 7/8/10, Alma and Fedora ship the same lines.
	// `exim -bP tls_require_ciphers prdr_enable` reports both as set.
	stock := readEximTestdata(t, "rhel9-exim-main.conf")

	t.Run("stock RHEL config with the binary's macros from exim -bP macros", func(t *testing.T) {
		params, err := parseEximConfig(stock, eximMacrosFrom(t, "rhel9-bP-macros.txt"))
		require.NoError(t, err)
		assert.Equal(t, "ECDSA:RSA:!COMPLEMENTOFDEFAULT", params["tls_require_ciphers"])
		assert.Equal(t, "acl_check_prdr", params["acl_smtp_data_prdr"])
		assert.Equal(t, "${if inlist {$received_port}{587:465} {:}{*}}", params["tls_resumption_hosts"])
	})

	t.Run("stock RHEL config with the macros derived from exim -bV", func(t *testing.T) {
		m := parseEximVersionOutput(readEximTestdata(t, "rhel7-bV.txt"))
		require.NotNil(t, m)
		params, err := parseEximConfig(stock, m.defined)
		require.NoError(t, err)
		assert.Equal(t, "ECDSA:RSA:!COMPLEMENTOFDEFAULT", params["tls_require_ciphers"])
		assert.Equal(t, "acl_check_prdr", params["acl_smtp_data_prdr"])
	})

	t.Run(".ifndef and .else on a built-in macro", func(t *testing.T) {
		content := ".ifdef _HAVE_GNUTLS\ntls_require_ciphers = NORMAL\n.else\ntls_require_ciphers = DEFAULT\n.endif\n" +
			".ifndef _HAVE_TLS\ntls_advertise_hosts =\n.endif\n"
		params, err := parseEximConfig(content, eximMacrosFrom(t, "rhel9-bP-macros.txt"))
		require.NoError(t, err)
		assert.Equal(t, "DEFAULT", params["tls_require_ciphers"])
		_, ok := params["tls_advertise_hosts"]
		assert.False(t, ok, "the binary has TLS, so the .ifndef _HAVE_TLS branch is skipped")
	})

	t.Run("no source for built-in macros is an error, not a guess", func(t *testing.T) {
		_, err := parseEximConfig(stock, nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "_HAVE_PRDR")
	})

	t.Run("a lookup error fails the parse", func(t *testing.T) {
		_, err := parseEximConfig(stock, func(string) (bool, error) {
			return false, errors.New("exim not found")
		})
		assert.EqualError(t, err, "exim not found")
	})

	t.Run("a built-in macro inside a skipped branch is not looked up", func(t *testing.T) {
		calls := 0
		lookup := func(string) (bool, error) { calls++; return true, nil }
		content := ".ifdef ROUTER_SMARTHOST\n.ifdef _HAVE_TLS\ntls_require_ciphers = X\n.elifdef _HAVE_DANE\n.endif\n.endif\n" +
			"local_interfaces = 127.0.0.1\n"
		params, err := parseEximConfig(content, lookup)
		require.NoError(t, err)
		assert.Equal(t, 0, calls)
		assert.Equal(t, "127.0.0.1", params["local_interfaces"])
		_, ok := params["tls_require_ciphers"]
		assert.False(t, ok)
	})

	t.Run("a config without built-in macro tests needs no lookup", func(t *testing.T) {
		_, err := parseEximConfig(debianAutogenerated, func(string) (bool, error) {
			return false, errors.New("must not be called")
		})
		require.NoError(t, err)
	})
}

func TestParseEximMacrosOutput(t *testing.T) {
	m := parseEximMacrosOutput(readEximTestdata(t, "rhel9-bP-macros.txt"))
	require.NotNil(t, m)

	ok, err := m.defined("_HAVE_OPENSSL")
	require.NoError(t, err)
	assert.True(t, ok)
	ok, err = m.defined("_HAVE_TLS1_3")
	require.NoError(t, err)
	assert.True(t, ok)
	ok, err = m.defined("_HAVE_GNUTLS")
	require.NoError(t, err)
	assert.False(t, ok)
	// macros the config defines are listed too, but are not built in
	_, isBuiltin := m.names["LOCAL_IFACES"]
	assert.False(t, isBuiltin)

	// a non-admin user gets a refusal instead of the list
	assert.Nil(t, parseEximMacrosOutput("exim: permission denied; not admin\n"))
	assert.Nil(t, parseEximMacrosOutput(""))
}

func TestParseEximVersionOutput(t *testing.T) {
	// every feature macro the -bV mapping answers must agree with what
	// `exim -bP macros` (run as root on the same host) reports
	for _, host := range []string{"rhel7", "rhel9"} {
		t.Run(host, func(t *testing.T) {
			fromBV := parseEximVersionOutput(readEximTestdata(t, host+"-bV.txt"))
			require.NotNil(t, fromBV)
			fromBP := parseEximMacrosOutput(readEximTestdata(t, host+"-bP-macros.txt"))
			require.NotNil(t, fromBP)

			for name := range fromBV.known {
				got, err := fromBV.defined(name)
				require.NoError(t, err)
				want, err := fromBP.defined(name)
				require.NoError(t, err)
				assert.Equal(t, want, got, name)
			}
			for _, name := range []string{"_HAVE_OPENSSL", "_HAVE_TLS", "_HAVE_PRDR", "_HAVE_TLS_RESUME"} {
				ok, err := fromBV.defined(name)
				require.NoError(t, err)
				assert.True(t, ok, name)
			}
		})
	}

	t.Run("a macro the feature list cannot answer is an error", func(t *testing.T) {
		m := parseEximVersionOutput(readEximTestdata(t, "rhel9-bV.txt"))
		_, err := m.defined("_HAVE_TLS1_3")
		assert.Error(t, err)
	})

	t.Run("Exim 4.94 Experimental_SRS leaves native SRS unknown", func(t *testing.T) {
		m := parseEximVersionOutput("Support for: crypteq OpenSSL Experimental_SRS\n")
		ok, err := m.defined("_HAVE_SRS")
		require.NoError(t, err)
		assert.True(t, ok)
		_, err = m.defined("_HAVE_NATIVE_SRS")
		assert.Error(t, err)
	})

	t.Run("no Support for line", func(t *testing.T) {
		assert.Nil(t, parseEximVersionOutput("exim: command not found\n"))
	})
}

func TestSplitEximListDoubledSeparator(t *testing.T) {
	// `local_interfaces = 127.0.0.1 : ::::1` on RHEL 9; Exim reads a doubled
	// ':' as a literal ':' and listens on 127.0.0.1 and ::1
	assert.Equal(t, []any{"127.0.0.1", "::1"}, parseEximListValue("127.0.0.1 : ::::1"))
	assert.Equal(t, []any{"0.0.0.0", "::0"}, parseEximListValue("0.0.0.0 : ::::0"))
	assert.Equal(t, []any{"127.0.0.1", "::1"},
		eximLocalInterfaces(map[string]any{"local_interfaces": "127.0.0.1 : ::::1"}))
	// a doubled separator in a '<;' list is a literal ';'
	assert.Equal(t, []any{"a;b", "c"}, parseEximListValue("<; a;;b ; c"))
	// a single ':' between items still separates them
	assert.Equal(t, []any{"127.0.0.1", "192.0.2.1"}, parseEximListValue("127.0.0.1:192.0.2.1"))
}

// eximVersionLookup answers built-in macros from captured `exim -bV` output,
// the source a non-admin user gets, and main-option macros from probe.
func eximVersionLookup(t *testing.T, name string, probe func(string) (bool, error)) eximBuiltinLookup {
	m := parseEximVersionOutput(readEximTestdata(t, name))
	require.NotNil(t, m)
	return func(macro string) (bool, error) {
		return m.lookup(macro, probe)
	}
}

func TestEximGeneratedConfigLocalInterfaces(t *testing.T) {
	// `exim4 -bP smtputf8_advertise_hosts` as the non-root user on Debian 12
	probeKnown := func(option string) (bool, error) {
		return parseEximOptionProbe(option, option+" = \n")
	}
	noProbe := func(option string) (bool, error) {
		t.Fatalf("unexpected probe for %s", option)
		return false, nil
	}

	cases := []struct {
		name   string
		file   string
		lookup eximBuiltinLookup
		want   []any
	}{
		// Debian 12's generated main section tests _OPT_MAIN_SMTPUTF8_ADVERTISE_HOSTS,
		// which `exim -bV` can't answer, so a non-root scan probes the option
		{"debian 12 non-root, dc_local_interfaces", "debian12-config.autogenerated", eximVersionLookup(t, "debian12-bV.txt", probeKnown), []any{"127.0.0.1", "::1"}},
		{"debian 12 non-root, localmacros", "debian12-config.autogenerated-localmacros", eximVersionLookup(t, "debian12-bV.txt", probeKnown), []any{"0.0.0.0", "::0"}},
		{"debian 12 root, localmacros", "debian12-config.autogenerated-localmacros", eximMacrosFrom(t, "debian12-bP-macros.txt"), []any{"0.0.0.0", "::0"}},
		// Debian 9's tests _HAVE_GNUTLS, which `exim -bV` answers
		{"debian 9 non-root, dc_local_interfaces", "debian9-config.autogenerated", eximVersionLookup(t, "debian9-bV.txt", noProbe), []any{"127.0.0.1", "::1"}},
		{"debian 9 non-root, localmacros", "debian9-config.autogenerated-localmacros", eximVersionLookup(t, "debian9-bV.txt", noProbe), []any{"0.0.0.0", "::0"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			params, err := parseEximConfig(readEximTestdata(t, tc.file), tc.lookup)
			require.NoError(t, err)
			assert.Equal(t, tc.want, eximLocalInterfaces(params))
		})
	}

	t.Run("the generated config without a built-in macro source is an error", func(t *testing.T) {
		_, err := parseEximConfig(readEximTestdata(t, "debian12-config.autogenerated"), nil)
		assert.Error(t, err)
	})
}

func TestEximBuiltinLookupMainOptionMacros(t *testing.T) {
	probed := []string{}
	probe := func(option string) (bool, error) {
		probed = append(probed, option)
		return option == "smtputf8_advertise_hosts", nil
	}

	// from `exim -bV`: _OPT_MAIN_* goes to the probe, feature macros don't
	v := parseEximVersionOutput(readEximTestdata(t, "debian12-bV.txt"))
	require.NotNil(t, v)
	got, err := v.lookup("_OPT_MAIN_SMTPUTF8_ADVERTISE_HOSTS", probe)
	require.NoError(t, err)
	assert.True(t, got)
	got, err = v.lookup("_OPT_MAIN_NO_SUCH_OPTION", probe)
	require.NoError(t, err)
	assert.False(t, got)
	got, err = v.lookup("_HAVE_GNUTLS", probe)
	require.NoError(t, err)
	assert.True(t, got)
	assert.Equal(t, []string{"smtputf8_advertise_hosts", "no_such_option"}, probed)
	// other macros outside the -bV set stay unknown
	_, err = v.lookup("_OPT_ROUTER_ACCEPT_DOMAINS", probe)
	assert.Error(t, err)

	// from `exim -bP macros` (root): the full set answers without a probe
	probed = probed[:0]
	m := parseEximMacrosOutput(readEximTestdata(t, "debian12-bP-macros.txt"))
	require.NotNil(t, m)
	got, err = m.lookup("_OPT_MAIN_SMTPUTF8_ADVERTISE_HOSTS", probe)
	require.NoError(t, err)
	assert.True(t, got)
	got, err = m.lookup("_OPT_MAIN_NO_SUCH_OPTION", probe)
	require.NoError(t, err)
	assert.False(t, got)
	assert.Empty(t, probed)
}

func TestParseEximOptionProbe(t *testing.T) {
	cases := []struct {
		name, option, out string
		want              bool
		wantErr           bool
	}{
		// Debian 12 (4.96) and 13 (4.98), non-root
		{"string option", "smtputf8_advertise_hosts", "smtputf8_advertise_hosts = \n", true, false},
		{"boolean option set", "prdr_enable", "prdr_enable\n", true, false},
		{"boolean option unset", "prdr_enable", "no_prdr_enable\n", true, false},
		// Debian 9 (4.89) prints this on stdout and exits 0
		{"unknown option", "smtputf8_advertise_hosts", "smtputf8_advertise_hosts is not a known option\n", false, false},
		{"other output", "smtputf8_advertise_hosts", "exim: permission denied\n", false, true},
		{"empty output", "smtputf8_advertise_hosts", "", false, true},
		{"prefix of a longer option", "tls", "tls_certificate = \n", false, true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := parseEximOptionProbe(tc.option, tc.out)
			if tc.wantErr {
				assert.Error(t, err)
				return
			}
			require.NoError(t, err)
			assert.Equal(t, tc.want, got)
		})
	}
}

func TestEximMainOptionMacro(t *testing.T) {
	opt, ok := eximMainOptionMacro("_OPT_MAIN_SMTPUTF8_ADVERTISE_HOSTS")
	assert.True(t, ok)
	assert.Equal(t, "smtputf8_advertise_hosts", opt)
	for _, name := range []string{"_HAVE_GNUTLS", "_OPT_MAIN_", "_OPT_ROUTER_ACCEPT_DOMAINS", "_OPT_MAIN_X;reboot"} {
		_, ok := eximMainOptionMacro(name)
		assert.False(t, ok, name)
	}
}

func TestEximDaemonInterfaces(t *testing.T) {
	// /proc/<pid>/cmdline of exim4 daemons on Debian 12 and 13
	oX := haproxy.SplitProcCmdline([]byte(readEximTestdata(t, "debian12-daemon-oX.cmdline")))
	require.Equal(t, []string{"/usr/sbin/exim4", "-bd", "-q30m", "-oX", "<;0.0.0.0.25;::0.25"}, oX)
	plain := haproxy.SplitProcCmdline([]byte(readEximTestdata(t, "debian13-daemon.cmdline")))
	require.Equal(t, []string{"/usr/sbin/exim4", "-bdf", "-q30m"}, plain)

	assert.True(t, isEximDaemon(oX))
	assert.True(t, isEximDaemon(plain))
	assert.False(t, isEximDaemon([]string{"/usr/sbin/exim4", "-q30m"}))
	assert.False(t, isEximDaemon([]string{"/usr/sbin/exim4", "-bP", "local_interfaces"}))
	assert.False(t, isEximDaemon([]string{"/usr/bin/vim", "-bd"}))
	assert.True(t, isEximDaemon([]string{"exim", "-bd"}))

	assert.Equal(t, []any{"0.0.0.0.25", "::0.25"}, eximOverrideInterfaces(oX[1:]))
	assert.Nil(t, eximOverrideInterfaces(plain[1:]))
	// the port list the Debian defaults file recommends: no interfaces
	assert.Nil(t, eximOverrideInterfaces([]string{"-bd", "-oX", "25:587:10025", "-oP", "/run/exim4/exim.pid"}))
	// an item with a dot or colon is an interface, the rest are ports
	assert.Equal(t, []any{"127.0.0.1.25"}, eximOverrideInterfaces([]string{"-oX", "25:127.0.0.1.25"}))
	// the last -oX wins
	assert.Equal(t, []any{"192.0.2.10"}, eximOverrideInterfaces([]string{"-oX", "0.0.0.0", "-oX", "192.0.2.10"}))
	assert.Nil(t, eximOverrideInterfaces([]string{"-oX"}))

	configured := []any{"127.0.0.1", "::1"}
	t.Run("no daemon reports the config", func(t *testing.T) {
		assert.Equal(t, configured, eximListenInterfaces(configured, nil))
	})
	t.Run("a daemon without -oX reports the config", func(t *testing.T) {
		assert.Equal(t, configured, eximListenInterfaces(configured, [][]string{plain[1:]}))
	})
	t.Run("-oX replaces the config", func(t *testing.T) {
		assert.Equal(t, []any{"0.0.0.0.25", "::0.25"}, eximListenInterfaces(configured, [][]string{oX[1:]}))
	})
	t.Run("several daemons listen on the union", func(t *testing.T) {
		assert.Equal(t, []any{"0.0.0.0.25", "::0.25", "127.0.0.1", "::1"},
			eximListenInterfaces(configured, [][]string{oX[1:], plain[1:], oX[1:]}))
	})
}

func TestEximDefaultsDaemonArgs(t *testing.T) {
	deb12 := readEximTestdata(t, "debian12-default-exim4")
	deb13 := readEximTestdata(t, "debian13-default-exim4")

	t.Run("init script, stock file", func(t *testing.T) {
		assert.Nil(t, eximOverrideInterfaces(eximDefaultsDaemonArgs(deb12, false)))
	})
	t.Run("init script reads SMTPLISTENEROPTIONS", func(t *testing.T) {
		content := deb12 + "SMTPLISTENEROPTIONS='-oX <;0.0.0.0.25;::0.25'\n"
		assert.Equal(t, []any{"0.0.0.0.25", "::0.25"}, eximOverrideInterfaces(eximDefaultsDaemonArgs(content, false)))
	})
	t.Run("init script reads COMMONOPTIONS", func(t *testing.T) {
		content := strings.Replace(deb12, "COMMONOPTIONS=''", "COMMONOPTIONS='-oX 0.0.0.0.25'", 1)
		assert.Equal(t, []any{"0.0.0.0.25"}, eximOverrideInterfaces(eximDefaultsDaemonArgs(content, false)))
	})
	t.Run("the systemd unit ignores SMTPLISTENEROPTIONS", func(t *testing.T) {
		content := deb13 + "SMTPLISTENEROPTIONS='-oX <;0.0.0.0.25;::0.25'\n"
		assert.Nil(t, eximOverrideInterfaces(eximDefaultsDaemonArgs(content, true)))
	})
	t.Run("the systemd unit reads EXIMSERVICE", func(t *testing.T) {
		content := deb13 + "EXIMSERVICE='-bdf -q30m -oX <;0.0.0.0.25;::0.25'\n"
		assert.Equal(t, []any{"0.0.0.0.25", "::0.25"}, eximOverrideInterfaces(eximDefaultsDaemonArgs(content, true)))
	})
}

// Exim reads .include files in place. On SLES 15 SP7 the main file's
// `.include /etc/exim/sweep-main.conf` set local_interfaces, and
// `exim -bP local_interfaces` reported the included value, while mql
// reported the unset default.
func TestParseEximConfigIncludes(t *testing.T) {
	files := map[string]string{
		"/etc/exim/sweep-main.conf":     "local_interfaces = <; 127.0.0.2\n",
		"/etc/exim/conf.d/tls.conf":     "tls_advertise_hosts =\n.include_if_exists /etc/exim/conf.d/missing.conf\n",
		"/etc/exim/conf.d/macro.conf":   "LISTEN = 192.0.2.1\n",
		"/etc/exim/conf.d/skipped.conf": "smtp_banner = skipped\n",
		"/etc/exim/conf.d/routers.conf": "begin routers\nnot_main = 1\n",
	}
	var opened []string
	read := func(path string) (string, bool, error) {
		opened = append(opened, path)
		c, ok := files[path]
		return c, ok, nil
	}

	t.Run("absolute, relative and conditional includes", func(t *testing.T) {
		opened = nil
		content := "primary_hostname = mail.example.test\n" +
			".include /etc/exim/sweep-main.conf\n" +
			".include conf.d/tls.conf\n" +
			".include_if_exists /etc/exim/conf.d/macro.conf\n" +
			"daemon_smtp_ports = LISTEN\n" +
			".ifdef NOT_DEFINED\n" +
			".include /etc/exim/conf.d/skipped.conf\n" +
			".endif\n" +
			".include \"/etc/exim/conf.d/routers.conf\"\n" +
			"after_begin = 1\n"
		got, err := parseEximConfigFile("/etc/exim/exim.conf", content, nil, read)
		require.NoError(t, err)
		assert.Equal(t, map[string]any{
			"primary_hostname":    "mail.example.test",
			"local_interfaces":    "<; 127.0.0.2",
			"tls_advertise_hosts": "",
			"LISTEN":              "192.0.2.1",
			"daemon_smtp_ports":   "192.0.2.1",
		}, got)
		assert.NotContains(t, opened, "/etc/exim/conf.d/skipped.conf", "an include in a skipped branch is not read")
	})

	t.Run("a missing .include is an error", func(t *testing.T) {
		_, err := parseEximConfigFile("/etc/exim/exim.conf", ".include /etc/exim/nope.conf\n", nil, read)
		require.Error(t, err)
	})

	t.Run(".include_if_exists needs an absolute path", func(t *testing.T) {
		_, err := parseEximConfigFile("/etc/exim/exim.conf", ".include_if_exists conf.d/tls.conf\n", nil, read)
		require.Error(t, err)
	})

	t.Run("an unreadable include is an error", func(t *testing.T) {
		denied := func(string) (string, bool, error) { return "", false, errors.New("permission denied") }
		_, err := parseEximConfigFile("/etc/exim/exim.conf", ".include /etc/exim/sweep-main.conf\n", nil, denied)
		require.Error(t, err)
	})

	t.Run("an include cycle stops", func(t *testing.T) {
		self := func(string) (string, bool, error) { return ".include /etc/exim/exim.conf\n", true, nil }
		_, err := parseEximConfigFile("/etc/exim/exim.conf", ".include /etc/exim/exim.conf\n", nil, self)
		require.Error(t, err)
	})
}
