// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package resources

import (
	"errors"
	"io"
	"io/fs"
	"strings"

	"go.mondoo.com/mql/llx"
	"go.mondoo.com/mql/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/providers/os/connection/shared"
)

const (
	// Debian's exim4 split config keeps the dc_* control values, including
	// dc_local_interfaces, in this file.
	debianEximConfig = "/etc/exim4/update-exim4.conf.conf"
	// Debian's exim4 reads this hand-written monolithic config in place of
	// the one update-exim4.conf generates whenever the file exists
	debianEximCustomConfig = "/etc/exim4/exim4.conf"
	// the monolithic configuration used by RHEL and most source installs
	monolithicEximConfig = "/etc/exim/exim.conf"
)

// eximDefaultLocalInterfaces is what Exim listens on when local_interfaces
// is unset: every IPv6 and IPv4 interface. `exim -bP local_interfaces`
// reports it as `<; ::0 ; 0.0.0.0`.
var eximDefaultLocalInterfaces = []string{"::0", "0.0.0.0"}

func (e *mqlExim) id() (string, error) {
	// a constant id keeps creation cheap; configPath() may shell out to
	// `exim -bP` to locate a non-standard config, which shouldn't run just
	// to compute the cache key
	return "exim", nil
}

func initExim(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error) {
	if x, ok := args["path"]; ok && x != nil {
		path, ok := x.Value.(string)
		if !ok {
			return nil, nil, errors.New("wrong type for 'path' in exim initialization, it must be a string")
		}
		args["configPath"] = llx.StringData(path)
		delete(args, "path")
	}
	return args, nil, nil
}

func (e *mqlExim) configPath() (string, error) {
	// only reached when no path was supplied via init
	conn := e.MqlRuntime.Connection.(shared.Connection)
	if asset := conn.Asset(); asset != nil && asset.Platform != nil && asset.Platform.IsFamily("debian") {
		// Debian's exim4 binary is built with
		// CONFIGURE_FILE=/etc/exim4/exim4.conf:/var/lib/exim4/config.autogenerated,
		// so a hand-written exim4.conf replaces the generated config and the
		// dc_* control values no longer apply
		if _, err := conn.FileSystem().Stat(debianEximCustomConfig); err == nil {
			return debianEximCustomConfig, nil
		} else if !errors.Is(err, fs.ErrNotExist) {
			return "", err
		}
		// otherwise exim4-config generates the config from its split-config
		// control file, which carries dc_local_interfaces
		return debianEximConfig, nil
	}

	// otherwise ask Exim where its configuration lives — this handles BSD
	// ports/pkgsrc, source installs, and other non-standard prefixes rather
	// than assuming /etc/exim/exim.conf
	if path := e.eximConfigureFile(); path != "" {
		return path, nil
	}
	return monolithicEximConfig, nil
}

// eximConfigureFile returns the configuration file Exim itself reports via
// `exim -bP configure_file`, or "" when the binary is unavailable.
func (e *mqlExim) eximConfigureFile() string {
	o, err := CreateResource(e.MqlRuntime, "command", map[string]*llx.RawData{
		"command": llx.StringData("exim -bP configure_file"),
	})
	if err != nil {
		return ""
	}
	cmd := o.(*mqlCommand)

	exit := cmd.GetExitcode()
	if exit.Error != nil || exit.Data != 0 {
		return ""
	}
	stdout := cmd.GetStdout()
	if stdout.Error != nil {
		return ""
	}

	// configure_file reports the single config file in use; take the first line
	path := strings.TrimSpace(stdout.Data)
	if idx := strings.IndexByte(path, '\n'); idx >= 0 {
		path = strings.TrimSpace(path[:idx])
	}
	// Exim prints just the path here, but normalize defensively in case a build
	// emits the general `optionname = value` form so the prefix doesn't leak
	// into the path and break the file read
	if rest, ok := strings.CutPrefix(path, "configure_file"); ok {
		if after, ok := strings.CutPrefix(strings.TrimSpace(rest), "="); ok {
			path = strings.TrimSpace(after)
		}
	}
	return path
}

func (e *mqlExim) params() (map[string]any, error) {
	configPath := e.GetConfigPath()
	if configPath.Error != nil {
		return nil, configPath.Error
	}
	content, err := e.readFile(configPath.Data)
	if err != nil {
		return nil, err
	}
	return parseEximConfig(content), nil
}

func (e *mqlExim) localInterfaces() ([]any, error) {
	params := e.GetParams()
	if params.Error != nil {
		return nil, params.Error
	}
	return eximLocalInterfaces(params.Data), nil
}

// eximLocalInterfaces returns the interfaces Exim listens on for the parsed
// config. An unset or empty setting means all interfaces, matching Exim's
// own default; only a missing config (no params at all) yields an empty list.
func eximLocalInterfaces(params map[string]any) []any {
	if len(params) == 0 {
		return []any{}
	}

	// Debian split config: dc_local_interfaces is a ' ; '-separated string.
	// update-exim4.conf only emits MAIN_LOCAL_INTERFACES (and with it
	// local_interfaces) when the value is non-empty.
	if v, ok := params["dc_local_interfaces"].(string); ok {
		if res := splitEximList(v, ";"); len(res) > 0 {
			return res
		}
		return eximDefaultInterfaceList()
	}
	// monolithic exim.conf: local_interfaces is an Exim list (default ':'
	// separator, overridable with a leading '<sep')
	if v, ok := params["local_interfaces"].(string); ok {
		if res := parseEximListValue(v); len(res) > 0 {
			return res
		}
	}
	return eximDefaultInterfaceList()
}

func eximDefaultInterfaceList() []any {
	res := make([]any, len(eximDefaultLocalInterfaces))
	for i, v := range eximDefaultLocalInterfaces {
		res[i] = v
	}
	return res
}

// readFile reads a config file from the target's filesystem. A missing file
// yields empty content rather than an error, so an MTA that isn't installed
// resolves cleanly.
func (e *mqlExim) readFile(path string) (string, error) {
	conn := e.MqlRuntime.Connection.(shared.Connection)
	f, err := conn.FileSystem().Open(path)
	if err != nil {
		// the connection's virtual filesystem may not return *os.PathError,
		// so match the wrapped sentinel rather than using os.IsNotExist
		if errors.Is(err, fs.ErrNotExist) {
			return "", nil
		}
		return "", err
	}
	defer f.Close()

	data, err := io.ReadAll(f)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// parseEximConfig parses the macros and main-section options of an Exim config.
// It handles both the Debian `KEY='value'` form and the monolithic `key = value`
// form, folds backslash continuations, strips comments, and stops at the first
// `begin <section>` block (routers, transports, acl, …) so only the main
// section and macros are returned. Like Exim's own preprocessor it evaluates
// `.ifdef`/`.ifndef`/`.elifdef`/`.elifndef`/`.else`/`.endif` against the macros
// defined so far and substitutes macro references in values, so
// `local_interfaces = MAIN_LOCAL_INTERFACES` reports the macro's value. Keys
// that are not simple assignments (named lists like `domainlist x = …`, ACL
// conditions) are skipped.
func parseEximConfig(content string) map[string]any {
	params := map[string]any{}
	macros := map[string]string{}
	cond := eximConditionals{}

	for _, line := range joinEximContinuations(content) {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		if strings.HasPrefix(trimmed, ".") {
			directive, arg, _ := strings.Cut(trimmed, " ")
			_, defined := macros[strings.TrimSpace(arg)]
			cond.apply(directive, defined)
			// other directives (.include, .include_if_exists) are not followed
			continue
		}
		if !cond.active() {
			continue
		}

		// the main section ends at the first `begin <section>` directive
		if trimmed == "begin" || strings.HasPrefix(trimmed, "begin ") {
			break
		}

		idx := strings.Index(trimmed, "=")
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(trimmed[:idx])
		key = strings.TrimSpace(strings.TrimPrefix(key, "hide ")) // `hide key = value`
		// a simple option or macro has a single-token name; skip named lists
		// (`domainlist x = …`) and other multi-token left-hand sides
		if key == "" || strings.ContainsAny(key, " \t") {
			continue
		}
		value := trimmed[idx+1:]

		if isEximMacroName(key) {
			// `NAME == value` redefines an existing macro
			value = strings.TrimPrefix(value, "=")
			value = substituteEximMacros(strings.TrimSpace(value), macros)
			macros[key] = value
			params[key] = unquoteEximValue(value)
			continue
		}

		value = substituteEximMacros(strings.TrimSpace(value), macros)
		params[key] = unquoteEximValue(value)
	}
	return params
}

// eximConditionals tracks nested .ifdef/.ifndef blocks.
type eximConditionals struct {
	// one entry per open block: whether the current branch is taken, and
	// whether any branch of the block has been taken yet
	taken []bool
	done  []bool
}

func (c *eximConditionals) active() bool {
	for _, t := range c.taken {
		if !t {
			return false
		}
	}
	return true
}

func (c *eximConditionals) apply(directive string, defined bool) {
	switch directive {
	case ".ifdef", ".ifndef":
		ok := defined == (directive == ".ifdef")
		c.taken = append(c.taken, ok)
		c.done = append(c.done, ok)
	case ".elifdef", ".elifndef":
		if n := len(c.taken); n > 0 {
			ok := !c.done[n-1] && defined == (directive == ".elifdef")
			c.taken[n-1] = ok
			c.done[n-1] = c.done[n-1] || ok
		}
	case ".else":
		if n := len(c.taken); n > 0 {
			c.taken[n-1] = !c.done[n-1]
			c.done[n-1] = true
		}
	case ".endif":
		if n := len(c.taken); n > 0 {
			c.taken = c.taken[:n-1]
			c.done = c.done[:n-1]
		}
	}
}

// isEximMacroName reports whether name is a macro name: it starts with an
// upper-case letter and continues with letters, digits and underscores.
func isEximMacroName(name string) bool {
	if name == "" || name[0] < 'A' || name[0] > 'Z' {
		return false
	}
	for i := 1; i < len(name); i++ {
		if !isEximMacroChar(name[i]) {
			return false
		}
	}
	return true
}

func isEximMacroChar(c byte) bool {
	return c == '_' || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')
}

// substituteEximMacros replaces whole-word references to defined macros in
// value. Exim matches macro names as substrings; whole words avoid rewriting
// a longer name that merely contains a shorter macro's name.
func substituteEximMacros(value string, macros map[string]string) string {
	if len(macros) == 0 {
		return value
	}
	var out strings.Builder
	for i := 0; i < len(value); {
		if value[i] >= 'A' && value[i] <= 'Z' && (i == 0 || !isEximMacroChar(value[i-1])) {
			j := i + 1
			for j < len(value) && isEximMacroChar(value[j]) {
				j++
			}
			if repl, ok := macros[value[i:j]]; ok {
				out.WriteString(repl)
				i = j
				continue
			}
			out.WriteString(value[i:j])
			i = j
			continue
		}
		out.WriteByte(value[i])
		i++
	}
	return out.String()
}

// joinEximContinuations joins lines ending in a backslash with the following
// line, matching Exim's line-continuation rule.
func joinEximContinuations(content string) []string {
	var logical []string
	var buf strings.Builder
	continuing := false

	for _, raw := range strings.Split(content, "\n") {
		line := strings.TrimRight(raw, "\r")
		if continuing {
			buf.WriteString(strings.TrimLeft(line, " \t"))
		} else {
			buf.Reset()
			buf.WriteString(line)
		}

		if strings.HasSuffix(strings.TrimRight(line, " \t"), "\\") {
			s := strings.TrimSuffix(strings.TrimRight(buf.String(), " \t"), "\\")
			buf.Reset()
			buf.WriteString(s)
			continuing = true
			continue
		}

		logical = append(logical, buf.String())
		continuing = false
	}
	if continuing {
		logical = append(logical, buf.String())
	}
	return logical
}

// unquoteEximValue strips a matching pair of surrounding single or double
// quotes (the Debian split config quotes its values).
func unquoteEximValue(value string) string {
	if len(value) >= 2 {
		first, last := value[0], value[len(value)-1]
		if (first == '\'' && last == '\'') || (first == '"' && last == '"') {
			return value[1 : len(value)-1]
		}
	}
	return value
}

// parseEximListValue parses an Exim list, honoring the optional `<sep` prefix
// that selects a non-default separator (needed for IPv6 addresses, which
// otherwise collide with the default ':' separator).
func parseEximListValue(value string) []any {
	value = strings.TrimSpace(value)
	sep := ":"
	if strings.HasPrefix(value, "<") && len(value) >= 2 {
		sep = string(value[1])
		value = strings.TrimSpace(value[2:])
	}
	return splitEximList(value, sep)
}

// splitEximList splits value on sep and trims each token, dropping empties.
func splitEximList(value, sep string) []any {
	res := []any{}
	for _, tok := range strings.Split(value, sep) {
		if tok = strings.TrimSpace(tok); tok != "" {
			res = append(res, tok)
		}
	}
	return res
}
