// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package resources

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestParseEximConfig(t *testing.T) {
	t.Run("Debian split-config key='value' form", func(t *testing.T) {
		content := "# update-exim4.conf.conf\n" +
			"dc_eximconfig_configtype='internet'\n" +
			"dc_local_interfaces='127.0.0.1 ; ::1'\n" +
			"dc_readhost=''\n"
		got := parseEximConfig(content)
		assert.Equal(t, "internet", got["dc_eximconfig_configtype"])
		assert.Equal(t, "127.0.0.1 ; ::1", got["dc_local_interfaces"])
		assert.Equal(t, "", got["dc_readhost"])
	})

	t.Run("monolithic key = value form with macros", func(t *testing.T) {
		content := "# exim.conf\n" +
			"MACRO = /var/spool/exim\n" +
			"local_interfaces = <; 127.0.0.1 ; ::1\n" +
			"primary_hostname = mail.example.com\n"
		got := parseEximConfig(content)
		assert.Equal(t, "/var/spool/exim", got["MACRO"])
		assert.Equal(t, "<; 127.0.0.1 ; ::1", got["local_interfaces"])
		assert.Equal(t, "mail.example.com", got["primary_hostname"])
	})

	t.Run("stops at the first begin block", func(t *testing.T) {
		content := "primary_hostname = mail.example.com\n" +
			"begin acl\n" +
			"acl_check_rcpt:\n" +
			"  accept hosts = +relay = something\n"
		got := parseEximConfig(content)
		assert.Equal(t, "mail.example.com", got["primary_hostname"])
		_, hasAcl := got["acl_check_rcpt:"]
		assert.False(t, hasAcl)
		// an option-looking line inside the section must not leak in
		_, leaked := got["accept hosts"]
		assert.False(t, leaked)
	})

	t.Run("hide prefix and named lists", func(t *testing.T) {
		content := "hide mysql_servers = localhost/db/user/secret\n" +
			"domainlist local_domains = @\n"
		got := parseEximConfig(content)
		assert.Equal(t, "localhost/db/user/secret", got["mysql_servers"])
		// named-list left-hand side has two tokens; it is not a simple option
		_, hasNamedList := got["domainlist local_domains"]
		assert.False(t, hasNamedList)
	})

	t.Run("backslash continuation", func(t *testing.T) {
		content := "local_interfaces = <; 127.0.0.1 ; \\\n  ::1\n"
		got := parseEximConfig(content)
		assert.Equal(t, "<; 127.0.0.1 ; ::1", got["local_interfaces"])
	})
}

func TestUnquoteEximValue(t *testing.T) {
	assert.Equal(t, "127.0.0.1 ; ::1", unquoteEximValue("'127.0.0.1 ; ::1'"))
	assert.Equal(t, "internet", unquoteEximValue(`"internet"`))
	assert.Equal(t, "", unquoteEximValue("''"))
	assert.Equal(t, "unquoted", unquoteEximValue("unquoted"))
	assert.Equal(t, "'mismatched", unquoteEximValue("'mismatched"))
}

func TestParseEximListValue(t *testing.T) {
	// custom separator via the <sep prefix (needed for IPv6)
	assert.Equal(t, []any{"127.0.0.1", "::1"}, parseEximListValue("<; 127.0.0.1 ; ::1"))
	// default ':' separator
	assert.Equal(t, []any{"127.0.0.1", "192.168.0.1"}, parseEximListValue("127.0.0.1 : 192.168.0.1"))
	assert.Equal(t, []any{"127.0.0.1"}, parseEximListValue("127.0.0.1"))
}

func TestSplitEximList(t *testing.T) {
	assert.Equal(t, []any{"127.0.0.1", "::1"}, splitEximList("127.0.0.1 ; ::1", ";"))
	assert.Equal(t, []any{}, splitEximList("", ";"))
}

// debianAutogenerated is the main section of /var/lib/exim4/config.autogenerated
// as written by update-exim4.conf on Ubuntu 24.04 (exim4 4.97) with
// dc_local_interfaces='127.0.0.1 ; ::1'.
const debianAutogenerated = `exim_path = /usr/sbin/exim4

.ifndef CONFDIR
CONFDIR = /etc/exim4
.endif

UPEX4CmacrosUPEX4C = 1
##############################################
# the following macro definitions were created
# dynamically by /usr/sbin/update-exim4.conf
.ifndef MAIN_LOCAL_INTERFACES
MAIN_LOCAL_INTERFACES=<; 127.0.0.1 ; ::1
.endif
.ifndef MAIN_LOCAL_DOMAINS
MAIN_LOCAL_DOMAINS=@:localhost:mail.example.test
.endif
.ifndef ETC_MAILNAME
ETC_MAILNAME=mail.example.test
.endif
##############################################

domainlist local_domains = MAIN_LOCAL_DOMAINS

.ifndef MAIN_PRIMARY_HOSTNAME_AS_QUALIFY_DOMAIN
.ifndef MAIN_QUALIFY_DOMAIN
qualify_domain = ETC_MAILNAME
.else
qualify_domain = MAIN_QUALIFY_DOMAIN
.endif
.endif

.ifdef MAIN_LOCAL_INTERFACES
local_interfaces = MAIN_LOCAL_INTERFACES
.endif

.ifndef LOCAL_DELIVERY
LOCAL_DELIVERY=mail_spool
.endif
`

func TestParseEximConfigMacros(t *testing.T) {
	t.Run("macro reference in an option is resolved", func(t *testing.T) {
		got := parseEximConfig(debianAutogenerated)
		assert.Equal(t, "<; 127.0.0.1 ; ::1", got["MAIN_LOCAL_INTERFACES"])
		assert.Equal(t, "<; 127.0.0.1 ; ::1", got["local_interfaces"])
		assert.Equal(t, []any{"127.0.0.1", "::1"}, eximLocalInterfaces(got))
	})

	t.Run(".ifndef/.else picks the branch for undefined macros", func(t *testing.T) {
		got := parseEximConfig(debianAutogenerated)
		// MAIN_QUALIFY_DOMAIN is undefined, so the .ifndef branch applies
		assert.Equal(t, "mail.example.test", got["qualify_domain"])
	})

	t.Run(".ifndef skips a redefinition of a defined macro", func(t *testing.T) {
		got := parseEximConfig("CONFDIR = /srv/exim\n" + debianAutogenerated)
		assert.Equal(t, "/srv/exim", got["CONFDIR"])
	})

	t.Run("an earlier macro overrides the generated default", func(t *testing.T) {
		// exim4.conf.localmacros content lands ahead of the generated block
		got := parseEximConfig("MAIN_LOCAL_INTERFACES = <; 0.0.0.0 ; ::0\n" + debianAutogenerated)
		assert.Equal(t, []any{"0.0.0.0", "::0"}, eximLocalInterfaces(got))
	})

	t.Run("undefined macro leaves local_interfaces unset", func(t *testing.T) {
		// update-exim4.conf omits the MAIN_LOCAL_INTERFACES block when
		// dc_local_interfaces is empty, so the .ifdef is false
		content := strings.Replace(debianAutogenerated,
			".ifndef MAIN_LOCAL_INTERFACES\nMAIN_LOCAL_INTERFACES=<; 127.0.0.1 ; ::1\n.endif\n", "", 1)
		got := parseEximConfig(content)
		_, ok := got["local_interfaces"]
		assert.False(t, ok)
		assert.Equal(t, []any{"::0", "0.0.0.0"}, eximLocalInterfaces(got))
	})

	t.Run("macro names match whole words only", func(t *testing.T) {
		got := parseEximConfig("PORT = 25\nPORTS = 587\ndaemon_smtp_ports = PORTS : PORT\n")
		assert.Equal(t, "587 : 25", got["daemon_smtp_ports"])
	})

	t.Run("== redefines a macro", func(t *testing.T) {
		got := parseEximConfig("IFACES = 127.0.0.1\nIFACES == 192.0.2.10\nlocal_interfaces = IFACES\n")
		assert.Equal(t, "192.0.2.10", got["local_interfaces"])
	})
}

func TestEximLocalInterfaces(t *testing.T) {
	t.Run("Debian dc_local_interfaces", func(t *testing.T) {
		assert.Equal(t, []any{"127.0.0.1", "::1"},
			eximLocalInterfaces(map[string]any{"dc_local_interfaces": "127.0.0.1 ; ::1"}))
	})

	t.Run("empty Debian dc_local_interfaces listens on all interfaces", func(t *testing.T) {
		// update-exim4.conf.conf from Ubuntu with dc_local_interfaces=''; exim4 -bP
		// local_interfaces then reports `<; ::0 ; 0.0.0.0` and binds 0.0.0.0:25 and [::]:25
		params := parseEximConfig("dc_eximconfig_configtype='local'\n" +
			"dc_local_interfaces=''\n" +
			"dc_use_split_config='false'\n")
		assert.Equal(t, []any{"::0", "0.0.0.0"}, eximLocalInterfaces(params))
	})

	t.Run("monolithic local_interfaces", func(t *testing.T) {
		assert.Equal(t, []any{"0.0.0.0", "::0"},
			eximLocalInterfaces(map[string]any{"local_interfaces": "<; 0.0.0.0 ; ::0"}))
	})

	t.Run("monolithic config without local_interfaces listens on all interfaces", func(t *testing.T) {
		assert.Equal(t, []any{"::0", "0.0.0.0"},
			eximLocalInterfaces(map[string]any{"primary_hostname": "mail.example.com"}))
	})

	t.Run("no configuration yields no interfaces", func(t *testing.T) {
		assert.Equal(t, []any{}, eximLocalInterfaces(map[string]any{}))
	})
}
