// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package resources

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"path"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/rs/zerolog/log"
	"github.com/spf13/afero"
	"go.mondoo.com/mql/llx"
	"go.mondoo.com/mql/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/providers/os/connection/shared"
	"go.mondoo.com/mql/providers/os/resources/haproxy"
)

const (
	// Debian's exim4 split config keeps the dc_* control values, including
	// dc_local_interfaces, in this file.
	debianEximConfig = "/etc/exim4/update-exim4.conf.conf"
	// Debian's exim4 reads this hand-written monolithic config in place of
	// the one update-exim4.conf generates whenever the file exists
	debianEximCustomConfig = "/etc/exim4/exim4.conf"
	// the monolithic configuration used by RHEL and most source installs
	monolithicEximConfig = "/etc/exim/exim.conf"
	// the config update-exim4.conf generates on Debian, and the one Exim
	// loads when there is no hand-written exim4.conf. It combines
	// update-exim4.conf.conf with exim4.conf.localmacros and the template.
	debianEximGeneratedConfig = "/var/lib/exim4/config.autogenerated"
	// the daemon options the Debian init script and systemd unit read
	debianEximDefaults = "/etc/default/exim4"
)

// eximUnitDirs lists where systemd looks for exim4.service.
var eximUnitDirs = []string{
	"/etc/systemd/system",
	"/run/systemd/system",
	"/usr/lib/systemd/system",
	"/lib/systemd/system",
}

// eximDefaultLocalInterfaces is what Exim listens on when local_interfaces
// is unset: every IPv6 and IPv4 interface. `exim -bP local_interfaces`
// reports it as `<; ::0 ; 0.0.0.0`.
var eximDefaultLocalInterfaces = []string{"::0", "0.0.0.0"}

func (e *mqlExim) id() (string, error) {
	// a constant id keeps creation cheap; configPath() may shell out to
	// `exim -bP` to locate a non-standard config, which shouldn't run just
	// to compute the cache key
	return "exim", nil
}

func initExim(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error) {
	if x, ok := args["path"]; ok && x != nil {
		path, ok := x.Value.(string)
		if !ok {
			return nil, nil, errors.New("wrong type for 'path' in exim initialization, it must be a string")
		}
		args["configPath"] = llx.StringData(path)
		delete(args, "path")
	}
	return args, nil, nil
}

func (e *mqlExim) configPath() (string, error) {
	// only reached when no path was supplied via init
	return e.detectConfigPath()
}

func (e *mqlExim) isDebian() bool {
	conn := e.MqlRuntime.Connection.(shared.Connection)
	asset := conn.Asset()
	return asset != nil && asset.Platform != nil && asset.Platform.IsFamily("debian")
}

// detectConfigPath returns the config file of the installed Exim.
func (e *mqlExim) detectConfigPath() (string, error) {
	conn := e.MqlRuntime.Connection.(shared.Connection)
	if e.isDebian() {
		// Debian's exim4 binary is built with
		// CONFIGURE_FILE=/etc/exim4/exim4.conf:/var/lib/exim4/config.autogenerated,
		// so a hand-written exim4.conf replaces the generated config and the
		// dc_* control values no longer apply
		if _, err := conn.FileSystem().Stat(debianEximCustomConfig); err == nil {
			return debianEximCustomConfig, nil
		} else if !errors.Is(err, fs.ErrNotExist) {
			return "", err
		}
		// otherwise exim4-config generates the config from its split-config
		// control file, which carries dc_local_interfaces
		return debianEximConfig, nil
	}

	// otherwise ask Exim where its configuration lives — this handles BSD
	// ports/pkgsrc, source installs, and other non-standard prefixes rather
	// than assuming /etc/exim/exim.conf
	if path := e.eximConfigureFile(); path != "" {
		return path, nil
	}
	return monolithicEximConfig, nil
}

// eximConfigureFile returns the configuration file Exim itself reports via
// `exim -bP configure_file`, or "" when the binary is unavailable.
func (e *mqlExim) eximConfigureFile() string {
	stdout, exit, err := e.runExim("-bP configure_file")
	if err != nil || exit != 0 {
		return ""
	}

	// configure_file reports the single config file in use; take the first line
	path := strings.TrimSpace(stdout)
	if idx := strings.IndexByte(path, '\n'); idx >= 0 {
		path = strings.TrimSpace(path[:idx])
	}
	// Exim prints just the path here, but normalize defensively in case a build
	// emits the general `optionname = value` form so the prefix doesn't leak
	// into the path and break the file read
	if rest, ok := strings.CutPrefix(path, "configure_file"); ok {
		if after, ok := strings.CutPrefix(strings.TrimSpace(rest), "="); ok {
			path = strings.TrimSpace(after)
		}
	}
	return path
}

func (e *mqlExim) params() (map[string]any, error) {
	configPath := e.GetConfigPath()
	if configPath.Error != nil {
		return nil, configPath.Error
	}
	if err := e.explicitConfigExists(configPath.Data); err != nil {
		return nil, err
	}
	content, err := e.readFile(configPath.Data)
	if err != nil {
		return nil, err
	}
	return parseEximConfigFile(configPath.Data, content, e.builtinMacros(), e.readInclude)
}

// explicitConfigExists returns an error when exim(path) names a file that
// does not exist, as snmpd.config and nginx.conf do. A missing config at the
// installed Exim's own location means Exim is not configured and reads as
// empty.
func (e *mqlExim) explicitConfigExists(configPath string) error {
	conn := e.MqlRuntime.Connection.(shared.Connection)
	if _, err := conn.FileSystem().Stat(configPath); !errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	detected, err := e.detectConfigPath()
	if err != nil {
		return err
	}
	if detected == configPath {
		return nil
	}
	return fmt.Errorf("could not read %q: no such file", configPath)
}

// eximBinaries are the names tried, in order, to run Exim. The absolute
// paths cover a non-root login whose PATH has no sbin directory (RHEL 7),
// and Debian installs the binary as exim4.
var eximBinaries = []string{"exim", "/usr/sbin/exim", "exim4", "/usr/sbin/exim4"}

// runExim runs Exim with args and returns its stdout and exit code. A binary
// the shell can't find (exit 127) moves on to the next name.
func (e *mqlExim) runExim(args string) (string, int64, error) {
	var exit int64 = 127
	for _, bin := range eximBinaries {
		o, err := CreateResource(e.MqlRuntime, "command", map[string]*llx.RawData{
			"command": llx.StringData(bin + " " + args),
		})
		if err != nil {
			return "", 0, err
		}
		cmd := o.(*mqlCommand)
		code := cmd.GetExitcode()
		if code.Error != nil {
			return "", 0, code.Error
		}
		exit = code.Data
		if exit == 127 {
			continue
		}
		stdout := cmd.GetStdout()
		if stdout.Error != nil {
			return "", 0, stdout.Error
		}
		return stdout.Data, exit, nil
	}
	return "", exit, nil
}

// builtinMacros returns the lookup parseEximConfig uses for Exim's built-in
// macros. The binary is only run the first time a config conditional tests
// one, so a config without such conditionals never runs it.
func (e *mqlExim) builtinMacros() eximBuiltinLookup {
	var macros *eximBuiltinMacros
	var loadErr error
	return func(name string) (bool, error) {
		if macros == nil && loadErr == nil {
			macros, loadErr = e.loadBuiltinMacros()
		}
		if loadErr != nil {
			return false, loadErr
		}
		return macros.lookup(name, e.hasMainOption)
	}
}

// hasMainOption reports whether the Exim binary knows a main option, from
// `exim -bP <option>`, which any user may run.
func (e *mqlExim) hasMainOption(option string) (bool, error) {
	stdout, exit, err := e.runExim("-bP " + option)
	if err != nil {
		return false, err
	}
	if exit == 127 {
		return false, errors.New("exim: the config tests Exim's built-in macros, but no exim binary was found to read them from")
	}
	return parseEximOptionProbe(option, stdout)
}

// parseEximOptionProbe reads `exim -bP <option>` output. Exim prints
// `<option> = <value>` for a known option, `<option>` or `no_<option>` for
// a boolean, and `<option> is not a known option` otherwise (on stdout, and
// before Exim 4.9x with exit code 0, so the exit code can't tell).
func parseEximOptionProbe(option, out string) (bool, error) {
	line, _, _ := strings.Cut(strings.TrimSpace(out), "\n")
	line = strings.TrimSpace(line)
	if line == option+" is not a known option" {
		return false, nil
	}
	name, _, _ := strings.Cut(line, "=")
	name = strings.TrimSpace(name)
	if name == option || name == "no_"+option {
		return true, nil
	}
	return false, fmt.Errorf("exim: unexpected output from `exim -bP %s`: %q", option, line)
}

// eximMainOptionMacro returns the main option a `_OPT_MAIN_<NAME>` macro
// stands for. Exim defines one for every main option it knows.
func eximMainOptionMacro(name string) (string, bool) {
	rest, ok := strings.CutPrefix(name, "_OPT_MAIN_")
	if !ok || rest == "" {
		return "", false
	}
	for i := 0; i < len(rest); i++ {
		c := rest[i]
		if c != '_' && (c < 'A' || c > 'Z') && (c < '0' || c > '9') {
			return "", false
		}
	}
	return strings.ToLower(rest), true
}

// loadBuiltinMacros reads the built-in macro set from `exim -bP macros`,
// which Exim only answers for an admin user. Otherwise it derives the
// feature macros from the `Support for:` line of `exim -bV`, which any user
// may run.
func (e *mqlExim) loadBuiltinMacros() (*eximBuiltinMacros, error) {
	stdout, exit, err := e.runExim("-bP macros")
	if err != nil {
		return nil, err
	}
	if exit == 0 {
		if m := parseEximMacrosOutput(stdout); m != nil {
			return m, nil
		}
	}

	stdout, exit, err = e.runExim("-bV")
	if err != nil {
		return nil, err
	}
	if exit == 127 {
		return nil, errors.New("exim: the config tests Exim's built-in macros, but no exim binary was found to read them from")
	}
	if exit != 0 {
		return nil, fmt.Errorf("exim: the config tests Exim's built-in macros, but `exim -bV` exited with %d", exit)
	}
	m := parseEximVersionOutput(stdout)
	if m == nil {
		return nil, errors.New("exim: the config tests Exim's built-in macros, but `exim -bV` printed no `Support for:` line")
	}
	return m, nil
}

// localInterfaces returns the interfaces Exim listens on. It starts from
// the config: on Debian the generated config Exim loads, where
// exim4.conf.localmacros can override dc_local_interfaces. When the config
// is the one the installed Exim uses, a daemon started with `-oX` listens
// on the interfaces given there instead. The running daemons' command lines
// answer that, otherwise on Debian the options in /etc/default/exim4.
func (e *mqlExim) localInterfaces() ([]any, error) {
	params := e.GetParams()
	if params.Error != nil {
		return nil, params.Error
	}
	if len(params.Data) == 0 {
		return []any{}, nil
	}
	configPath := e.GetConfigPath()
	if configPath.Error != nil {
		return nil, configPath.Error
	}

	configured := eximLocalInterfaces(params.Data)
	if configPath.Data == debianEximConfig {
		content, err := e.readFile(debianEximGeneratedConfig)
		if err != nil {
			return nil, err
		}
		if content != "" {
			generated, err := parseEximConfigFile(debianEximGeneratedConfig, content, e.builtinMacros(), e.readInclude)
			if err != nil {
				return nil, err
			}
			configured = eximLocalInterfaces(generated)
		}
	}

	detected, err := e.detectConfigPath()
	if err != nil {
		return nil, err
	}
	if detected != configPath.Data {
		// a file other than the installed Exim's config
		return configured, nil
	}

	daemons := e.runningDaemons()
	if len(daemons) == 0 && e.isDebian() {
		args, err := e.debianDaemonArgs()
		if err != nil {
			return nil, err
		}
		if args != nil {
			daemons = [][]string{args}
		}
	}
	return eximListenInterfaces(configured, daemons), nil
}

// runningDaemons returns the arguments of every running Exim daemon. Not
// being able to list processes (an image scan) means no daemon.
func (e *mqlExim) runningDaemons() [][]string {
	raw, err := CreateResource(e.MqlRuntime, "processes", map[string]*llx.RawData{})
	if err != nil {
		log.Debug().Err(err).Msg("exim> could not list processes")
		return nil
	}
	list := raw.(*mqlProcesses).GetList()
	if list.Error != nil {
		log.Debug().Err(list.Error).Msg("exim> could not list processes")
		return nil
	}

	conn := e.MqlRuntime.Connection.(shared.Connection)
	afs := &afero.Afero{Fs: conn.FileSystem()}
	var res [][]string
	for i := range list.Data {
		proc, ok := list.Data[i].(*mqlProcess)
		if !ok {
			continue
		}
		cmd := proc.GetCommand()
		if cmd.Error != nil {
			continue
		}
		argv := strings.Fields(cmd.Data)
		if len(argv) == 0 || !strings.HasPrefix(path.Base(argv[0]), "exim") {
			continue
		}
		// the exact argument boundaries, where /proc is readable
		if pid := proc.GetPid(); pid.Error == nil {
			if data, err := afs.ReadFile(path.Join("/proc", strconv.FormatInt(pid.Data, 10), "cmdline")); err == nil {
				if exact := haproxy.SplitProcCmdline(data); len(exact) > 0 {
					argv = exact
				}
			}
		}
		if isEximDaemon(argv) {
			res = append(res, argv[1:])
		}
	}
	return res
}

// debianDaemonArgs returns the daemon options the Debian service passes
// from /etc/default/exim4, or nil when the file doesn't exist.
func (e *mqlExim) debianDaemonArgs() ([]string, error) {
	content, err := e.readFile(debianEximDefaults)
	if err != nil || content == "" {
		return nil, err
	}
	systemdUnit := false
	for _, dir := range eximUnitDirs {
		unit, err := e.readFile(filepath.Join(dir, "exim4.service"))
		if err != nil {
			return nil, err
		}
		if unit != "" {
			systemdUnit = strings.Contains(unit, "EXIMSERVICE")
			break
		}
	}
	return eximDefaultsDaemonArgs(content, systemdUnit), nil
}

// eximDefaultsDaemonArgs returns the options /etc/default/exim4 adds to the
// listening daemon's command line. Debian's systemd unit (Debian 13) runs
// `exim4 $EXIMSERVICE`; the init script runs `exim4 -bd ... $COMMONOPTIONS
// ... $SMTPLISTENEROPTIONS`. Both expand the variables unquoted, so the
// values split on whitespace.
func eximDefaultsDaemonArgs(content string, systemdUnit bool) []string {
	env := haproxy.ParseEnvironmentFile(content)
	if systemdUnit {
		return strings.Fields(env["EXIMSERVICE"])
	}
	return strings.Fields(env["COMMONOPTIONS"] + " " + env["SMTPLISTENEROPTIONS"])
}

// isEximDaemon reports whether argv runs an Exim listening daemon.
func isEximDaemon(argv []string) bool {
	if len(argv) < 2 || !strings.HasPrefix(path.Base(argv[0]), "exim") {
		return false
	}
	for _, arg := range argv[1:] {
		if arg == "-bd" || arg == "-bdf" {
			return true
		}
	}
	return false
}

// eximOverrideInterfaces returns the interfaces a daemon's `-oX` option
// sets, or nil when it sets none. Like Exim's daemon, an item of the `-oX`
// list that contains a dot or colon is an interface (optionally with a
// `.port` suffix) and the others are ports; only interfaces replace
// local_interfaces. The last `-oX` wins.
func eximOverrideInterfaces(args []string) []any {
	value, found := "", false
	for i := 0; i+1 < len(args); i++ {
		if args[i] == "-oX" {
			value, found = args[i+1], true
			i++
		}
	}
	if !found {
		return nil
	}
	var res []any
	for _, item := range parseEximListValue(value) {
		if s := item.(string); strings.ContainsAny(s, ".:") {
			res = append(res, s)
		}
	}
	return res
}

// eximListenInterfaces combines the configured interfaces with the running
// daemons' `-oX` overrides: every daemon listens on its override or, without
// one, on the configured interfaces.
func eximListenInterfaces(configured []any, daemons [][]string) []any {
	if len(daemons) == 0 {
		return configured
	}
	res := []any{}
	seen := map[string]struct{}{}
	add := func(list []any) {
		for _, v := range list {
			s := v.(string)
			if _, ok := seen[s]; ok {
				continue
			}
			seen[s] = struct{}{}
			res = append(res, s)
		}
	}
	for _, args := range daemons {
		if override := eximOverrideInterfaces(args); override != nil {
			add(override)
		} else {
			add(configured)
		}
	}
	return res
}

// eximLocalInterfaces returns the interfaces Exim listens on for the parsed
// config. An unset or empty setting means all interfaces, matching Exim's
// own default; only a missing config (no params at all) yields an empty list.
func eximLocalInterfaces(params map[string]any) []any {
	if len(params) == 0 {
		return []any{}
	}

	// Debian split config: dc_local_interfaces is a ' ; '-separated string.
	// update-exim4.conf only emits MAIN_LOCAL_INTERFACES (and with it
	// local_interfaces) when the value is non-empty.
	if v, ok := params["dc_local_interfaces"].(string); ok {
		if res := splitEximList(v, ";"); len(res) > 0 {
			return res
		}
		return eximDefaultInterfaceList()
	}
	// monolithic exim.conf: local_interfaces is an Exim list (default ':'
	// separator, overridable with a leading '<sep')
	if v, ok := params["local_interfaces"].(string); ok {
		if res := parseEximListValue(v); len(res) > 0 {
			return res
		}
	}
	return eximDefaultInterfaceList()
}

func eximDefaultInterfaceList() []any {
	res := make([]any, len(eximDefaultLocalInterfaces))
	for i, v := range eximDefaultLocalInterfaces {
		res[i] = v
	}
	return res
}

// readFile reads a config file from the target's filesystem. A missing file
// yields empty content rather than an error, so an MTA that isn't installed
// resolves cleanly.
func (e *mqlExim) readFile(path string) (string, error) {
	conn := e.MqlRuntime.Connection.(shared.Connection)
	f, err := conn.FileSystem().Open(path)
	if err != nil {
		// the connection's virtual filesystem may not return *os.PathError,
		// so match the wrapped sentinel rather than using os.IsNotExist
		if errors.Is(err, fs.ErrNotExist) {
			return "", nil
		}
		return "", err
	}
	defer f.Close()

	data, err := io.ReadAll(f)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// readInclude reads a file named by .include or .include_if_exists. exists
// is false when the file is not there; a file that is there but cannot be
// read is an error.
func (e *mqlExim) readInclude(path string) (string, bool, error) {
	conn := e.MqlRuntime.Connection.(shared.Connection)
	if _, err := conn.FileSystem().Stat(path); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return "", false, nil
		}
		return "", false, err
	}
	f, err := conn.FileSystem().Open(path)
	if err != nil {
		return "", false, err
	}
	defer f.Close()
	data, err := io.ReadAll(f)
	if err != nil {
		return "", false, err
	}
	return string(data), true, nil
}

// eximIncludeReader reads a file named by .include or .include_if_exists.
// exists is false for a file that is not there.
type eximIncludeReader func(path string) (content string, exists bool, err error)

// eximMaxIncludeDepth bounds .include nesting so a file that includes itself
// fails instead of recursing forever (Exim itself runs out of file handles).
const eximMaxIncludeDepth = 32

// parseEximConfig parses content on its own, without following .include.
func parseEximConfig(content string, builtins eximBuiltinLookup) (map[string]any, error) {
	return parseEximConfigFile("", content, builtins, nil)
}

// parseEximConfigFile parses the macros and main-section options of an Exim config.
// It handles both the Debian `KEY='value'` form and the monolithic `key = value`
// form, folds backslash continuations, strips comments, and stops at the first
// `begin <section>` block (routers, transports, acl, …) so only the main
// section and macros are returned. Like Exim's own preprocessor it evaluates
// `.ifdef`/`.ifndef`/`.elifdef`/`.elifndef`/`.else`/`.endif` against the macros
// defined so far and substitutes macro references in values, so
// `local_interfaces = MAIN_LOCAL_INTERFACES` reports the macro's value. Keys
// that are not simple assignments (named lists like `domainlist x = …`, ACL
// conditions) are skipped.
//
// Conditionals on Exim's built-in macros (`.ifdef _HAVE_OPENSSL`) are
// answered by builtins. It is only called for a conditional whose branch
// matters, and its error fails the parse rather than guessing a branch.
//
// `.include` and `.include_if_exists` lines in an active branch are read
// through include and parsed in place, the way Exim's readconf does: macros
// and conditionals carry across files, a relative .include resolves against
// the including file's directory, .include_if_exists needs an absolute path
// and skips a missing file, and a missing .include file is an error (Exim
// refuses to start). path is the file content came from. With a nil include
// the directives are ignored.
func parseEximConfigFile(path, content string, builtins eximBuiltinLookup, include eximIncludeReader) (map[string]any, error) {
	params := map[string]any{}
	macros := map[string]string{}
	cond := eximConditionals{}

	type eximFile struct {
		lines []string
		next  int
		dir   string
	}
	stack := []*eximFile{{lines: joinEximContinuations(content), dir: filepath.Dir(path)}}

lines:
	for len(stack) > 0 {
		file := stack[len(stack)-1]
		if file.next >= len(file.lines) {
			stack = stack[:len(stack)-1]
			continue
		}
		line := file.lines[file.next]
		file.next++

		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		if strings.HasPrefix(trimmed, ".") {
			directive, arg, _ := strings.Cut(strings.Replace(trimmed, "\t", " ", 1), " ")
			name := strings.TrimSpace(arg)
			if directive == ".include" || directive == ".include_if_exists" {
				if !cond.active() || include == nil {
					continue
				}
				target := strings.TrimSpace(substituteEximMacros(name, macros))
				if len(target) >= 2 && target[0] == '"' && target[len(target)-1] == '"' {
					target = target[1 : len(target)-1]
				}
				if !filepath.IsAbs(target) {
					if directive == ".include_if_exists" {
						return nil, fmt.Errorf("exim: .include_if_exists specifies a non-absolute path %q", target)
					}
					target = filepath.Join(file.dir, target)
				}
				if len(stack) > eximMaxIncludeDepth {
					return nil, fmt.Errorf("exim: .include nested too deeply at %s", target)
				}
				included, exists, err := include(target)
				if err != nil {
					return nil, err
				}
				if !exists {
					if directive == ".include_if_exists" {
						continue
					}
					return nil, fmt.Errorf("exim: failed to open included configuration file %s", target)
				}
				stack = append(stack, &eximFile{lines: joinEximContinuations(included), dir: filepath.Dir(target)})
				continue
			}
			err := cond.apply(directive, func() (bool, error) {
				if strings.HasPrefix(name, "_") {
					if builtins == nil {
						return false, fmt.Errorf("exim: cannot evaluate %s %s without Exim's built-in macros", directive, name)
					}
					return builtins(name)
				}
				_, ok := macros[name]
				return ok, nil
			})
			if err != nil {
				return nil, err
			}
			continue
		}
		if !cond.active() {
			continue
		}

		// the main section ends at the first `begin <section>` directive
		if trimmed == "begin" || strings.HasPrefix(trimmed, "begin ") {
			break lines
		}

		idx := strings.Index(trimmed, "=")
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(trimmed[:idx])
		key = strings.TrimSpace(strings.TrimPrefix(key, "hide ")) // `hide key = value`
		// a simple option or macro has a single-token name; skip named lists
		// (`domainlist x = …`) and other multi-token left-hand sides
		if key == "" || strings.ContainsAny(key, " \t") {
			continue
		}
		value := trimmed[idx+1:]

		if isEximMacroName(key) {
			// `NAME == value` redefines an existing macro
			value = strings.TrimPrefix(value, "=")
			value = substituteEximMacros(strings.TrimSpace(value), macros)
			macros[key] = value
			params[key] = unquoteEximValue(value)
			continue
		}

		value = substituteEximMacros(strings.TrimSpace(value), macros)
		params[key] = unquoteEximValue(value)
	}
	return params, nil
}

// eximConditionals tracks nested .ifdef/.ifndef blocks.
type eximConditionals struct {
	// one entry per open block: whether the current branch is taken, and
	// whether any branch of the block has been taken yet
	taken []bool
	done  []bool
}

func (c *eximConditionals) active() bool {
	for _, t := range c.taken {
		if !t {
			return false
		}
	}
	return true
}

// parentsActive reports whether every enclosing block of the innermost one
// takes its current branch.
func (c *eximConditionals) parentsActive() bool {
	for _, t := range c.taken[:len(c.taken)-1] {
		if !t {
			return false
		}
	}
	return true
}

// apply evaluates a conditional directive. defined is only called when the
// answer decides which lines are read; inside a skipped branch it is not.
func (c *eximConditionals) apply(directive string, defined func() (bool, error)) error {
	switch directive {
	case ".ifdef", ".ifndef":
		ok := false
		if c.active() {
			d, err := defined()
			if err != nil {
				return err
			}
			ok = d == (directive == ".ifdef")
		}
		c.taken = append(c.taken, ok)
		c.done = append(c.done, ok)
	case ".elifdef", ".elifndef":
		if n := len(c.taken); n > 0 {
			ok := false
			if !c.done[n-1] && c.parentsActive() {
				d, err := defined()
				if err != nil {
					return err
				}
				ok = d == (directive == ".elifdef")
			}
			c.taken[n-1] = ok
			c.done[n-1] = c.done[n-1] || ok
		}
	case ".else":
		if n := len(c.taken); n > 0 {
			c.taken[n-1] = !c.done[n-1]
			c.done[n-1] = true
		}
	case ".endif":
		if n := len(c.taken); n > 0 {
			c.taken = c.taken[:n-1]
			c.done = c.done[:n-1]
		}
	}
	return nil
}

// isEximMacroName reports whether name is a macro name: it starts with an
// upper-case letter and continues with letters, digits and underscores.
func isEximMacroName(name string) bool {
	if name == "" || name[0] < 'A' || name[0] > 'Z' {
		return false
	}
	for i := 1; i < len(name); i++ {
		if !isEximMacroChar(name[i]) {
			return false
		}
	}
	return true
}

func isEximMacroChar(c byte) bool {
	return c == '_' || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')
}

// substituteEximMacros replaces whole-word references to defined macros in
// value. Exim matches macro names as substrings; whole words avoid rewriting
// a longer name that merely contains a shorter macro's name.
func substituteEximMacros(value string, macros map[string]string) string {
	if len(macros) == 0 {
		return value
	}
	var out strings.Builder
	for i := 0; i < len(value); {
		if value[i] >= 'A' && value[i] <= 'Z' && (i == 0 || !isEximMacroChar(value[i-1])) {
			j := i + 1
			for j < len(value) && isEximMacroChar(value[j]) {
				j++
			}
			if repl, ok := macros[value[i:j]]; ok {
				out.WriteString(repl)
				i = j
				continue
			}
			out.WriteString(value[i:j])
			i = j
			continue
		}
		out.WriteByte(value[i])
		i++
	}
	return out.String()
}

// joinEximContinuations joins lines ending in a backslash with the following
// line, matching Exim's line-continuation rule.
func joinEximContinuations(content string) []string {
	var logical []string
	var buf strings.Builder
	continuing := false

	for _, raw := range strings.Split(content, "\n") {
		line := strings.TrimRight(raw, "\r")
		if continuing {
			buf.WriteString(strings.TrimLeft(line, " \t"))
		} else {
			buf.Reset()
			buf.WriteString(line)
		}

		if strings.HasSuffix(strings.TrimRight(line, " \t"), "\\") {
			s := strings.TrimSuffix(strings.TrimRight(buf.String(), " \t"), "\\")
			buf.Reset()
			buf.WriteString(s)
			continuing = true
			continue
		}

		logical = append(logical, buf.String())
		continuing = false
	}
	if continuing {
		logical = append(logical, buf.String())
	}
	return logical
}

// unquoteEximValue strips a matching pair of surrounding single or double
// quotes (the Debian split config quotes its values).
func unquoteEximValue(value string) string {
	if len(value) >= 2 {
		first, last := value[0], value[len(value)-1]
		if (first == '\'' && last == '\'') || (first == '"' && last == '"') {
			return value[1 : len(value)-1]
		}
	}
	return value
}

// parseEximListValue parses an Exim list, honoring the optional `<sep` prefix
// that selects a non-default separator (needed for IPv6 addresses, which
// otherwise collide with the default ':' separator).
func parseEximListValue(value string) []any {
	value = strings.TrimSpace(value)
	sep := ":"
	if strings.HasPrefix(value, "<") && len(value) >= 2 {
		sep = string(value[1])
		value = strings.TrimSpace(value[2:])
	}
	return splitEximList(value, sep)
}

// splitEximList splits an Exim list on sep, trims each item and drops empty
// ones. A doubled separator is a literal separator character inside an item,
// so the ':'-separated `127.0.0.1 : ::::1` holds 127.0.0.1 and ::1.
func splitEximList(value, sep string) []any {
	res := []any{}
	if sep == "" {
		return res
	}
	var item strings.Builder
	flush := func() {
		if tok := strings.TrimSpace(item.String()); tok != "" {
			res = append(res, tok)
		}
		item.Reset()
	}
	for i := 0; i < len(value); {
		if strings.HasPrefix(value[i:], sep) {
			if strings.HasPrefix(value[i+len(sep):], sep) {
				item.WriteString(sep)
				i += 2 * len(sep)
				continue
			}
			flush()
			i += len(sep)
			continue
		}
		item.WriteByte(value[i])
		i++
	}
	flush()
	return res
}

// eximBuiltinLookup reports whether a built-in macro (a name starting with
// an underscore, such as _HAVE_OPENSSL) is defined by the Exim binary.
type eximBuiltinLookup func(name string) (bool, error)

// eximBuiltinMacros is the built-in macro set of an Exim binary.
type eximBuiltinMacros struct {
	names map[string]struct{}
	// known limits the names the set can answer for; nil means every name.
	// The `exim -bV` feature list only covers the feature macros.
	known map[string]struct{}
}

// lookup answers a built-in macro from the set. A `_OPT_MAIN_*` macro the
// set can't answer (it came from `exim -bV`) is answered by probe, which
// tells whether the binary knows that main option.
func (m *eximBuiltinMacros) lookup(name string, probe func(option string) (bool, error)) (bool, error) {
	if option, ok := eximMainOptionMacro(name); ok && m.known != nil {
		if _, known := m.known[name]; !known {
			return probe(option)
		}
	}
	return m.defined(name)
}

func (m *eximBuiltinMacros) defined(name string) (bool, error) {
	if m.known != nil {
		if _, ok := m.known[name]; !ok {
			return false, fmt.Errorf("exim: cannot tell whether the built-in macro %s is defined: `exim -bP macros` needs an Exim admin user, and `exim -bV` does not report it", name)
		}
	}
	_, ok := m.names[name]
	return ok, nil
}

// parseEximMacrosOutput reads the built-in macros from `exim -bP macros`
// output, one `NAME=value` per line. Macros defined in the config are
// listed too and are skipped, since the config parser defines its own. It
// returns nil when the output holds no built-in macro.
func parseEximMacrosOutput(out string) *eximBuiltinMacros {
	names := map[string]struct{}{}
	for _, line := range strings.Split(out, "\n") {
		name, _, _ := strings.Cut(strings.TrimSpace(line), "=")
		name = strings.TrimSpace(name)
		if len(name) > 1 && name[0] == '_' && isEximMacroName("A"+name[1:]) {
			names[name] = struct{}{}
		}
	}
	if len(names) == 0 {
		return nil
	}
	return &eximBuiltinMacros{names: names}
}

// eximFeatureMacros maps each `Support for:` entry of `exim -bV` to the
// feature macros Exim defines for it, taken from show_whats_supported() in
// exim.c and features() in macro_predef.c of Exim 4.92 to 4.99. An entry
// mapping to no macro still counts: Exim 4.96 and 4.97 print
// Experimental_ESMTP_Limits but define no _HAVE_ESMTP_LIMITS.
var eximFeatureMacros = map[string][]string{
	"Content_Scanning":          {"_HAVE_CONTENT_SCANNING"},
	"crypteq":                   {"_HAVE_CRYPTEQ"},
	"Expand_dlfunc":             {"_HAVE_DLFUNC"},
	"iconv()":                   {"_HAVE_ICONV"},
	"IPv6":                      {"_HAVE_IPV6"},
	"PAM":                       {"_HAVE_PAM"},
	"Perl":                      {"_HAVE_PERL"},
	"GnuTLS":                    {"_HAVE_TLS", "_HAVE_GNUTLS"},
	"OpenSSL":                   {"_HAVE_TLS", "_HAVE_OPENSSL"},
	"move_frozen_messages":      {"_HAVE_MOVE_FROZEN_MESSAGES"},
	"radius":                    {"_HAVE_RADIUS"},
	"TLS_resume":                {"_HAVE_TLS_RESUME"},
	"Experimental_TLS_resume":   {"_HAVE_TLS_RESUME"},
	"translate_ip_address":      {"_HAVE_TRANSLATE_IP_ADDRESS"},
	"TCPwrappers":               {"_HAVE_TCPWRAPPERS"},
	"use_setclassresources":     {"_HAVE_SETCLASSRESOURCES"},
	"DANE":                      {"_HAVE_DANE"},
	"DKIM":                      {"_HAVE_DKIM"},
	"DMARC":                     {"_HAVE_DMARC"},
	"Experimental_DMARC":        {"_HAVE_DMARC"},
	"DNSSEC":                    {"_HAVE_DNSSEC"},
	"DSCP":                      {"_HAVE_DSCP"},
	"ESMTP_Limits":              {"_HAVE_ESMTP_LIMITS"},
	"Experimental_ESMTP_Limits": {},
	"ESMTP_Wellknown":           {"_HAVE_WELLKNOWN"},
	"Event":                     {"_HAVE_EVENT"},
	"I18N":                      {"_HAVE_I18N"},
	"OCSP":                      {"_HAVE_OCSP"},
	"PIPECONNECT":               {"_HAVE_PIPE_CONNECT"},
	"PIPE_CONNECT":              {"_HAVE_PIPE_CONNECT"},
	"Experimental_PIPE_CONNECT": {"_HAVE_PIPE_CONNECT"},
	"PRDR":                      {"_HAVE_PRDR"},
	"PROXY":                     {"_HAVE_PROXY"},
	"SOCKS":                     {"_HAVE_SOCKS"},
	"SPF":                       {"_HAVE_SPF"},
	"SRS":                       {"_HAVE_SRS", "_HAVE_NATIVE_SRS"},
	"TCP_Fast_Open":             {"_HAVE_TCP_FASTOPEN"},
	"Experimental_ARC":          {"_HAVE_ARC"},
	"Experimental_Brightmail":   {"_HAVE_BRIGHTMAIL"},
	"Experimental_DCC":          {"_HAVE_DCC"},
	"Experimental_DSN_info":     {"_HAVE_DSN_INFO"},
	"Experimental_REQUIRETLS":   {"_HAVE_REQTLS"},
	"Experimental_XCLIENT":      {"_HAVE_XCLIENT"},
	// Exim 4.94 prints this for both the external and the native SRS
	// support, and only the native one defines _HAVE_NATIVE_SRS
	"Experimental_SRS": {"_HAVE_SRS"},
}

// parseEximVersionOutput derives the feature macros from the `Support for:`
// line of `exim -bV`. Only the feature macros can be answered this way; the
// set is limited to them so a test of any other built-in macro is reported
// as unknown rather than as undefined. It returns nil when the output has no
// `Support for:` line.
func parseEximVersionOutput(out string) *eximBuiltinMacros {
	for _, line := range strings.Split(out, "\n") {
		features, ok := strings.CutPrefix(strings.TrimSpace(line), "Support for:")
		if !ok {
			continue
		}
		m := &eximBuiltinMacros{names: map[string]struct{}{}, known: map[string]struct{}{}}
		for _, macros := range eximFeatureMacros {
			for _, name := range macros {
				m.known[name] = struct{}{}
			}
		}
		for _, feature := range strings.Fields(features) {
			for _, name := range eximFeatureMacros[feature] {
				m.names[name] = struct{}{}
			}
			if feature == "Experimental_SRS" {
				delete(m.known, "_HAVE_NATIVE_SRS")
			}
		}
		return m
	}
	return nil
}
