// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

package resources

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.mondoo.com/mql/llx"
	"go.mondoo.com/mql/providers-sdk/v1/inventory"
	"go.mondoo.com/mql/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/providers/os/connection/mock"
	"go.mondoo.com/mql/utils/syncx"
)

func pgAutoConfRuntime(t *testing.T, files map[string]string) *plugin.Runtime {
	t.Helper()
	data := &mock.TomlData{Files: map[string]*mock.MockFileData{}}
	for p, c := range files {
		data.Files[p] = &mock.MockFileData{Path: p, Content: c, StatData: mock.FileInfo{Mode: 0o644}}
	}
	conn, err := mock.New(0, &inventory.Asset{Platform: &inventory.Platform{Name: "ubuntu", Family: []string{"debian", "linux"}}}, mock.WithData(data))
	require.NoError(t, err)
	return &plugin.Runtime{Connection: conn, Resources: &syncx.Map[plugin.Resource]{}}
}

// Ubuntu 24.04, PostgreSQL 18: ALTER SYSTEM SET ssl = off and
// password_encryption = md5, then pg_reload_conf(). The server runs with ssl
// off and md5 (pg_settings source "configuration file",
// sourcefile postgresql.auto.conf), while postgresql.conf still says ssl = on.
func TestPostgresqlConfAppliesAutoConf(t *testing.T) {
	runtime := pgAutoConfRuntime(t, map[string]string{
		"/etc/postgresql/18/main/postgresql.conf":          "data_directory = '/var/lib/postgresql/18/main'\nssl = on\npassword_encryption = scram-sha-256\nport = 5443\n",
		"/var/lib/postgresql/18/main/postgresql.auto.conf": "# Do not edit this file manually!\n# It will be overwritten by the ALTER SYSTEM command.\nssl = 'off'\npassword_encryption = 'md5'\n",
	})
	raw, err := NewResource(runtime, "postgresql.conf", map[string]*llx.RawData{"path": llx.StringData("/etc/postgresql/18/main/postgresql.conf")})
	require.NoError(t, err)
	conf := raw.(*mqlPostgresqlConf)

	ssl := conf.GetSslEnabled()
	require.NoError(t, ssl.Error)
	assert.False(t, ssl.Data, "ALTER SYSTEM SET ssl = off wins over postgresql.conf")
	assert.Equal(t, "md5", conf.GetPasswordEncryption().Data)
	assert.Equal(t, int64(5443), conf.GetPort().Data, "settings auto.conf does not set stay")

	files := conf.GetFiles()
	require.NoError(t, files.Error)
	var paths []string
	for _, f := range files.Data {
		paths = append(paths, f.(*mqlFile).Path.Data)
	}
	assert.Equal(t, []string{"/etc/postgresql/18/main/postgresql.conf", "/var/lib/postgresql/18/main/postgresql.auto.conf"}, paths)
}

// RHEL keeps postgresql.conf in the data directory and sets no
// data_directory, so postgresql.auto.conf sits next to it.
func TestPostgresqlConfAutoConfNextToConfWithoutDataDirectory(t *testing.T) {
	runtime := pgAutoConfRuntime(t, map[string]string{
		"/var/lib/pgsql/data/postgresql.conf":      "ssl = on\n",
		"/var/lib/pgsql/data/postgresql.auto.conf": "ssl = 'off'\n",
	})
	raw, err := NewResource(runtime, "postgresql.conf", map[string]*llx.RawData{"path": llx.StringData("/var/lib/pgsql/data/postgresql.conf")})
	require.NoError(t, err)
	assert.False(t, raw.(*mqlPostgresqlConf).GetSslEnabled().Data)
}

// No ALTER SYSTEM ever ran: there is no postgresql.auto.conf, and nothing
// changes.
func TestPostgresqlConfWithoutAutoConf(t *testing.T) {
	runtime := pgAutoConfRuntime(t, map[string]string{
		"/var/lib/pgsql/data/postgresql.conf": "ssl = on\n",
	})
	raw, err := NewResource(runtime, "postgresql.conf", map[string]*llx.RawData{"path": llx.StringData("/var/lib/pgsql/data/postgresql.conf")})
	require.NoError(t, err)
	conf := raw.(*mqlPostgresqlConf)
	ssl := conf.GetSslEnabled()
	require.NoError(t, ssl.Error)
	assert.True(t, ssl.Data)
	assert.Len(t, conf.GetFiles().Data, 1)
}
