// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by resources. DO NOT EDIT.

package resources

import (
	"errors"

	"go.mondoo.com/mql/llx"
	"go.mondoo.com/mql/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/types"
)

// The MQL type names exposed as public consts for ease of reference.
const (
	ResourceIac          string = "iac"
	ResourceIacSource    string = "iac.source"
	ResourceIacDetection string = "iac.detection"
)

var resourceFactories map[string]plugin.ResourceFactory

func init() {
	resourceFactories = map[string]plugin.ResourceFactory{
		"iac": {
			// to override args, implement: initIac(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createIac,
		},
		"iac.source": {
			// to override args, implement: initIacSource(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createIacSource,
		},
		"iac.detection": {
			// to override args, implement: initIacDetection(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createIacDetection,
		},
	}
}

// NewResource is used by the runtime of this plugin to create new resources.
// Its arguments may be provided by users. This function is generally not
// used by initializing resources from recordings or from lists.
func NewResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	if f.Init != nil {
		cargs, res, err := f.Init(runtime, args)
		if err != nil {
			return res, err
		}

		if res != nil {
			mqlId := res.MqlID()
			id := name + "\x00" + mqlId
			if x, ok := runtime.Resources.Get(id); ok {
				return x, nil
			}
			runtime.Resources.Set(id, res)
			return res, nil
		}

		args = cargs
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

// CreateResource is used by the runtime of this plugin to create resources.
// Its arguments must be complete and pre-processed. This method is used
// for initializing resources from recordings or from lists.
func CreateResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

var getDataFields = map[string]func(r plugin.Resource) *plugin.DataRes{
	"iac.source": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlIac).GetSource()).ToDataRes(types.Resource("iac.source"))
	},
	"iac.detections": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlIac).GetDetections()).ToDataRes(types.Array(types.Resource("iac.detection")))
	},
	"iac.source.kind": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlIacSource).GetKind()).ToDataRes(types.String)
	},
	"iac.source.origin": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlIacSource).GetOrigin()).ToDataRes(types.String)
	},
	"iac.source.ref": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlIacSource).GetRef()).ToDataRes(types.String)
	},
	"iac.detection.tool": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlIacDetection).GetTool()).ToDataRes(types.String)
	},
	"iac.detection.path": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlIacDetection).GetPath()).ToDataRes(types.String)
	},
	"iac.detection.files": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlIacDetection).GetFiles()).ToDataRes(types.Array(types.String))
	},
	"iac.detection.asset": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlIacDetection).GetAsset()).ToDataRes(types.Asset(""))
	},
	"iac.detection.error": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlIacDetection).GetError()).ToDataRes(types.String)
	},
}

func GetData(resource plugin.Resource, field string, args map[string]*llx.RawData) *plugin.DataRes {
	f, ok := getDataFields[resource.MqlName()+"."+field]
	if !ok {
		return &plugin.DataRes{Error: "cannot find '" + field + "' in resource '" + resource.MqlName() + "'"}
	}

	return f(resource)
}

var setDataFields = map[string]func(r plugin.Resource, v *llx.RawData) bool{
	"iac.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIac).__id, ok = v.Value.(string)
		return
	},
	"iac.source": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIac).Source, ok = plugin.RawToTValue[*mqlIacSource](v.Value, v.Error)
		return
	},
	"iac.detections": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIac).Detections, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"iac.source.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIacSource).__id, ok = v.Value.(string)
		return
	},
	"iac.source.kind": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIacSource).Kind, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"iac.source.origin": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIacSource).Origin, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"iac.source.ref": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIacSource).Ref, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"iac.detection.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIacDetection).__id, ok = v.Value.(string)
		return
	},
	"iac.detection.tool": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIacDetection).Tool, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"iac.detection.path": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIacDetection).Path, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"iac.detection.files": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIacDetection).Files, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"iac.detection.asset": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIacDetection).Asset, ok = plugin.RawToTValue[*llx.AssetValue](v.Value, v.Error)
		return
	},
	"iac.detection.error": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlIacDetection).Error, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
}

func SetData(resource plugin.Resource, field string, val *llx.RawData) error {
	f, ok := setDataFields[resource.MqlName()+"."+field]
	if !ok {
		return errors.New("[iac] cannot set '" + field + "' in resource '" + resource.MqlName() + "', field not found")
	}

	if ok := f(resource, val); !ok {
		return errors.New("[iac] cannot set '" + field + "' in resource '" + resource.MqlName() + "', type does not match")
	}
	return nil
}

func SetAllData(resource plugin.Resource, args map[string]*llx.RawData) error {
	var err error
	for k, v := range args {
		if err = SetData(resource, k, v); err != nil {
			return err
		}
	}
	return nil
}

// mqlIac for the iac resource
type mqlIac struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlIacInternal it will be used here
	Source     plugin.TValue[*mqlIacSource]
	Detections plugin.TValue[[]any]
}

// createIac creates a new instance of this resource
func createIac(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlIac{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("iac", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlIac) MqlName() string {
	return "iac"
}

func (c *mqlIac) MqlID() string {
	return c.__id
}

func (c *mqlIac) GetSource() *plugin.TValue[*mqlIacSource] {
	return plugin.GetOrCompute[*mqlIacSource](&c.Source, func() (*mqlIacSource, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("iac", c.__id, "source")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlIacSource), nil
			}
		}

		return c.source()
	})
}

func (c *mqlIac) GetDetections() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Detections, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("iac", c.__id, "detections")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.detections()
	})
}

// mqlIacSource for the iac.source resource
type mqlIacSource struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlIacSourceInternal it will be used here
	Kind   plugin.TValue[string]
	Origin plugin.TValue[string]
	Ref    plugin.TValue[string]
}

// createIacSource creates a new instance of this resource
func createIacSource(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlIacSource{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("iac.source", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlIacSource) MqlName() string {
	return "iac.source"
}

func (c *mqlIacSource) MqlID() string {
	return c.__id
}

func (c *mqlIacSource) GetKind() *plugin.TValue[string] {
	return &c.Kind
}

func (c *mqlIacSource) GetOrigin() *plugin.TValue[string] {
	return &c.Origin
}

func (c *mqlIacSource) GetRef() *plugin.TValue[string] {
	return &c.Ref
}

// mqlIacDetection for the iac.detection resource
type mqlIacDetection struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlIacDetectionInternal
	Tool  plugin.TValue[string]
	Path  plugin.TValue[string]
	Files plugin.TValue[[]any]
	Asset plugin.TValue[*llx.AssetValue]
	Error plugin.TValue[string]
}

// createIacDetection creates a new instance of this resource
func createIacDetection(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlIacDetection{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("iac.detection", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlIacDetection) MqlName() string {
	return "iac.detection"
}

func (c *mqlIacDetection) MqlID() string {
	return c.__id
}

func (c *mqlIacDetection) GetTool() *plugin.TValue[string] {
	return &c.Tool
}

func (c *mqlIacDetection) GetPath() *plugin.TValue[string] {
	return &c.Path
}

func (c *mqlIacDetection) GetFiles() *plugin.TValue[[]any] {
	return &c.Files
}

func (c *mqlIacDetection) GetAsset() *plugin.TValue[*llx.AssetValue] {
	return plugin.GetOrCompute[*llx.AssetValue](&c.Asset, func() (*llx.AssetValue, error) {
		return c.asset()
	})
}

func (c *mqlIacDetection) GetError() *plugin.TValue[string] {
	return &c.Error
}
