// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by resources. DO NOT EDIT.

package resources

import (
	"errors"
	"time"

	"go.mondoo.com/mql/llx"
	"go.mondoo.com/mql/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/types"
)

// The MQL type names exposed as public consts for ease of reference.
const (
	ResourceAzuredevops                 string = "azuredevops"
	ResourceAzuredevopsOrganization     string = "azuredevops.organization"
	ResourceAzuredevopsProject          string = "azuredevops.project"
	ResourceAzuredevopsRepository       string = "azuredevops.repository"
	ResourceAzuredevopsBranch           string = "azuredevops.branch"
	ResourceAzuredevopsBranchProtection string = "azuredevops.branchProtection"
	ResourceAzuredevopsPolicy           string = "azuredevops.policy"
)

var resourceFactories map[string]plugin.ResourceFactory

func init() {
	resourceFactories = map[string]plugin.ResourceFactory{
		"azuredevops": {
			// to override args, implement: initAzuredevops(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createAzuredevops,
		},
		"azuredevops.organization": {
			Init:   initAzuredevopsOrganization,
			Create: createAzuredevopsOrganization,
		},
		"azuredevops.project": {
			// to override args, implement: initAzuredevopsProject(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createAzuredevopsProject,
		},
		"azuredevops.repository": {
			Init:   initAzuredevopsRepository,
			Create: createAzuredevopsRepository,
		},
		"azuredevops.branch": {
			// to override args, implement: initAzuredevopsBranch(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createAzuredevopsBranch,
		},
		"azuredevops.branchProtection": {
			// to override args, implement: initAzuredevopsBranchProtection(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createAzuredevopsBranchProtection,
		},
		"azuredevops.policy": {
			// to override args, implement: initAzuredevopsPolicy(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createAzuredevopsPolicy,
		},
	}
}

// NewResource is used by the runtime of this plugin to create new resources.
// Its arguments may be provided by users. This function is generally not
// used by initializing resources from recordings or from lists.
func NewResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	if f.Init != nil {
		cargs, res, err := f.Init(runtime, args)
		if err != nil {
			return res, err
		}

		if res != nil {
			mqlId := res.MqlID()
			id := name + "\x00" + mqlId
			if x, ok := runtime.Resources.Get(id); ok {
				return x, nil
			}
			runtime.Resources.Set(id, res)
			return res, nil
		}

		args = cargs
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

// CreateResource is used by the runtime of this plugin to create resources.
// Its arguments must be complete and pre-processed. This method is used
// for initializing resources from recordings or from lists.
func CreateResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

var getDataFields = map[string]func(r plugin.Resource) *plugin.DataRes{
	"azuredevops.organization.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsOrganization).GetName()).ToDataRes(types.String)
	},
	"azuredevops.organization.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsOrganization).GetId()).ToDataRes(types.String)
	},
	"azuredevops.organization.deploymentType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsOrganization).GetDeploymentType()).ToDataRes(types.String)
	},
	"azuredevops.organization.projects": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsOrganization).GetProjects()).ToDataRes(types.Array(types.Resource("azuredevops.project")))
	},
	"azuredevops.organization.repositories": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsOrganization).GetRepositories()).ToDataRes(types.Array(types.Resource("azuredevops.repository")))
	},
	"azuredevops.organization.unreadableProjects": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsOrganization).GetUnreadableProjects()).ToDataRes(types.Array(types.String))
	},
	"azuredevops.project.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsProject).GetId()).ToDataRes(types.String)
	},
	"azuredevops.project.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsProject).GetName()).ToDataRes(types.String)
	},
	"azuredevops.project.description": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsProject).GetDescription()).ToDataRes(types.String)
	},
	"azuredevops.project.state": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsProject).GetState()).ToDataRes(types.String)
	},
	"azuredevops.project.visibility": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsProject).GetVisibility()).ToDataRes(types.String)
	},
	"azuredevops.project.url": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsProject).GetUrl()).ToDataRes(types.String)
	},
	"azuredevops.project.lastUpdateTime": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsProject).GetLastUpdateTime()).ToDataRes(types.Time)
	},
	"azuredevops.project.repositories": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsProject).GetRepositories()).ToDataRes(types.Array(types.Resource("azuredevops.repository")))
	},
	"azuredevops.repository.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetId()).ToDataRes(types.String)
	},
	"azuredevops.repository.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetName()).ToDataRes(types.String)
	},
	"azuredevops.repository.projectName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetProjectName()).ToDataRes(types.String)
	},
	"azuredevops.repository.projectId": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetProjectId()).ToDataRes(types.String)
	},
	"azuredevops.repository.fullName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetFullName()).ToDataRes(types.String)
	},
	"azuredevops.repository.defaultBranch": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetDefaultBranch()).ToDataRes(types.String)
	},
	"azuredevops.repository.size": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetSize()).ToDataRes(types.Int)
	},
	"azuredevops.repository.isDisabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetIsDisabled()).ToDataRes(types.Bool)
	},
	"azuredevops.repository.isEmpty": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetIsEmpty()).ToDataRes(types.Bool)
	},
	"azuredevops.repository.isFork": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetIsFork()).ToDataRes(types.Bool)
	},
	"azuredevops.repository.status": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetStatus()).ToDataRes(types.String)
	},
	"azuredevops.repository.webUrl": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetWebUrl()).ToDataRes(types.String)
	},
	"azuredevops.repository.sshUrl": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetSshUrl()).ToDataRes(types.String)
	},
	"azuredevops.repository.cloneUrl": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetCloneUrl()).ToDataRes(types.String)
	},
	"azuredevops.repository.project": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetProject()).ToDataRes(types.Resource("azuredevops.project"))
	},
	"azuredevops.repository.branches": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetBranches()).ToDataRes(types.Array(types.Resource("azuredevops.branch")))
	},
	"azuredevops.repository.policies": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsRepository).GetPolicies()).ToDataRes(types.Array(types.Resource("azuredevops.policy")))
	},
	"azuredevops.branch.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranch).GetName()).ToDataRes(types.String)
	},
	"azuredevops.branch.refName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranch).GetRefName()).ToDataRes(types.String)
	},
	"azuredevops.branch.headCommitSha": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranch).GetHeadCommitSha()).ToDataRes(types.String)
	},
	"azuredevops.branch.isDefault": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranch).GetIsDefault()).ToDataRes(types.Bool)
	},
	"azuredevops.branch.isProtected": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranch).GetIsProtected()).ToDataRes(types.Bool)
	},
	"azuredevops.branch.protectionRules": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranch).GetProtectionRules()).ToDataRes(types.Resource("azuredevops.branchProtection"))
	},
	"azuredevops.branchProtection.refName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranchProtection).GetRefName()).ToDataRes(types.String)
	},
	"azuredevops.branchProtection.requiredPullRequestReviewsEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranchProtection).GetRequiredPullRequestReviewsEnabled()).ToDataRes(types.Bool)
	},
	"azuredevops.branchProtection.requiredApprovingReviewCount": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranchProtection).GetRequiredApprovingReviewCount()).ToDataRes(types.Int)
	},
	"azuredevops.branchProtection.requireCodeOwnerReviews": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranchProtection).GetRequireCodeOwnerReviews()).ToDataRes(types.Bool)
	},
	"azuredevops.branchProtection.requiredConversationResolutionEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranchProtection).GetRequiredConversationResolutionEnabled()).ToDataRes(types.Bool)
	},
	"azuredevops.branchProtection.requiredStatusChecksEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranchProtection).GetRequiredStatusChecksEnabled()).ToDataRes(types.Bool)
	},
	"azuredevops.branchProtection.policies": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranchProtection).GetPolicies()).ToDataRes(types.Array(types.Resource("azuredevops.policy")))
	},
	"azuredevops.branchProtection.allowForcePushesEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranchProtection).GetAllowForcePushesEnabled()).ToDataRes(types.Bool)
	},
	"azuredevops.branchProtection.enforceAdminsEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranchProtection).GetEnforceAdminsEnabled()).ToDataRes(types.Bool)
	},
	"azuredevops.branchProtection.blockCreations": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsBranchProtection).GetBlockCreations()).ToDataRes(types.Bool)
	},
	"azuredevops.policy.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsPolicy).GetId()).ToDataRes(types.Int)
	},
	"azuredevops.policy.type": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsPolicy).GetType()).ToDataRes(types.String)
	},
	"azuredevops.policy.typeName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsPolicy).GetTypeName()).ToDataRes(types.String)
	},
	"azuredevops.policy.enabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsPolicy).GetEnabled()).ToDataRes(types.Bool)
	},
	"azuredevops.policy.blocking": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsPolicy).GetBlocking()).ToDataRes(types.Bool)
	},
	"azuredevops.policy.scope": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsPolicy).GetScope()).ToDataRes(types.Array(types.Dict))
	},
	"azuredevops.policy.settings": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlAzuredevopsPolicy).GetSettings()).ToDataRes(types.Dict)
	},
}

func GetData(resource plugin.Resource, field string, args map[string]*llx.RawData) *plugin.DataRes {
	f, ok := getDataFields[resource.MqlName()+"."+field]
	if !ok {
		return &plugin.DataRes{Error: "cannot find '" + field + "' in resource '" + resource.MqlName() + "'"}
	}

	return f(resource)
}

var setDataFields = map[string]func(r plugin.Resource, v *llx.RawData) bool{
	"azuredevops.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevops).__id, ok = v.Value.(string)
		return
	},
	"azuredevops.organization.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsOrganization).__id, ok = v.Value.(string)
		return
	},
	"azuredevops.organization.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsOrganization).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.organization.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsOrganization).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.organization.deploymentType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsOrganization).DeploymentType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.organization.projects": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsOrganization).Projects, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"azuredevops.organization.repositories": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsOrganization).Repositories, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"azuredevops.organization.unreadableProjects": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsOrganization).UnreadableProjects, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"azuredevops.project.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsProject).__id, ok = v.Value.(string)
		return
	},
	"azuredevops.project.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsProject).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.project.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsProject).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.project.description": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsProject).Description, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.project.state": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsProject).State, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.project.visibility": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsProject).Visibility, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.project.url": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsProject).Url, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.project.lastUpdateTime": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsProject).LastUpdateTime, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"azuredevops.project.repositories": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsProject).Repositories, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"azuredevops.repository.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).__id, ok = v.Value.(string)
		return
	},
	"azuredevops.repository.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.repository.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.repository.projectName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).ProjectName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.repository.projectId": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).ProjectId, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.repository.fullName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).FullName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.repository.defaultBranch": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).DefaultBranch, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.repository.size": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).Size, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"azuredevops.repository.isDisabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).IsDisabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.repository.isEmpty": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).IsEmpty, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.repository.isFork": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).IsFork, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.repository.status": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).Status, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.repository.webUrl": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).WebUrl, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.repository.sshUrl": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).SshUrl, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.repository.cloneUrl": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).CloneUrl, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.repository.project": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).Project, ok = plugin.RawToTValue[*mqlAzuredevopsProject](v.Value, v.Error)
		return
	},
	"azuredevops.repository.branches": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).Branches, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"azuredevops.repository.policies": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsRepository).Policies, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"azuredevops.branch.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranch).__id, ok = v.Value.(string)
		return
	},
	"azuredevops.branch.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranch).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.branch.refName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranch).RefName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.branch.headCommitSha": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranch).HeadCommitSha, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.branch.isDefault": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranch).IsDefault, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.branch.isProtected": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranch).IsProtected, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.branch.protectionRules": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranch).ProtectionRules, ok = plugin.RawToTValue[*mqlAzuredevopsBranchProtection](v.Value, v.Error)
		return
	},
	"azuredevops.branchProtection.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).__id, ok = v.Value.(string)
		return
	},
	"azuredevops.branchProtection.refName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).RefName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.branchProtection.requiredPullRequestReviewsEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).RequiredPullRequestReviewsEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.branchProtection.requiredApprovingReviewCount": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).RequiredApprovingReviewCount, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"azuredevops.branchProtection.requireCodeOwnerReviews": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).RequireCodeOwnerReviews, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.branchProtection.requiredConversationResolutionEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).RequiredConversationResolutionEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.branchProtection.requiredStatusChecksEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).RequiredStatusChecksEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.branchProtection.policies": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).Policies, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"azuredevops.branchProtection.allowForcePushesEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).AllowForcePushesEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.branchProtection.enforceAdminsEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).EnforceAdminsEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.branchProtection.blockCreations": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsBranchProtection).BlockCreations, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.policy.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsPolicy).__id, ok = v.Value.(string)
		return
	},
	"azuredevops.policy.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsPolicy).Id, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"azuredevops.policy.type": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsPolicy).Type, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.policy.typeName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsPolicy).TypeName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"azuredevops.policy.enabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsPolicy).Enabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.policy.blocking": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsPolicy).Blocking, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"azuredevops.policy.scope": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsPolicy).Scope, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"azuredevops.policy.settings": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlAzuredevopsPolicy).Settings, ok = plugin.RawToTValue[any](v.Value, v.Error)
		return
	},
}

func SetData(resource plugin.Resource, field string, val *llx.RawData) error {
	f, ok := setDataFields[resource.MqlName()+"."+field]
	if !ok {
		return errors.New("[azuredevops] cannot set '" + field + "' in resource '" + resource.MqlName() + "', field not found")
	}

	if ok := f(resource, val); !ok {
		return errors.New("[azuredevops] cannot set '" + field + "' in resource '" + resource.MqlName() + "', type does not match")
	}
	return nil
}

func SetAllData(resource plugin.Resource, args map[string]*llx.RawData) error {
	var err error
	for k, v := range args {
		if err = SetData(resource, k, v); err != nil {
			return err
		}
	}
	return nil
}

// mqlAzuredevops for the azuredevops resource
type mqlAzuredevops struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlAzuredevopsInternal it will be used here
}

// createAzuredevops creates a new instance of this resource
func createAzuredevops(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlAzuredevops{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("azuredevops", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlAzuredevops) MqlName() string {
	return "azuredevops"
}

func (c *mqlAzuredevops) MqlID() string {
	return c.__id
}

// mqlAzuredevopsOrganization for the azuredevops.organization resource
type mqlAzuredevopsOrganization struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlAzuredevopsOrganizationInternal it will be used here
	Name               plugin.TValue[string]
	Id                 plugin.TValue[string]
	DeploymentType     plugin.TValue[string]
	Projects           plugin.TValue[[]any]
	Repositories       plugin.TValue[[]any]
	UnreadableProjects plugin.TValue[[]any]
}

// createAzuredevopsOrganization creates a new instance of this resource
func createAzuredevopsOrganization(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlAzuredevopsOrganization{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("azuredevops.organization", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlAzuredevopsOrganization) MqlName() string {
	return "azuredevops.organization"
}

func (c *mqlAzuredevopsOrganization) MqlID() string {
	return c.__id
}

func (c *mqlAzuredevopsOrganization) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlAzuredevopsOrganization) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlAzuredevopsOrganization) GetDeploymentType() *plugin.TValue[string] {
	return &c.DeploymentType
}

func (c *mqlAzuredevopsOrganization) GetProjects() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Projects, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("azuredevops.organization", c.__id, "projects")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.projects()
	})
}

func (c *mqlAzuredevopsOrganization) GetRepositories() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Repositories, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("azuredevops.organization", c.__id, "repositories")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.repositories()
	})
}

func (c *mqlAzuredevopsOrganization) GetUnreadableProjects() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.UnreadableProjects, func() ([]any, error) {
		return c.unreadableProjects()
	})
}

// mqlAzuredevopsProject for the azuredevops.project resource
type mqlAzuredevopsProject struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlAzuredevopsProjectInternal it will be used here
	Id             plugin.TValue[string]
	Name           plugin.TValue[string]
	Description    plugin.TValue[string]
	State          plugin.TValue[string]
	Visibility     plugin.TValue[string]
	Url            plugin.TValue[string]
	LastUpdateTime plugin.TValue[*time.Time]
	Repositories   plugin.TValue[[]any]
}

// createAzuredevopsProject creates a new instance of this resource
func createAzuredevopsProject(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlAzuredevopsProject{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("azuredevops.project", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlAzuredevopsProject) MqlName() string {
	return "azuredevops.project"
}

func (c *mqlAzuredevopsProject) MqlID() string {
	return c.__id
}

func (c *mqlAzuredevopsProject) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlAzuredevopsProject) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlAzuredevopsProject) GetDescription() *plugin.TValue[string] {
	return &c.Description
}

func (c *mqlAzuredevopsProject) GetState() *plugin.TValue[string] {
	return &c.State
}

func (c *mqlAzuredevopsProject) GetVisibility() *plugin.TValue[string] {
	return &c.Visibility
}

func (c *mqlAzuredevopsProject) GetUrl() *plugin.TValue[string] {
	return &c.Url
}

func (c *mqlAzuredevopsProject) GetLastUpdateTime() *plugin.TValue[*time.Time] {
	return &c.LastUpdateTime
}

func (c *mqlAzuredevopsProject) GetRepositories() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Repositories, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("azuredevops.project", c.__id, "repositories")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.repositories()
	})
}

// mqlAzuredevopsRepository for the azuredevops.repository resource
type mqlAzuredevopsRepository struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlAzuredevopsRepositoryInternal it will be used here
	Id            plugin.TValue[string]
	Name          plugin.TValue[string]
	ProjectName   plugin.TValue[string]
	ProjectId     plugin.TValue[string]
	FullName      plugin.TValue[string]
	DefaultBranch plugin.TValue[string]
	Size          plugin.TValue[int64]
	IsDisabled    plugin.TValue[bool]
	IsEmpty       plugin.TValue[bool]
	IsFork        plugin.TValue[bool]
	Status        plugin.TValue[string]
	WebUrl        plugin.TValue[string]
	SshUrl        plugin.TValue[string]
	CloneUrl      plugin.TValue[string]
	Project       plugin.TValue[*mqlAzuredevopsProject]
	Branches      plugin.TValue[[]any]
	Policies      plugin.TValue[[]any]
}

// createAzuredevopsRepository creates a new instance of this resource
func createAzuredevopsRepository(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlAzuredevopsRepository{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("azuredevops.repository", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlAzuredevopsRepository) MqlName() string {
	return "azuredevops.repository"
}

func (c *mqlAzuredevopsRepository) MqlID() string {
	return c.__id
}

func (c *mqlAzuredevopsRepository) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlAzuredevopsRepository) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlAzuredevopsRepository) GetProjectName() *plugin.TValue[string] {
	return &c.ProjectName
}

func (c *mqlAzuredevopsRepository) GetProjectId() *plugin.TValue[string] {
	return &c.ProjectId
}

func (c *mqlAzuredevopsRepository) GetFullName() *plugin.TValue[string] {
	return &c.FullName
}

func (c *mqlAzuredevopsRepository) GetDefaultBranch() *plugin.TValue[string] {
	return &c.DefaultBranch
}

func (c *mqlAzuredevopsRepository) GetSize() *plugin.TValue[int64] {
	return &c.Size
}

func (c *mqlAzuredevopsRepository) GetIsDisabled() *plugin.TValue[bool] {
	return &c.IsDisabled
}

func (c *mqlAzuredevopsRepository) GetIsEmpty() *plugin.TValue[bool] {
	return &c.IsEmpty
}

func (c *mqlAzuredevopsRepository) GetIsFork() *plugin.TValue[bool] {
	return &c.IsFork
}

func (c *mqlAzuredevopsRepository) GetStatus() *plugin.TValue[string] {
	return &c.Status
}

func (c *mqlAzuredevopsRepository) GetWebUrl() *plugin.TValue[string] {
	return &c.WebUrl
}

func (c *mqlAzuredevopsRepository) GetSshUrl() *plugin.TValue[string] {
	return &c.SshUrl
}

func (c *mqlAzuredevopsRepository) GetCloneUrl() *plugin.TValue[string] {
	return &c.CloneUrl
}

func (c *mqlAzuredevopsRepository) GetProject() *plugin.TValue[*mqlAzuredevopsProject] {
	return plugin.GetOrCompute[*mqlAzuredevopsProject](&c.Project, func() (*mqlAzuredevopsProject, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("azuredevops.repository", c.__id, "project")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlAzuredevopsProject), nil
			}
		}

		return c.project()
	})
}

func (c *mqlAzuredevopsRepository) GetBranches() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Branches, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("azuredevops.repository", c.__id, "branches")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.branches()
	})
}

func (c *mqlAzuredevopsRepository) GetPolicies() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Policies, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("azuredevops.repository", c.__id, "policies")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.policies()
	})
}

// mqlAzuredevopsBranch for the azuredevops.branch resource
type mqlAzuredevopsBranch struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlAzuredevopsBranchInternal
	Name            plugin.TValue[string]
	RefName         plugin.TValue[string]
	HeadCommitSha   plugin.TValue[string]
	IsDefault       plugin.TValue[bool]
	IsProtected     plugin.TValue[bool]
	ProtectionRules plugin.TValue[*mqlAzuredevopsBranchProtection]
}

// createAzuredevopsBranch creates a new instance of this resource
func createAzuredevopsBranch(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlAzuredevopsBranch{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("azuredevops.branch", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlAzuredevopsBranch) MqlName() string {
	return "azuredevops.branch"
}

func (c *mqlAzuredevopsBranch) MqlID() string {
	return c.__id
}

func (c *mqlAzuredevopsBranch) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlAzuredevopsBranch) GetRefName() *plugin.TValue[string] {
	return &c.RefName
}

func (c *mqlAzuredevopsBranch) GetHeadCommitSha() *plugin.TValue[string] {
	return &c.HeadCommitSha
}

func (c *mqlAzuredevopsBranch) GetIsDefault() *plugin.TValue[bool] {
	return &c.IsDefault
}

func (c *mqlAzuredevopsBranch) GetIsProtected() *plugin.TValue[bool] {
	return plugin.GetOrCompute[bool](&c.IsProtected, func() (bool, error) {
		return c.isProtected()
	})
}

func (c *mqlAzuredevopsBranch) GetProtectionRules() *plugin.TValue[*mqlAzuredevopsBranchProtection] {
	return plugin.GetOrCompute[*mqlAzuredevopsBranchProtection](&c.ProtectionRules, func() (*mqlAzuredevopsBranchProtection, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("azuredevops.branch", c.__id, "protectionRules")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlAzuredevopsBranchProtection), nil
			}
		}

		return c.protectionRules()
	})
}

// mqlAzuredevopsBranchProtection for the azuredevops.branchProtection resource
type mqlAzuredevopsBranchProtection struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlAzuredevopsBranchProtectionInternal
	RefName                               plugin.TValue[string]
	RequiredPullRequestReviewsEnabled     plugin.TValue[bool]
	RequiredApprovingReviewCount          plugin.TValue[int64]
	RequireCodeOwnerReviews               plugin.TValue[bool]
	RequiredConversationResolutionEnabled plugin.TValue[bool]
	RequiredStatusChecksEnabled           plugin.TValue[bool]
	Policies                              plugin.TValue[[]any]
	AllowForcePushesEnabled               plugin.TValue[bool]
	EnforceAdminsEnabled                  plugin.TValue[bool]
	BlockCreations                        plugin.TValue[bool]
}

// createAzuredevopsBranchProtection creates a new instance of this resource
func createAzuredevopsBranchProtection(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlAzuredevopsBranchProtection{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("azuredevops.branchProtection", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlAzuredevopsBranchProtection) MqlName() string {
	return "azuredevops.branchProtection"
}

func (c *mqlAzuredevopsBranchProtection) MqlID() string {
	return c.__id
}

func (c *mqlAzuredevopsBranchProtection) GetRefName() *plugin.TValue[string] {
	return &c.RefName
}

func (c *mqlAzuredevopsBranchProtection) GetRequiredPullRequestReviewsEnabled() *plugin.TValue[bool] {
	return &c.RequiredPullRequestReviewsEnabled
}

func (c *mqlAzuredevopsBranchProtection) GetRequiredApprovingReviewCount() *plugin.TValue[int64] {
	return &c.RequiredApprovingReviewCount
}

func (c *mqlAzuredevopsBranchProtection) GetRequireCodeOwnerReviews() *plugin.TValue[bool] {
	return &c.RequireCodeOwnerReviews
}

func (c *mqlAzuredevopsBranchProtection) GetRequiredConversationResolutionEnabled() *plugin.TValue[bool] {
	return &c.RequiredConversationResolutionEnabled
}

func (c *mqlAzuredevopsBranchProtection) GetRequiredStatusChecksEnabled() *plugin.TValue[bool] {
	return &c.RequiredStatusChecksEnabled
}

func (c *mqlAzuredevopsBranchProtection) GetPolicies() *plugin.TValue[[]any] {
	return &c.Policies
}

func (c *mqlAzuredevopsBranchProtection) GetAllowForcePushesEnabled() *plugin.TValue[bool] {
	return plugin.GetOrCompute[bool](&c.AllowForcePushesEnabled, func() (bool, error) {
		return c.allowForcePushesEnabled()
	})
}

func (c *mqlAzuredevopsBranchProtection) GetEnforceAdminsEnabled() *plugin.TValue[bool] {
	return plugin.GetOrCompute[bool](&c.EnforceAdminsEnabled, func() (bool, error) {
		return c.enforceAdminsEnabled()
	})
}

func (c *mqlAzuredevopsBranchProtection) GetBlockCreations() *plugin.TValue[bool] {
	return plugin.GetOrCompute[bool](&c.BlockCreations, func() (bool, error) {
		return c.blockCreations()
	})
}

// mqlAzuredevopsPolicy for the azuredevops.policy resource
type mqlAzuredevopsPolicy struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlAzuredevopsPolicyInternal it will be used here
	Id       plugin.TValue[int64]
	Type     plugin.TValue[string]
	TypeName plugin.TValue[string]
	Enabled  plugin.TValue[bool]
	Blocking plugin.TValue[bool]
	Scope    plugin.TValue[[]any]
	Settings plugin.TValue[any]
}

// createAzuredevopsPolicy creates a new instance of this resource
func createAzuredevopsPolicy(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlAzuredevopsPolicy{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("azuredevops.policy", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlAzuredevopsPolicy) MqlName() string {
	return "azuredevops.policy"
}

func (c *mqlAzuredevopsPolicy) MqlID() string {
	return c.__id
}

func (c *mqlAzuredevopsPolicy) GetId() *plugin.TValue[int64] {
	return &c.Id
}

func (c *mqlAzuredevopsPolicy) GetType() *plugin.TValue[string] {
	return &c.Type
}

func (c *mqlAzuredevopsPolicy) GetTypeName() *plugin.TValue[string] {
	return &c.TypeName
}

func (c *mqlAzuredevopsPolicy) GetEnabled() *plugin.TValue[bool] {
	return &c.Enabled
}

func (c *mqlAzuredevopsPolicy) GetBlocking() *plugin.TValue[bool] {
	return &c.Blocking
}

func (c *mqlAzuredevopsPolicy) GetScope() *plugin.TValue[[]any] {
	return &c.Scope
}

func (c *mqlAzuredevopsPolicy) GetSettings() *plugin.TValue[any] {
	return &c.Settings
}
