// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by resources. DO NOT EDIT.

package resources

import (
	"errors"
	"time"

	"go.mondoo.com/mql/llx"
	"go.mondoo.com/mql/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/types"
)

// The MQL type names exposed as public consts for ease of reference.
const (
	ResourceMistral                         string = "mistral"
	ResourceMistralModel                    string = "mistral.model"
	ResourceMistralFineTuningJob            string = "mistral.fineTuningJob"
	ResourceMistralFineTuningJobIntegration string = "mistral.fineTuningJob.integration"
	ResourceMistralFile                     string = "mistral.file"
	ResourceMistralBatchJob                 string = "mistral.batchJob"
	ResourceMistralBatchJobError            string = "mistral.batchJob.error"
	ResourceMistralConnector                string = "mistral.connector"
	ResourceMistralLibrary                  string = "mistral.library"
	ResourceMistralLibraryAccess            string = "mistral.library.access"
)

var resourceFactories map[string]plugin.ResourceFactory

func init() {
	resourceFactories = map[string]plugin.ResourceFactory{
		"mistral": {
			// to override args, implement: initMistral(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createMistral,
		},
		"mistral.model": {
			// to override args, implement: initMistralModel(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createMistralModel,
		},
		"mistral.fineTuningJob": {
			// to override args, implement: initMistralFineTuningJob(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createMistralFineTuningJob,
		},
		"mistral.fineTuningJob.integration": {
			// to override args, implement: initMistralFineTuningJobIntegration(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createMistralFineTuningJobIntegration,
		},
		"mistral.file": {
			// to override args, implement: initMistralFile(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createMistralFile,
		},
		"mistral.batchJob": {
			// to override args, implement: initMistralBatchJob(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createMistralBatchJob,
		},
		"mistral.batchJob.error": {
			// to override args, implement: initMistralBatchJobError(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createMistralBatchJobError,
		},
		"mistral.connector": {
			// to override args, implement: initMistralConnector(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createMistralConnector,
		},
		"mistral.library": {
			// to override args, implement: initMistralLibrary(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createMistralLibrary,
		},
		"mistral.library.access": {
			// to override args, implement: initMistralLibraryAccess(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createMistralLibraryAccess,
		},
	}
}

// NewResource is used by the runtime of this plugin to create new resources.
// Its arguments may be provided by users. This function is generally not
// used by initializing resources from recordings or from lists.
func NewResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	if f.Init != nil {
		cargs, res, err := f.Init(runtime, args)
		if err != nil {
			return res, err
		}

		if res != nil {
			mqlId := res.MqlID()
			id := name + "\x00" + mqlId
			if x, ok := runtime.Resources.Get(id); ok {
				return x, nil
			}
			runtime.Resources.Set(id, res)
			return res, nil
		}

		args = cargs
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

// CreateResource is used by the runtime of this plugin to create resources.
// Its arguments must be complete and pre-processed. This method is used
// for initializing resources from recordings or from lists.
func CreateResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

var getDataFields = map[string]func(r plugin.Resource) *plugin.DataRes{
	"mistral.ownedBy": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistral).GetOwnedBy()).ToDataRes(types.String)
	},
	"mistral.models": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistral).GetModels()).ToDataRes(types.Array(types.Resource("mistral.model")))
	},
	"mistral.fineTuningJobs": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistral).GetFineTuningJobs()).ToDataRes(types.Array(types.Resource("mistral.fineTuningJob")))
	},
	"mistral.files": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistral).GetFiles()).ToDataRes(types.Array(types.Resource("mistral.file")))
	},
	"mistral.batchJobs": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistral).GetBatchJobs()).ToDataRes(types.Array(types.Resource("mistral.batchJob")))
	},
	"mistral.connectors": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistral).GetConnectors()).ToDataRes(types.Array(types.Resource("mistral.connector")))
	},
	"mistral.libraries": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistral).GetLibraries()).ToDataRes(types.Array(types.Resource("mistral.library")))
	},
	"mistral.model.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetId()).ToDataRes(types.String)
	},
	"mistral.model.type": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetType()).ToDataRes(types.String)
	},
	"mistral.model.ownedBy": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetOwnedBy()).ToDataRes(types.String)
	},
	"mistral.model.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetName()).ToDataRes(types.String)
	},
	"mistral.model.description": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetDescription()).ToDataRes(types.String)
	},
	"mistral.model.maxContextLength": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetMaxContextLength()).ToDataRes(types.Int)
	},
	"mistral.model.created": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCreated()).ToDataRes(types.Time)
	},
	"mistral.model.aliases": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetAliases()).ToDataRes(types.Array(types.String))
	},
	"mistral.model.deprecation": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetDeprecation()).ToDataRes(types.Time)
	},
	"mistral.model.replacementModel": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetReplacementModel()).ToDataRes(types.Resource("mistral.model"))
	},
	"mistral.model.defaultModelTemperature": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetDefaultModelTemperature()).ToDataRes(types.Float)
	},
	"mistral.model.capabilityChat": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCapabilityChat()).ToDataRes(types.Bool)
	},
	"mistral.model.capabilityFunctionCalling": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCapabilityFunctionCalling()).ToDataRes(types.Bool)
	},
	"mistral.model.capabilityFim": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCapabilityFim()).ToDataRes(types.Bool)
	},
	"mistral.model.capabilityFineTuning": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCapabilityFineTuning()).ToDataRes(types.Bool)
	},
	"mistral.model.capabilityVision": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCapabilityVision()).ToDataRes(types.Bool)
	},
	"mistral.model.capabilityOcr": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCapabilityOcr()).ToDataRes(types.Bool)
	},
	"mistral.model.capabilityClassification": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCapabilityClassification()).ToDataRes(types.Bool)
	},
	"mistral.model.capabilityModeration": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCapabilityModeration()).ToDataRes(types.Bool)
	},
	"mistral.model.capabilityAudio": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCapabilityAudio()).ToDataRes(types.Bool)
	},
	"mistral.model.capabilityAudioTranscription": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetCapabilityAudioTranscription()).ToDataRes(types.Bool)
	},
	"mistral.model.job": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetJob()).ToDataRes(types.String)
	},
	"mistral.model.root": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetRoot()).ToDataRes(types.String)
	},
	"mistral.model.archived": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetArchived()).ToDataRes(types.Bool)
	},
	"mistral.model.family": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetFamily()).ToDataRes(types.String)
	},
	"mistral.model.parameterSize": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralModel).GetParameterSize()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetId()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.status": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetStatus()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.model": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetModel()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.fineTunedModel": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetFineTunedModel()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.suffix": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetSuffix()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.autoStart": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetAutoStart()).ToDataRes(types.Bool)
	},
	"mistral.fineTuningJob.trainingFiles": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetTrainingFiles()).ToDataRes(types.Array(types.String))
	},
	"mistral.fineTuningJob.validationFiles": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetValidationFiles()).ToDataRes(types.Array(types.String))
	},
	"mistral.fineTuningJob.trainedTokens": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetTrainedTokens()).ToDataRes(types.Int)
	},
	"mistral.fineTuningJob.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetCreatedAt()).ToDataRes(types.Time)
	},
	"mistral.fineTuningJob.modifiedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetModifiedAt()).ToDataRes(types.Time)
	},
	"mistral.fineTuningJob.jobType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetJobType()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.trainingSteps": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetTrainingSteps()).ToDataRes(types.Int)
	},
	"mistral.fineTuningJob.learningRate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetLearningRate()).ToDataRes(types.Float)
	},
	"mistral.fineTuningJob.epochs": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetEpochs()).ToDataRes(types.Float)
	},
	"mistral.fineTuningJob.expectedDurationSeconds": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetExpectedDurationSeconds()).ToDataRes(types.Int)
	},
	"mistral.fineTuningJob.cost": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetCost()).ToDataRes(types.Float)
	},
	"mistral.fineTuningJob.costCurrency": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetCostCurrency()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.integrations": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJob).GetIntegrations()).ToDataRes(types.Array(types.Resource("mistral.fineTuningJob.integration")))
	},
	"mistral.fineTuningJob.integration.type": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJobIntegration).GetType()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.integration.project": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJobIntegration).GetProject()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.integration.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJobIntegration).GetName()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.integration.runName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJobIntegration).GetRunName()).ToDataRes(types.String)
	},
	"mistral.fineTuningJob.integration.url": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFineTuningJobIntegration).GetUrl()).ToDataRes(types.String)
	},
	"mistral.file.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFile).GetId()).ToDataRes(types.String)
	},
	"mistral.file.filename": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFile).GetFilename()).ToDataRes(types.String)
	},
	"mistral.file.purpose": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFile).GetPurpose()).ToDataRes(types.String)
	},
	"mistral.file.bytes": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFile).GetBytes()).ToDataRes(types.Int)
	},
	"mistral.file.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFile).GetCreatedAt()).ToDataRes(types.Time)
	},
	"mistral.file.sampleType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFile).GetSampleType()).ToDataRes(types.String)
	},
	"mistral.file.source": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFile).GetSource()).ToDataRes(types.String)
	},
	"mistral.file.numLines": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFile).GetNumLines()).ToDataRes(types.Int)
	},
	"mistral.file.mimeType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralFile).GetMimeType()).ToDataRes(types.String)
	},
	"mistral.batchJob.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetId()).ToDataRes(types.String)
	},
	"mistral.batchJob.status": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetStatus()).ToDataRes(types.String)
	},
	"mistral.batchJob.endpoint": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetEndpoint()).ToDataRes(types.String)
	},
	"mistral.batchJob.model": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetModel()).ToDataRes(types.String)
	},
	"mistral.batchJob.inputFiles": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetInputFiles()).ToDataRes(types.Array(types.String))
	},
	"mistral.batchJob.outputFile": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetOutputFile()).ToDataRes(types.String)
	},
	"mistral.batchJob.errorFile": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetErrorFile()).ToDataRes(types.String)
	},
	"mistral.batchJob.totalRequests": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetTotalRequests()).ToDataRes(types.Int)
	},
	"mistral.batchJob.completedRequests": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetCompletedRequests()).ToDataRes(types.Int)
	},
	"mistral.batchJob.succeededRequests": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetSucceededRequests()).ToDataRes(types.Int)
	},
	"mistral.batchJob.failedRequests": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetFailedRequests()).ToDataRes(types.Int)
	},
	"mistral.batchJob.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetCreatedAt()).ToDataRes(types.Time)
	},
	"mistral.batchJob.startedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetStartedAt()).ToDataRes(types.Time)
	},
	"mistral.batchJob.completedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetCompletedAt()).ToDataRes(types.Time)
	},
	"mistral.batchJob.errors": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetErrors()).ToDataRes(types.Array(types.Resource("mistral.batchJob.error")))
	},
	"mistral.batchJob.metadata": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJob).GetMetadata()).ToDataRes(types.Map(types.String, types.String))
	},
	"mistral.batchJob.error.message": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJobError).GetMessage()).ToDataRes(types.String)
	},
	"mistral.batchJob.error.count": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralBatchJobError).GetCount()).ToDataRes(types.Int)
	},
	"mistral.connector.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetId()).ToDataRes(types.String)
	},
	"mistral.connector.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetName()).ToDataRes(types.String)
	},
	"mistral.connector.description": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetDescription()).ToDataRes(types.String)
	},
	"mistral.connector.server": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetServer()).ToDataRes(types.String)
	},
	"mistral.connector.protocol": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetProtocol()).ToDataRes(types.String)
	},
	"mistral.connector.visibility": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetVisibility()).ToDataRes(types.String)
	},
	"mistral.connector.ownerType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetOwnerType()).ToDataRes(types.String)
	},
	"mistral.connector.supportedAuthMethods": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetSupportedAuthMethods()).ToDataRes(types.Array(types.String))
	},
	"mistral.connector.privateToolExecution": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetPrivateToolExecution()).ToDataRes(types.Bool)
	},
	"mistral.connector.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetCreatedAt()).ToDataRes(types.Time)
	},
	"mistral.connector.modifiedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralConnector).GetModifiedAt()).ToDataRes(types.Time)
	},
	"mistral.library.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibrary).GetId()).ToDataRes(types.String)
	},
	"mistral.library.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibrary).GetName()).ToDataRes(types.String)
	},
	"mistral.library.description": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibrary).GetDescription()).ToDataRes(types.String)
	},
	"mistral.library.nbDocuments": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibrary).GetNbDocuments()).ToDataRes(types.Int)
	},
	"mistral.library.totalSize": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibrary).GetTotalSize()).ToDataRes(types.Int)
	},
	"mistral.library.ownerType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibrary).GetOwnerType()).ToDataRes(types.String)
	},
	"mistral.library.ownerId": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibrary).GetOwnerId()).ToDataRes(types.String)
	},
	"mistral.library.createdAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibrary).GetCreatedAt()).ToDataRes(types.Time)
	},
	"mistral.library.updatedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibrary).GetUpdatedAt()).ToDataRes(types.Time)
	},
	"mistral.library.accesses": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibrary).GetAccesses()).ToDataRes(types.Array(types.Resource("mistral.library.access")))
	},
	"mistral.library.access.shareWithType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibraryAccess).GetShareWithType()).ToDataRes(types.String)
	},
	"mistral.library.access.shareWithUuid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibraryAccess).GetShareWithUuid()).ToDataRes(types.String)
	},
	"mistral.library.access.role": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlMistralLibraryAccess).GetRole()).ToDataRes(types.String)
	},
}

func GetData(resource plugin.Resource, field string, args map[string]*llx.RawData) *plugin.DataRes {
	f, ok := getDataFields[resource.MqlName()+"."+field]
	if !ok {
		return &plugin.DataRes{Error: "cannot find '" + field + "' in resource '" + resource.MqlName() + "'"}
	}

	return f(resource)
}

var setDataFields = map[string]func(r plugin.Resource, v *llx.RawData) bool{
	"mistral.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistral).__id, ok = v.Value.(string)
		return
	},
	"mistral.ownedBy": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistral).OwnedBy, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.models": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistral).Models, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJobs": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistral).FineTuningJobs, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.files": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistral).Files, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.batchJobs": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistral).BatchJobs, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.connectors": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistral).Connectors, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.libraries": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistral).Libraries, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.model.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).__id, ok = v.Value.(string)
		return
	},
	"mistral.model.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.model.type": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Type, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.model.ownedBy": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).OwnedBy, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.model.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.model.description": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Description, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.model.maxContextLength": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).MaxContextLength, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.model.created": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Created, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.model.aliases": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Aliases, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.model.deprecation": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Deprecation, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.model.replacementModel": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).ReplacementModel, ok = plugin.RawToTValue[*mqlMistralModel](v.Value, v.Error)
		return
	},
	"mistral.model.defaultModelTemperature": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).DefaultModelTemperature, ok = plugin.RawToTValue[float64](v.Value, v.Error)
		return
	},
	"mistral.model.capabilityChat": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).CapabilityChat, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.capabilityFunctionCalling": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).CapabilityFunctionCalling, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.capabilityFim": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).CapabilityFim, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.capabilityFineTuning": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).CapabilityFineTuning, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.capabilityVision": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).CapabilityVision, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.capabilityOcr": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).CapabilityOcr, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.capabilityClassification": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).CapabilityClassification, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.capabilityModeration": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).CapabilityModeration, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.capabilityAudio": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).CapabilityAudio, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.capabilityAudioTranscription": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).CapabilityAudioTranscription, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.job": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Job, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.model.root": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Root, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.model.archived": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Archived, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.model.family": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).Family, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.model.parameterSize": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralModel).ParameterSize, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).__id, ok = v.Value.(string)
		return
	},
	"mistral.fineTuningJob.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.status": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).Status, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.model": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).Model, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.fineTunedModel": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).FineTunedModel, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.suffix": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).Suffix, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.autoStart": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).AutoStart, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.trainingFiles": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).TrainingFiles, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.validationFiles": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).ValidationFiles, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.trainedTokens": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).TrainedTokens, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.modifiedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).ModifiedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.jobType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).JobType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.trainingSteps": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).TrainingSteps, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.learningRate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).LearningRate, ok = plugin.RawToTValue[float64](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.epochs": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).Epochs, ok = plugin.RawToTValue[float64](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.expectedDurationSeconds": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).ExpectedDurationSeconds, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.cost": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).Cost, ok = plugin.RawToTValue[float64](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.costCurrency": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).CostCurrency, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.integrations": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJob).Integrations, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.integration.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJobIntegration).__id, ok = v.Value.(string)
		return
	},
	"mistral.fineTuningJob.integration.type": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJobIntegration).Type, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.integration.project": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJobIntegration).Project, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.integration.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJobIntegration).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.integration.runName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJobIntegration).RunName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.fineTuningJob.integration.url": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFineTuningJobIntegration).Url, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.file.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFile).__id, ok = v.Value.(string)
		return
	},
	"mistral.file.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFile).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.file.filename": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFile).Filename, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.file.purpose": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFile).Purpose, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.file.bytes": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFile).Bytes, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.file.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFile).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.file.sampleType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFile).SampleType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.file.source": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFile).Source, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.file.numLines": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFile).NumLines, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.file.mimeType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralFile).MimeType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.batchJob.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).__id, ok = v.Value.(string)
		return
	},
	"mistral.batchJob.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.batchJob.status": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).Status, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.batchJob.endpoint": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).Endpoint, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.batchJob.model": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).Model, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.batchJob.inputFiles": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).InputFiles, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.batchJob.outputFile": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).OutputFile, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.batchJob.errorFile": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).ErrorFile, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.batchJob.totalRequests": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).TotalRequests, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.batchJob.completedRequests": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).CompletedRequests, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.batchJob.succeededRequests": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).SucceededRequests, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.batchJob.failedRequests": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).FailedRequests, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.batchJob.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.batchJob.startedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).StartedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.batchJob.completedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).CompletedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.batchJob.errors": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).Errors, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.batchJob.metadata": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJob).Metadata, ok = plugin.RawToTValue[map[string]any](v.Value, v.Error)
		return
	},
	"mistral.batchJob.error.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJobError).__id, ok = v.Value.(string)
		return
	},
	"mistral.batchJob.error.message": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJobError).Message, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.batchJob.error.count": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralBatchJobError).Count, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.connector.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).__id, ok = v.Value.(string)
		return
	},
	"mistral.connector.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.connector.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.connector.description": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).Description, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.connector.server": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).Server, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.connector.protocol": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).Protocol, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.connector.visibility": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).Visibility, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.connector.ownerType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).OwnerType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.connector.supportedAuthMethods": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).SupportedAuthMethods, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.connector.privateToolExecution": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).PrivateToolExecution, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"mistral.connector.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.connector.modifiedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralConnector).ModifiedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.library.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).__id, ok = v.Value.(string)
		return
	},
	"mistral.library.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.library.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.library.description": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).Description, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.library.nbDocuments": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).NbDocuments, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.library.totalSize": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).TotalSize, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"mistral.library.ownerType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).OwnerType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.library.ownerId": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).OwnerId, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.library.createdAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).CreatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.library.updatedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).UpdatedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"mistral.library.accesses": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibrary).Accesses, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"mistral.library.access.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibraryAccess).__id, ok = v.Value.(string)
		return
	},
	"mistral.library.access.shareWithType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibraryAccess).ShareWithType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.library.access.shareWithUuid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibraryAccess).ShareWithUuid, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"mistral.library.access.role": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlMistralLibraryAccess).Role, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
}

func SetData(resource plugin.Resource, field string, val *llx.RawData) error {
	f, ok := setDataFields[resource.MqlName()+"."+field]
	if !ok {
		return errors.New("[mistral] cannot set '" + field + "' in resource '" + resource.MqlName() + "', field not found")
	}

	if ok := f(resource, val); !ok {
		return errors.New("[mistral] cannot set '" + field + "' in resource '" + resource.MqlName() + "', type does not match")
	}
	return nil
}

func SetAllData(resource plugin.Resource, args map[string]*llx.RawData) error {
	var err error
	for k, v := range args {
		if err = SetData(resource, k, v); err != nil {
			return err
		}
	}
	return nil
}

// mqlMistral for the mistral resource
type mqlMistral struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlMistralInternal it will be used here
	OwnedBy        plugin.TValue[string]
	Models         plugin.TValue[[]any]
	FineTuningJobs plugin.TValue[[]any]
	Files          plugin.TValue[[]any]
	BatchJobs      plugin.TValue[[]any]
	Connectors     plugin.TValue[[]any]
	Libraries      plugin.TValue[[]any]
}

// createMistral creates a new instance of this resource
func createMistral(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlMistral{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("mistral", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlMistral) MqlName() string {
	return "mistral"
}

func (c *mqlMistral) MqlID() string {
	return c.__id
}

func (c *mqlMistral) GetOwnedBy() *plugin.TValue[string] {
	return plugin.GetOrCompute[string](&c.OwnedBy, func() (string, error) {
		return c.ownedBy()
	})
}

func (c *mqlMistral) GetModels() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Models, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("mistral", c.__id, "models")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.models()
	})
}

func (c *mqlMistral) GetFineTuningJobs() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.FineTuningJobs, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("mistral", c.__id, "fineTuningJobs")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.fineTuningJobs()
	})
}

func (c *mqlMistral) GetFiles() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Files, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("mistral", c.__id, "files")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.files()
	})
}

func (c *mqlMistral) GetBatchJobs() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.BatchJobs, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("mistral", c.__id, "batchJobs")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.batchJobs()
	})
}

func (c *mqlMistral) GetConnectors() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Connectors, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("mistral", c.__id, "connectors")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.connectors()
	})
}

func (c *mqlMistral) GetLibraries() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Libraries, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("mistral", c.__id, "libraries")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.libraries()
	})
}

// mqlMistralModel for the mistral.model resource
type mqlMistralModel struct {
	MqlRuntime *plugin.Runtime
	__id       string
	mqlMistralModelInternal
	Id                           plugin.TValue[string]
	Type                         plugin.TValue[string]
	OwnedBy                      plugin.TValue[string]
	Name                         plugin.TValue[string]
	Description                  plugin.TValue[string]
	MaxContextLength             plugin.TValue[int64]
	Created                      plugin.TValue[*time.Time]
	Aliases                      plugin.TValue[[]any]
	Deprecation                  plugin.TValue[*time.Time]
	ReplacementModel             plugin.TValue[*mqlMistralModel]
	DefaultModelTemperature      plugin.TValue[float64]
	CapabilityChat               plugin.TValue[bool]
	CapabilityFunctionCalling    plugin.TValue[bool]
	CapabilityFim                plugin.TValue[bool]
	CapabilityFineTuning         plugin.TValue[bool]
	CapabilityVision             plugin.TValue[bool]
	CapabilityOcr                plugin.TValue[bool]
	CapabilityClassification     plugin.TValue[bool]
	CapabilityModeration         plugin.TValue[bool]
	CapabilityAudio              plugin.TValue[bool]
	CapabilityAudioTranscription plugin.TValue[bool]
	Job                          plugin.TValue[string]
	Root                         plugin.TValue[string]
	Archived                     plugin.TValue[bool]
	Family                       plugin.TValue[string]
	ParameterSize                plugin.TValue[string]
}

// createMistralModel creates a new instance of this resource
func createMistralModel(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlMistralModel{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("mistral.model", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlMistralModel) MqlName() string {
	return "mistral.model"
}

func (c *mqlMistralModel) MqlID() string {
	return c.__id
}

func (c *mqlMistralModel) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlMistralModel) GetType() *plugin.TValue[string] {
	return &c.Type
}

func (c *mqlMistralModel) GetOwnedBy() *plugin.TValue[string] {
	return &c.OwnedBy
}

func (c *mqlMistralModel) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlMistralModel) GetDescription() *plugin.TValue[string] {
	return &c.Description
}

func (c *mqlMistralModel) GetMaxContextLength() *plugin.TValue[int64] {
	return &c.MaxContextLength
}

func (c *mqlMistralModel) GetCreated() *plugin.TValue[*time.Time] {
	return &c.Created
}

func (c *mqlMistralModel) GetAliases() *plugin.TValue[[]any] {
	return &c.Aliases
}

func (c *mqlMistralModel) GetDeprecation() *plugin.TValue[*time.Time] {
	return &c.Deprecation
}

func (c *mqlMistralModel) GetReplacementModel() *plugin.TValue[*mqlMistralModel] {
	return plugin.GetOrCompute[*mqlMistralModel](&c.ReplacementModel, func() (*mqlMistralModel, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("mistral.model", c.__id, "replacementModel")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlMistralModel), nil
			}
		}

		return c.replacementModel()
	})
}

func (c *mqlMistralModel) GetDefaultModelTemperature() *plugin.TValue[float64] {
	return &c.DefaultModelTemperature
}

func (c *mqlMistralModel) GetCapabilityChat() *plugin.TValue[bool] {
	return &c.CapabilityChat
}

func (c *mqlMistralModel) GetCapabilityFunctionCalling() *plugin.TValue[bool] {
	return &c.CapabilityFunctionCalling
}

func (c *mqlMistralModel) GetCapabilityFim() *plugin.TValue[bool] {
	return &c.CapabilityFim
}

func (c *mqlMistralModel) GetCapabilityFineTuning() *plugin.TValue[bool] {
	return &c.CapabilityFineTuning
}

func (c *mqlMistralModel) GetCapabilityVision() *plugin.TValue[bool] {
	return &c.CapabilityVision
}

func (c *mqlMistralModel) GetCapabilityOcr() *plugin.TValue[bool] {
	return &c.CapabilityOcr
}

func (c *mqlMistralModel) GetCapabilityClassification() *plugin.TValue[bool] {
	return &c.CapabilityClassification
}

func (c *mqlMistralModel) GetCapabilityModeration() *plugin.TValue[bool] {
	return &c.CapabilityModeration
}

func (c *mqlMistralModel) GetCapabilityAudio() *plugin.TValue[bool] {
	return &c.CapabilityAudio
}

func (c *mqlMistralModel) GetCapabilityAudioTranscription() *plugin.TValue[bool] {
	return &c.CapabilityAudioTranscription
}

func (c *mqlMistralModel) GetJob() *plugin.TValue[string] {
	return &c.Job
}

func (c *mqlMistralModel) GetRoot() *plugin.TValue[string] {
	return &c.Root
}

func (c *mqlMistralModel) GetArchived() *plugin.TValue[bool] {
	return &c.Archived
}

func (c *mqlMistralModel) GetFamily() *plugin.TValue[string] {
	return plugin.GetOrCompute[string](&c.Family, func() (string, error) {
		return c.family()
	})
}

func (c *mqlMistralModel) GetParameterSize() *plugin.TValue[string] {
	return plugin.GetOrCompute[string](&c.ParameterSize, func() (string, error) {
		return c.parameterSize()
	})
}

// mqlMistralFineTuningJob for the mistral.fineTuningJob resource
type mqlMistralFineTuningJob struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlMistralFineTuningJobInternal it will be used here
	Id                      plugin.TValue[string]
	Status                  plugin.TValue[string]
	Model                   plugin.TValue[string]
	FineTunedModel          plugin.TValue[string]
	Suffix                  plugin.TValue[string]
	AutoStart               plugin.TValue[bool]
	TrainingFiles           plugin.TValue[[]any]
	ValidationFiles         plugin.TValue[[]any]
	TrainedTokens           plugin.TValue[int64]
	CreatedAt               plugin.TValue[*time.Time]
	ModifiedAt              plugin.TValue[*time.Time]
	JobType                 plugin.TValue[string]
	TrainingSteps           plugin.TValue[int64]
	LearningRate            plugin.TValue[float64]
	Epochs                  plugin.TValue[float64]
	ExpectedDurationSeconds plugin.TValue[int64]
	Cost                    plugin.TValue[float64]
	CostCurrency            plugin.TValue[string]
	Integrations            plugin.TValue[[]any]
}

// createMistralFineTuningJob creates a new instance of this resource
func createMistralFineTuningJob(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlMistralFineTuningJob{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("mistral.fineTuningJob", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlMistralFineTuningJob) MqlName() string {
	return "mistral.fineTuningJob"
}

func (c *mqlMistralFineTuningJob) MqlID() string {
	return c.__id
}

func (c *mqlMistralFineTuningJob) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlMistralFineTuningJob) GetStatus() *plugin.TValue[string] {
	return &c.Status
}

func (c *mqlMistralFineTuningJob) GetModel() *plugin.TValue[string] {
	return &c.Model
}

func (c *mqlMistralFineTuningJob) GetFineTunedModel() *plugin.TValue[string] {
	return &c.FineTunedModel
}

func (c *mqlMistralFineTuningJob) GetSuffix() *plugin.TValue[string] {
	return &c.Suffix
}

func (c *mqlMistralFineTuningJob) GetAutoStart() *plugin.TValue[bool] {
	return &c.AutoStart
}

func (c *mqlMistralFineTuningJob) GetTrainingFiles() *plugin.TValue[[]any] {
	return &c.TrainingFiles
}

func (c *mqlMistralFineTuningJob) GetValidationFiles() *plugin.TValue[[]any] {
	return &c.ValidationFiles
}

func (c *mqlMistralFineTuningJob) GetTrainedTokens() *plugin.TValue[int64] {
	return &c.TrainedTokens
}

func (c *mqlMistralFineTuningJob) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlMistralFineTuningJob) GetModifiedAt() *plugin.TValue[*time.Time] {
	return &c.ModifiedAt
}

func (c *mqlMistralFineTuningJob) GetJobType() *plugin.TValue[string] {
	return &c.JobType
}

func (c *mqlMistralFineTuningJob) GetTrainingSteps() *plugin.TValue[int64] {
	return &c.TrainingSteps
}

func (c *mqlMistralFineTuningJob) GetLearningRate() *plugin.TValue[float64] {
	return &c.LearningRate
}

func (c *mqlMistralFineTuningJob) GetEpochs() *plugin.TValue[float64] {
	return &c.Epochs
}

func (c *mqlMistralFineTuningJob) GetExpectedDurationSeconds() *plugin.TValue[int64] {
	return &c.ExpectedDurationSeconds
}

func (c *mqlMistralFineTuningJob) GetCost() *plugin.TValue[float64] {
	return &c.Cost
}

func (c *mqlMistralFineTuningJob) GetCostCurrency() *plugin.TValue[string] {
	return &c.CostCurrency
}

func (c *mqlMistralFineTuningJob) GetIntegrations() *plugin.TValue[[]any] {
	return &c.Integrations
}

// mqlMistralFineTuningJobIntegration for the mistral.fineTuningJob.integration resource
type mqlMistralFineTuningJobIntegration struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlMistralFineTuningJobIntegrationInternal it will be used here
	Type    plugin.TValue[string]
	Project plugin.TValue[string]
	Name    plugin.TValue[string]
	RunName plugin.TValue[string]
	Url     plugin.TValue[string]
}

// createMistralFineTuningJobIntegration creates a new instance of this resource
func createMistralFineTuningJobIntegration(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlMistralFineTuningJobIntegration{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("mistral.fineTuningJob.integration", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlMistralFineTuningJobIntegration) MqlName() string {
	return "mistral.fineTuningJob.integration"
}

func (c *mqlMistralFineTuningJobIntegration) MqlID() string {
	return c.__id
}

func (c *mqlMistralFineTuningJobIntegration) GetType() *plugin.TValue[string] {
	return &c.Type
}

func (c *mqlMistralFineTuningJobIntegration) GetProject() *plugin.TValue[string] {
	return &c.Project
}

func (c *mqlMistralFineTuningJobIntegration) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlMistralFineTuningJobIntegration) GetRunName() *plugin.TValue[string] {
	return &c.RunName
}

func (c *mqlMistralFineTuningJobIntegration) GetUrl() *plugin.TValue[string] {
	return &c.Url
}

// mqlMistralFile for the mistral.file resource
type mqlMistralFile struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlMistralFileInternal it will be used here
	Id         plugin.TValue[string]
	Filename   plugin.TValue[string]
	Purpose    plugin.TValue[string]
	Bytes      plugin.TValue[int64]
	CreatedAt  plugin.TValue[*time.Time]
	SampleType plugin.TValue[string]
	Source     plugin.TValue[string]
	NumLines   plugin.TValue[int64]
	MimeType   plugin.TValue[string]
}

// createMistralFile creates a new instance of this resource
func createMistralFile(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlMistralFile{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("mistral.file", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlMistralFile) MqlName() string {
	return "mistral.file"
}

func (c *mqlMistralFile) MqlID() string {
	return c.__id
}

func (c *mqlMistralFile) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlMistralFile) GetFilename() *plugin.TValue[string] {
	return &c.Filename
}

func (c *mqlMistralFile) GetPurpose() *plugin.TValue[string] {
	return &c.Purpose
}

func (c *mqlMistralFile) GetBytes() *plugin.TValue[int64] {
	return &c.Bytes
}

func (c *mqlMistralFile) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlMistralFile) GetSampleType() *plugin.TValue[string] {
	return &c.SampleType
}

func (c *mqlMistralFile) GetSource() *plugin.TValue[string] {
	return &c.Source
}

func (c *mqlMistralFile) GetNumLines() *plugin.TValue[int64] {
	return &c.NumLines
}

func (c *mqlMistralFile) GetMimeType() *plugin.TValue[string] {
	return &c.MimeType
}

// mqlMistralBatchJob for the mistral.batchJob resource
type mqlMistralBatchJob struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlMistralBatchJobInternal it will be used here
	Id                plugin.TValue[string]
	Status            plugin.TValue[string]
	Endpoint          plugin.TValue[string]
	Model             plugin.TValue[string]
	InputFiles        plugin.TValue[[]any]
	OutputFile        plugin.TValue[string]
	ErrorFile         plugin.TValue[string]
	TotalRequests     plugin.TValue[int64]
	CompletedRequests plugin.TValue[int64]
	SucceededRequests plugin.TValue[int64]
	FailedRequests    plugin.TValue[int64]
	CreatedAt         plugin.TValue[*time.Time]
	StartedAt         plugin.TValue[*time.Time]
	CompletedAt       plugin.TValue[*time.Time]
	Errors            plugin.TValue[[]any]
	Metadata          plugin.TValue[map[string]any]
}

// createMistralBatchJob creates a new instance of this resource
func createMistralBatchJob(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlMistralBatchJob{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("mistral.batchJob", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlMistralBatchJob) MqlName() string {
	return "mistral.batchJob"
}

func (c *mqlMistralBatchJob) MqlID() string {
	return c.__id
}

func (c *mqlMistralBatchJob) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlMistralBatchJob) GetStatus() *plugin.TValue[string] {
	return &c.Status
}

func (c *mqlMistralBatchJob) GetEndpoint() *plugin.TValue[string] {
	return &c.Endpoint
}

func (c *mqlMistralBatchJob) GetModel() *plugin.TValue[string] {
	return &c.Model
}

func (c *mqlMistralBatchJob) GetInputFiles() *plugin.TValue[[]any] {
	return &c.InputFiles
}

func (c *mqlMistralBatchJob) GetOutputFile() *plugin.TValue[string] {
	return &c.OutputFile
}

func (c *mqlMistralBatchJob) GetErrorFile() *plugin.TValue[string] {
	return &c.ErrorFile
}

func (c *mqlMistralBatchJob) GetTotalRequests() *plugin.TValue[int64] {
	return &c.TotalRequests
}

func (c *mqlMistralBatchJob) GetCompletedRequests() *plugin.TValue[int64] {
	return &c.CompletedRequests
}

func (c *mqlMistralBatchJob) GetSucceededRequests() *plugin.TValue[int64] {
	return &c.SucceededRequests
}

func (c *mqlMistralBatchJob) GetFailedRequests() *plugin.TValue[int64] {
	return &c.FailedRequests
}

func (c *mqlMistralBatchJob) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlMistralBatchJob) GetStartedAt() *plugin.TValue[*time.Time] {
	return &c.StartedAt
}

func (c *mqlMistralBatchJob) GetCompletedAt() *plugin.TValue[*time.Time] {
	return &c.CompletedAt
}

func (c *mqlMistralBatchJob) GetErrors() *plugin.TValue[[]any] {
	return &c.Errors
}

func (c *mqlMistralBatchJob) GetMetadata() *plugin.TValue[map[string]any] {
	return &c.Metadata
}

// mqlMistralBatchJobError for the mistral.batchJob.error resource
type mqlMistralBatchJobError struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlMistralBatchJobErrorInternal it will be used here
	Message plugin.TValue[string]
	Count   plugin.TValue[int64]
}

// createMistralBatchJobError creates a new instance of this resource
func createMistralBatchJobError(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlMistralBatchJobError{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("mistral.batchJob.error", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlMistralBatchJobError) MqlName() string {
	return "mistral.batchJob.error"
}

func (c *mqlMistralBatchJobError) MqlID() string {
	return c.__id
}

func (c *mqlMistralBatchJobError) GetMessage() *plugin.TValue[string] {
	return &c.Message
}

func (c *mqlMistralBatchJobError) GetCount() *plugin.TValue[int64] {
	return &c.Count
}

// mqlMistralConnector for the mistral.connector resource
type mqlMistralConnector struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlMistralConnectorInternal it will be used here
	Id                   plugin.TValue[string]
	Name                 plugin.TValue[string]
	Description          plugin.TValue[string]
	Server               plugin.TValue[string]
	Protocol             plugin.TValue[string]
	Visibility           plugin.TValue[string]
	OwnerType            plugin.TValue[string]
	SupportedAuthMethods plugin.TValue[[]any]
	PrivateToolExecution plugin.TValue[bool]
	CreatedAt            plugin.TValue[*time.Time]
	ModifiedAt           plugin.TValue[*time.Time]
}

// createMistralConnector creates a new instance of this resource
func createMistralConnector(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlMistralConnector{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("mistral.connector", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlMistralConnector) MqlName() string {
	return "mistral.connector"
}

func (c *mqlMistralConnector) MqlID() string {
	return c.__id
}

func (c *mqlMistralConnector) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlMistralConnector) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlMistralConnector) GetDescription() *plugin.TValue[string] {
	return &c.Description
}

func (c *mqlMistralConnector) GetServer() *plugin.TValue[string] {
	return &c.Server
}

func (c *mqlMistralConnector) GetProtocol() *plugin.TValue[string] {
	return &c.Protocol
}

func (c *mqlMistralConnector) GetVisibility() *plugin.TValue[string] {
	return &c.Visibility
}

func (c *mqlMistralConnector) GetOwnerType() *plugin.TValue[string] {
	return &c.OwnerType
}

func (c *mqlMistralConnector) GetSupportedAuthMethods() *plugin.TValue[[]any] {
	return &c.SupportedAuthMethods
}

func (c *mqlMistralConnector) GetPrivateToolExecution() *plugin.TValue[bool] {
	return &c.PrivateToolExecution
}

func (c *mqlMistralConnector) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlMistralConnector) GetModifiedAt() *plugin.TValue[*time.Time] {
	return &c.ModifiedAt
}

// mqlMistralLibrary for the mistral.library resource
type mqlMistralLibrary struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlMistralLibraryInternal it will be used here
	Id          plugin.TValue[string]
	Name        plugin.TValue[string]
	Description plugin.TValue[string]
	NbDocuments plugin.TValue[int64]
	TotalSize   plugin.TValue[int64]
	OwnerType   plugin.TValue[string]
	OwnerId     plugin.TValue[string]
	CreatedAt   plugin.TValue[*time.Time]
	UpdatedAt   plugin.TValue[*time.Time]
	Accesses    plugin.TValue[[]any]
}

// createMistralLibrary creates a new instance of this resource
func createMistralLibrary(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlMistralLibrary{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("mistral.library", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlMistralLibrary) MqlName() string {
	return "mistral.library"
}

func (c *mqlMistralLibrary) MqlID() string {
	return c.__id
}

func (c *mqlMistralLibrary) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlMistralLibrary) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlMistralLibrary) GetDescription() *plugin.TValue[string] {
	return &c.Description
}

func (c *mqlMistralLibrary) GetNbDocuments() *plugin.TValue[int64] {
	return &c.NbDocuments
}

func (c *mqlMistralLibrary) GetTotalSize() *plugin.TValue[int64] {
	return &c.TotalSize
}

func (c *mqlMistralLibrary) GetOwnerType() *plugin.TValue[string] {
	return &c.OwnerType
}

func (c *mqlMistralLibrary) GetOwnerId() *plugin.TValue[string] {
	return &c.OwnerId
}

func (c *mqlMistralLibrary) GetCreatedAt() *plugin.TValue[*time.Time] {
	return &c.CreatedAt
}

func (c *mqlMistralLibrary) GetUpdatedAt() *plugin.TValue[*time.Time] {
	return &c.UpdatedAt
}

func (c *mqlMistralLibrary) GetAccesses() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Accesses, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("mistral.library", c.__id, "accesses")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.accesses()
	})
}

// mqlMistralLibraryAccess for the mistral.library.access resource
type mqlMistralLibraryAccess struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlMistralLibraryAccessInternal it will be used here
	ShareWithType plugin.TValue[string]
	ShareWithUuid plugin.TValue[string]
	Role          plugin.TValue[string]
}

// createMistralLibraryAccess creates a new instance of this resource
func createMistralLibraryAccess(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlMistralLibraryAccess{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("mistral.library.access", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlMistralLibraryAccess) MqlName() string {
	return "mistral.library.access"
}

func (c *mqlMistralLibraryAccess) MqlID() string {
	return c.__id
}

func (c *mqlMistralLibraryAccess) GetShareWithType() *plugin.TValue[string] {
	return &c.ShareWithType
}

func (c *mqlMistralLibraryAccess) GetShareWithUuid() *plugin.TValue[string] {
	return &c.ShareWithUuid
}

func (c *mqlMistralLibraryAccess) GetRole() *plugin.TValue[string] {
	return &c.Role
}
