// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.6
// source: llx.proto

package llx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorKind classifies a failure so that a consumer can act on it without
// parsing the message text (ADR 046). It lives here, in the lowest layer, so
// that Result can carry it: plugin.proto imports llx.proto, not the other way
// around.
//
// The HTTP status in each comment names the kind for a reader. Nothing maps a
// status onto a kind: a provider reads whatever its SDK hands it and decides.
// ERROR_KIND_UNSPECIFIED means unclassified, which is the honest default - a
// kind is a claim, and a provider that does not know makes none.
type ErrorKind int32

const (
	ErrorKind_ERROR_KIND_UNSPECIFIED ErrorKind = 0
	// The connection type was right and the content was not: this target is not
	// this provider's (ADR 045). Connect only.
	ErrorKind_ERROR_KIND_NO_MATCH ErrorKind = 1
	// 401. We are not who we need to be: no credentials, wrong credentials, an
	// expired or revoked token.
	ErrorKind_ERROR_KIND_UNAUTHENTICATED ErrorKind = 2
	// 403. We are authenticated and not permitted. Includes an OS elevation
	// failure: needing sudo and not having it is a permission we are asking for.
	ErrorKind_ERROR_KIND_FORBIDDEN ErrorKind = 3
	// 404. The provider could not answer because what it had to read is not
	// there. A legitimate absence is a null value, not this kind.
	ErrorKind_ERROR_KIND_NOT_FOUND ErrorKind = 4
	// 501. The question does not apply to this target: API not enabled, resource
	// provider not registered, feature not in this plan, service not offered in
	// this region, resource not supported on this platform.
	ErrorKind_ERROR_KIND_NOT_APPLICABLE ErrorKind = 5
	// 410. The API we call existed and does not any more.
	ErrorKind_ERROR_KIND_GONE ErrorKind = 6
	// 429. Throttled. Carries retry_after_ms when the target said so.
	ErrorKind_ERROR_KIND_TOO_MANY_REQUESTS ErrorKind = 7
	// 503. The target is temporarily not answering: 5xx, connection refused,
	// timeout, DNS failure.
	ErrorKind_ERROR_KIND_UNAVAILABLE ErrorKind = 8
	// The target answered and what it said cannot be read.
	ErrorKind_ERROR_KIND_MALFORMED_DATA ErrorKind = 9
	// The asset went away while we were scanning it.
	ErrorKind_ERROR_KIND_ASSET_VANISHED ErrorKind = 10
)

// Enum value maps for ErrorKind.
var (
	ErrorKind_name = map[int32]string{
		0:  "ERROR_KIND_UNSPECIFIED",
		1:  "ERROR_KIND_NO_MATCH",
		2:  "ERROR_KIND_UNAUTHENTICATED",
		3:  "ERROR_KIND_FORBIDDEN",
		4:  "ERROR_KIND_NOT_FOUND",
		5:  "ERROR_KIND_NOT_APPLICABLE",
		6:  "ERROR_KIND_GONE",
		7:  "ERROR_KIND_TOO_MANY_REQUESTS",
		8:  "ERROR_KIND_UNAVAILABLE",
		9:  "ERROR_KIND_MALFORMED_DATA",
		10: "ERROR_KIND_ASSET_VANISHED",
	}
	ErrorKind_value = map[string]int32{
		"ERROR_KIND_UNSPECIFIED":       0,
		"ERROR_KIND_NO_MATCH":          1,
		"ERROR_KIND_UNAUTHENTICATED":   2,
		"ERROR_KIND_FORBIDDEN":         3,
		"ERROR_KIND_NOT_FOUND":         4,
		"ERROR_KIND_NOT_APPLICABLE":    5,
		"ERROR_KIND_GONE":              6,
		"ERROR_KIND_TOO_MANY_REQUESTS": 7,
		"ERROR_KIND_UNAVAILABLE":       8,
		"ERROR_KIND_MALFORMED_DATA":    9,
		"ERROR_KIND_ASSET_VANISHED":    10,
	}
)

func (x ErrorKind) Enum() *ErrorKind {
	p := new(ErrorKind)
	*p = x
	return p
}

func (x ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_llx_proto_enumTypes[0].Descriptor()
}

func (ErrorKind) Type() protoreflect.EnumType {
	return &file_llx_proto_enumTypes[0]
}

func (x ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorKind.Descriptor instead.
func (ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{0}
}

// ErrorScope says how far a failure reaches, which is what lets a consumer
// aggregate identical failures and decide whether continuing is worthwhile.
type ErrorScope int32

const (
	ErrorScope_ERROR_SCOPE_UNSPECIFIED ErrorScope = 0
	// This one field.
	ErrorScope_ERROR_SCOPE_FIELD ErrorScope = 1
	// This resource, including any listing it would have produced.
	ErrorScope_ERROR_SCOPE_RESOURCE ErrorScope = 2
	// Everything in one region, project, or subscription, named by scope_id.
	ErrorScope_ERROR_SCOPE_PARTITION ErrorScope = 3
	// Every remaining call on this asset, e.g. an expired credential.
	ErrorScope_ERROR_SCOPE_ASSET ErrorScope = 4
)

// Enum value maps for ErrorScope.
var (
	ErrorScope_name = map[int32]string{
		0: "ERROR_SCOPE_UNSPECIFIED",
		1: "ERROR_SCOPE_FIELD",
		2: "ERROR_SCOPE_RESOURCE",
		3: "ERROR_SCOPE_PARTITION",
		4: "ERROR_SCOPE_ASSET",
	}
	ErrorScope_value = map[string]int32{
		"ERROR_SCOPE_UNSPECIFIED": 0,
		"ERROR_SCOPE_FIELD":       1,
		"ERROR_SCOPE_RESOURCE":    2,
		"ERROR_SCOPE_PARTITION":   3,
		"ERROR_SCOPE_ASSET":       4,
	}
)

func (x ErrorScope) Enum() *ErrorScope {
	p := new(ErrorScope)
	*p = x
	return p
}

func (x ErrorScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorScope) Descriptor() protoreflect.EnumDescriptor {
	return file_llx_proto_enumTypes[1].Descriptor()
}

func (ErrorScope) Type() protoreflect.EnumType {
	return &file_llx_proto_enumTypes[1]
}

func (x ErrorScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorScope.Descriptor instead.
func (ErrorScope) EnumDescriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{1}
}

// How this call behaves when it cannot resolve. See ADR 043 (strict mode).
// A link fails to resolve when its binding is null, or - for a map or dict -
// when the key it names is absent.
type Function_Nullability int32

const (
	// Non-strict: a link that cannot resolve yields null, as it always has.
	Function_NULLABILITY_UNSPECIFIED Function_Nullability = 0
	// Strict: a link that cannot resolve is an error. A binding that is a
	// short-circuited null (produced by an upstream NULLABILITY_OPTIONAL link)
	// still passes straight through.
	Function_NULLABILITY_REQUIRED Function_Nullability = 1
	// The author wrote `?` before this link. It never errors, and a null result
	// is marked short-circuited so the rest of the chain passes it through.
	Function_NULLABILITY_OPTIONAL Function_Nullability = 2
)

// Enum value maps for Function_Nullability.
var (
	Function_Nullability_name = map[int32]string{
		0: "NULLABILITY_UNSPECIFIED",
		1: "NULLABILITY_REQUIRED",
		2: "NULLABILITY_OPTIONAL",
	}
	Function_Nullability_value = map[string]int32{
		"NULLABILITY_UNSPECIFIED": 0,
		"NULLABILITY_REQUIRED":    1,
		"NULLABILITY_OPTIONAL":    2,
	}
)

func (x Function_Nullability) Enum() *Function_Nullability {
	p := new(Function_Nullability)
	*p = x
	return p
}

func (x Function_Nullability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Function_Nullability) Descriptor() protoreflect.EnumDescriptor {
	return file_llx_proto_enumTypes[2].Descriptor()
}

func (Function_Nullability) Type() protoreflect.EnumType {
	return &file_llx_proto_enumTypes[2]
}

func (x Function_Nullability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Function_Nullability.Descriptor instead.
func (Function_Nullability) EnumDescriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{2, 0}
}

// These values predate the CALL_ prefix rule and renaming them is a wire
// change, so it stays suppressed. Block form rather than `disable:next`:
// protolint takes the expected prefix from the preceding enum, so adding
// Function.Nullability above made a one-line suppression stop covering these.
// protolint:disable ENUM_FIELD_NAMES_PREFIX
type Chunk_Call int32

const (
	// protolint:disable:next ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
	Chunk_PRIMITIVE Chunk_Call = 0
	Chunk_FUNCTION  Chunk_Call = 1
	Chunk_PROPERTY  Chunk_Call = 2
)

// Enum value maps for Chunk_Call.
var (
	Chunk_Call_name = map[int32]string{
		0: "PRIMITIVE",
		1: "FUNCTION",
		2: "PROPERTY",
	}
	Chunk_Call_value = map[string]int32{
		"PRIMITIVE": 0,
		"FUNCTION":  1,
		"PROPERTY":  2,
	}
)

func (x Chunk_Call) Enum() *Chunk_Call {
	p := new(Chunk_Call)
	*p = x
	return p
}

func (x Chunk_Call) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chunk_Call) Descriptor() protoreflect.EnumDescriptor {
	return file_llx_proto_enumTypes[3].Descriptor()
}

func (Chunk_Call) Type() protoreflect.EnumType {
	return &file_llx_proto_enumTypes[3]
}

func (x Chunk_Call) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chunk_Call.Descriptor instead.
func (Chunk_Call) EnumDescriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{3, 0}
}

type Primitive struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The value of the primitive in case of bool|int|float|string|ref|json
	// For array/map it holds the exact datatype as a string,
	// e.g. []int or map[string]string
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// In case of an array primitive, holds the data of the array
	// protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
	Array []*Primitive `protobuf:"bytes,3,rep,name=array,proto3" json:"array,omitempty"`
	// In case of a map primitive, holds the data of the map
	Map           map[string]*Primitive `protobuf:"bytes,4,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Primitive) Reset() {
	*x = Primitive{}
	mi := &file_llx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Primitive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Primitive) ProtoMessage() {}

func (x *Primitive) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Primitive.ProtoReflect.Descriptor instead.
func (*Primitive) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{0}
}

func (x *Primitive) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Primitive) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Primitive) GetArray() []*Primitive {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *Primitive) GetMap() map[string]*Primitive {
	if x != nil {
		return x.Map
	}
	return nil
}

// AssetValue is the payload of the native `asset` primitive type. It points at
// another asset by the resource that anchors it in the current asset's resource
// tree: the anchor is `(resource_type, resource_id)`. The owning asset id is
// contextual (the caller knows which asset it is evaluating), so it is NOT part
// of this value. See ADR 030.
type AssetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetValue) Reset() {
	*x = AssetValue{}
	mi := &file_llx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetValue) ProtoMessage() {}

func (x *AssetValue) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetValue.ProtoReflect.Descriptor instead.
func (*AssetValue) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{1}
}

func (x *AssetValue) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AssetValue) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type Function struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Args  []*Primitive           `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// FIXME: this is a suggestion to allow function calls to be bound
	// to non-local references; Remove this comment or remove the feature
	Binding       uint64               `protobuf:"varint,4,opt,name=binding,proto3" json:"binding,omitempty"`
	Nullability   Function_Nullability `protobuf:"varint,5,opt,name=nullability,proto3,enum=mql.llx.Function_Nullability" json:"nullability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_llx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{2}
}

func (x *Function) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Function) GetArgs() []*Primitive {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Function) GetBinding() uint64 {
	if x != nil {
		return x.Binding
	}
	return 0
}

func (x *Function) GetNullability() Function_Nullability {
	if x != nil {
		return x.Nullability
	}
	return Function_NULLABILITY_UNSPECIFIED
}

type Chunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protolint:enable ENUM_FIELD_NAMES_PREFIX
	Call          Chunk_Call `protobuf:"varint,1,opt,name=call,proto3,enum=mql.llx.Chunk_Call" json:"call,omitempty"`
	Id            string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Primitive     *Primitive `protobuf:"bytes,3,opt,name=primitive,proto3" json:"primitive,omitempty"`
	Function      *Function  `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_llx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetCall() Chunk_Call {
	if x != nil {
		return x.Call
	}
	return Chunk_PRIMITIVE
}

func (x *Chunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chunk) GetPrimitive() *Primitive {
	if x != nil {
		return x.Primitive
	}
	return nil
}

func (x *Chunk) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type AssertionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Refs          []uint64               `protobuf:"varint,2,rep,packed,name=refs,proto3" json:"refs,omitempty"`
	Checksums     []string               `protobuf:"bytes,3,rep,name=checksums,proto3" json:"checksums,omitempty"`
	DecodeBlock   bool                   `protobuf:"varint,21,opt,name=decode_block,json=decodeBlock,proto3" json:"decode_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertionMessage) Reset() {
	*x = AssertionMessage{}
	mi := &file_llx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertionMessage) ProtoMessage() {}

func (x *AssertionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertionMessage.ProtoReflect.Descriptor instead.
func (*AssertionMessage) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{4}
}

func (x *AssertionMessage) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *AssertionMessage) GetRefs() []uint64 {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *AssertionMessage) GetChecksums() []string {
	if x != nil {
		return x.Checksums
	}
	return nil
}

func (x *AssertionMessage) GetDecodeBlock() bool {
	if x != nil {
		return x.DecodeBlock
	}
	return false
}

type CodeV1 struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code        []*Chunk               `protobuf:"bytes,2,rep,name=code,proto3" json:"code,omitempty"`
	Parameters  int32                  `protobuf:"varint,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Entrypoints []int32                `protobuf:"varint,4,rep,packed,name=entrypoints,proto3" json:"entrypoints,omitempty"`
	Datapoints  []int32                `protobuf:"varint,5,rep,packed,name=datapoints,proto3" json:"datapoints,omitempty"`
	Checksums   map[int32]string       `protobuf:"bytes,6,rep,name=checksums,proto3" json:"checksums,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Functions   []*CodeV1              `protobuf:"bytes,7,rep,name=functions,proto3" json:"functions,omitempty"`
	// protolint:disable:next FIELD_NAMES_LOWER_SNAKE_CASE
	SingleValue   bool                        `protobuf:"varint,8,opt,name=singleValue,proto3" json:"singleValue,omitempty"`
	Assertions    map[int32]*AssertionMessage `protobuf:"bytes,20,rep,name=assertions,proto3" json:"assertions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeV1) Reset() {
	*x = CodeV1{}
	mi := &file_llx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeV1) ProtoMessage() {}

func (x *CodeV1) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeV1.ProtoReflect.Descriptor instead.
func (*CodeV1) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{5}
}

func (x *CodeV1) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CodeV1) GetCode() []*Chunk {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *CodeV1) GetParameters() int32 {
	if x != nil {
		return x.Parameters
	}
	return 0
}

func (x *CodeV1) GetEntrypoints() []int32 {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

func (x *CodeV1) GetDatapoints() []int32 {
	if x != nil {
		return x.Datapoints
	}
	return nil
}

func (x *CodeV1) GetChecksums() map[int32]string {
	if x != nil {
		return x.Checksums
	}
	return nil
}

func (x *CodeV1) GetFunctions() []*CodeV1 {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *CodeV1) GetSingleValue() bool {
	if x != nil {
		return x.SingleValue
	}
	return false
}

func (x *CodeV1) GetAssertions() map[int32]*AssertionMessage {
	if x != nil {
		return x.Assertions
	}
	return nil
}

type Block struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Chunks []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// Identifies if we return multiple or just a single value.
	// The difference is that blocks usually return the block type (a kind of map)
	// where this flag instructs it to just return the value instead.
	// protolint:disable:next FIELD_NAMES_LOWER_SNAKE_CASE
	SingleValue bool `protobuf:"varint,2,opt,name=singleValue,proto3" json:"singleValue,omitempty"`
	// Number of parameters that are directly provided to this block
	Parameters    int32    `protobuf:"varint,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Entrypoints   []uint64 `protobuf:"varint,4,rep,packed,name=entrypoints,proto3" json:"entrypoints,omitempty"`
	Datapoints    []uint64 `protobuf:"varint,5,rep,packed,name=datapoints,proto3" json:"datapoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_llx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{6}
}

func (x *Block) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *Block) GetSingleValue() bool {
	if x != nil {
		return x.SingleValue
	}
	return false
}

func (x *Block) GetParameters() int32 {
	if x != nil {
		return x.Parameters
	}
	return 0
}

func (x *Block) GetEntrypoints() []uint64 {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

func (x *Block) GetDatapoints() []uint64 {
	if x != nil {
		return x.Datapoints
	}
	return nil
}

type CodeV2 struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Id            string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Blocks        []*Block                     `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Checksums     map[uint64]string            `protobuf:"bytes,5,rep,name=checksums,proto3" json:"checksums,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Assertions    map[uint64]*AssertionMessage `protobuf:"bytes,20,rep,name=assertions,proto3" json:"assertions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeV2) Reset() {
	*x = CodeV2{}
	mi := &file_llx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeV2) ProtoMessage() {}

func (x *CodeV2) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeV2.ProtoReflect.Descriptor instead.
func (*CodeV2) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{7}
}

func (x *CodeV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CodeV2) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *CodeV2) GetChecksums() map[uint64]string {
	if x != nil {
		return x.Checksums
	}
	return nil
}

func (x *CodeV2) GetAssertions() map[uint64]*AssertionMessage {
	if x != nil {
		return x.Assertions
	}
	return nil
}

type Labels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Labels) Reset() {
	*x = Labels{}
	mi := &file_llx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Labels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Labels) ProtoMessage() {}

func (x *Labels) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Labels.ProtoReflect.Descriptor instead.
func (*Labels) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{8}
}

func (x *Labels) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Documentation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Documentation) Reset() {
	*x = Documentation{}
	mi := &file_llx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Documentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Documentation) ProtoMessage() {}

func (x *Documentation) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Documentation.ProtoReflect.Descriptor instead.
func (*Documentation) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{9}
}

func (x *Documentation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Documentation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Documentation) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Documentation) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type CodeBundle struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	CodeV2           *CodeV2                      `protobuf:"bytes,6,opt,name=code_v2,json=codeV2,proto3" json:"code_v2,omitempty"`
	Suggestions      []*Documentation             `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	Source           string                       `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Labels           *Labels                      `protobuf:"bytes,4,opt,name=labels,proto3" json:"labels,omitempty"`
	Props            map[string]string            `protobuf:"bytes,5,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // name + type
	Version          string                       `protobuf:"bytes,20,opt,name=version,proto3" json:"version,omitempty"`
	MinMondooVersion string                       `protobuf:"bytes,22,opt,name=min_mondoo_version,json=minMondooVersion,proto3" json:"min_mondoo_version,omitempty"`
	Assertions       map[string]*AssertionMessage `protobuf:"bytes,23,rep,name=assertions,proto3" json:"assertions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// name + ref to the block of data
	AutoExpand map[string]uint64 `protobuf:"bytes,24,rep,name=auto_expand,json=autoExpand,proto3" json:"auto_expand,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// ref + variable name; only used during label creation and discarded
	// afterwards
	Vars map[uint64]string `protobuf:"bytes,25,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Writer-schema identity (ADR 040 part 1): the version of every provider
	// whose schema this bundle was compiled against, keyed by the stable
	// provider name ("aws", "os") rather than by its module-path id, so the key
	// survives an id migration.
	//
	// This says what the compiler *saw*. It is provenance, not a requirement -
	// use min_provider_versions to decide whether a reader can execute the
	// bundle.
	ProviderSchemas map[string]string `protobuf:"bytes,26,rep,name=provider_schemas,json=providerSchemas,proto3" json:"provider_schemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Minimum version of each provider required to execute this bundle, keyed by
	// the stable provider name.
	//
	// Derived at compile time as the highest `min_provider_version` over every
	// resource and field the bundle actually touches, so it is a real
	// requirement rather than a snapshot of the compiling machine. A reader whose
	// provider is older than this cannot resolve every name in the bundle, and
	// should say so instead of degrading the missing ones to null.
	MinProviderVersions map[string]string `protobuf:"bytes,27,rep,name=min_provider_versions,json=minProviderVersions,proto3" json:"min_provider_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Downgrade translations (ADR 040 part 6).
	//
	// Each entry says: a reader whose `provider` is older than `below_version`
	// cannot make the call at `ref`, and should run the block at `block_ref`
	// instead. The blocks themselves ship inside code_v2 as ordinary blocks with
	// their checksums already in place; nothing points at them until a patch
	// does, so a current reader carries them as unreachable weight and executes
	// pristine code.
	//
	// Patching rewrites one chunk in place and never touches the checksum map, so
	// a downgraded reader reports under exactly the checksums the producer
	// shipped and scoring does not fork across versions.
	Translations []*TranslationRef `protobuf:"bytes,28,rep,name=translations,proto3" json:"translations,omitempty"`
	// Resources this bundle reached through the global namespace that do not hang
	// off an asset root and are not marked `@global` (ADR 031 point 7).
	//
	// In v14 a bare name resolves globally first and falls back to the asset
	// root, so both spellings work. In v15 the root is the namespace, and a name
	// that is neither rooted nor global stops resolving. This list is what makes
	// cutover measurable: it is the set of names in this bundle that have no home
	// in the asset's tree, recorded rather than logged so tooling can show which
	// parts of a bundle reach outside it.
	//
	// Empty when every name resolved is either rooted or marked global, which is
	// the state a fully migrated provider produces.
	UnrootedResources []string `protobuf:"bytes,29,rep,name=unrooted_resources,json=unrootedResources,proto3" json:"unrooted_resources,omitempty"`
	// The asset root this bundle was compiled against (ADR 031), empty when it
	// was compiled without one. Provenance - what the query was bounded by - and
	// what lets a reader tell the chunks the compiler inserted to reach the root
	// from the ones the author wrote.
	AssetRoot string `protobuf:"bytes,30,opt,name=asset_root,json=assetRoot,proto3" json:"asset_root,omitempty"`
	// The asset roots that can execute this bundle (ADR 031), narrowed from what
	// it touched: a query reading only universal members is satisfied by every
	// root, one reading `iptables` only by the Linux root and the union above it.
	//
	// Empty means no requirement was derived - nothing was reached through a
	// root, which is every bundle compiled before this existed and every one that
	// only uses the global namespace. A reader treats empty as "runs anywhere".
	//
	// This is applicability derived from the query rather than declared beside
	// it: the same job a hand-written platform filter does today, computed from
	// what the code actually reads.
	CompatibleRoots []string `protobuf:"bytes,31,rep,name=compatible_roots,json=compatibleRoots,proto3" json:"compatible_roots,omitempty"`
	// Names this bundle uses that are deprecated and say where they moved to
	// (ADR 040). Recorded, never logged: the compiler is called per keystroke by
	// autocomplete, so the decision to show a notice belongs to whoever is
	// driving it.
	//
	// Only uses with a `@replaced_by` target land here. A deprecation with no
	// destination has nothing actionable to tell a user, so it stays silent.
	DeprecatedUses []*DeprecatedUse `protobuf:"bytes,32,rep,name=deprecated_uses,json=deprecatedUses,proto3" json:"deprecated_uses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CodeBundle) Reset() {
	*x = CodeBundle{}
	mi := &file_llx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeBundle) ProtoMessage() {}

func (x *CodeBundle) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeBundle.ProtoReflect.Descriptor instead.
func (*CodeBundle) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{10}
}

func (x *CodeBundle) GetCodeV2() *CodeV2 {
	if x != nil {
		return x.CodeV2
	}
	return nil
}

func (x *CodeBundle) GetSuggestions() []*Documentation {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *CodeBundle) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CodeBundle) GetLabels() *Labels {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CodeBundle) GetProps() map[string]string {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *CodeBundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CodeBundle) GetMinMondooVersion() string {
	if x != nil {
		return x.MinMondooVersion
	}
	return ""
}

func (x *CodeBundle) GetAssertions() map[string]*AssertionMessage {
	if x != nil {
		return x.Assertions
	}
	return nil
}

func (x *CodeBundle) GetAutoExpand() map[string]uint64 {
	if x != nil {
		return x.AutoExpand
	}
	return nil
}

func (x *CodeBundle) GetVars() map[uint64]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *CodeBundle) GetProviderSchemas() map[string]string {
	if x != nil {
		return x.ProviderSchemas
	}
	return nil
}

func (x *CodeBundle) GetMinProviderVersions() map[string]string {
	if x != nil {
		return x.MinProviderVersions
	}
	return nil
}

func (x *CodeBundle) GetTranslations() []*TranslationRef {
	if x != nil {
		return x.Translations
	}
	return nil
}

func (x *CodeBundle) GetUnrootedResources() []string {
	if x != nil {
		return x.UnrootedResources
	}
	return nil
}

func (x *CodeBundle) GetAssetRoot() string {
	if x != nil {
		return x.AssetRoot
	}
	return ""
}

func (x *CodeBundle) GetCompatibleRoots() []string {
	if x != nil {
		return x.CompatibleRoots
	}
	return nil
}

func (x *CodeBundle) GetDeprecatedUses() []*DeprecatedUse {
	if x != nil {
		return x.DeprecatedUses
	}
	return nil
}

// DeprecatedUse is one deprecated name a bundle reads, and its replacement.
type DeprecatedUse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The deprecated name as it exists in the schema, e.g. `os.hostname`.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Where it moved to, as a full schema path, e.g. `os.base.hostname`. What a
	// user is shown is rendered from this against the root the query compiled
	// with, so the same entry reads as `hostname` in a rooted shell and as
	// `os.base.hostname` where there is no root to shorten it against.
	To            string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprecatedUse) Reset() {
	*x = DeprecatedUse{}
	mi := &file_llx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecatedUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecatedUse) ProtoMessage() {}

func (x *DeprecatedUse) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecatedUse.ProtoReflect.Descriptor instead.
func (*DeprecatedUse) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{11}
}

func (x *DeprecatedUse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DeprecatedUse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// TranslationRef points one call that an older reader cannot make at a block
// that computes the same value out of vocabulary it does have.
type TranslationRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ref of the chunk in code_v2 to replace.
	Ref uint64 `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Provider id whose version decides whether this applies.
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// Readers older than this need the translation. It is the version that
	// introduced the change being compensated for.
	BelowVersion string `protobuf:"bytes,3,opt,name=below_version,json=belowVersion,proto3" json:"below_version,omitempty"`
	// Block ref computing the replacement. It is bound to the replaced chunk's
	// own binding - the parent - because the field being replaced may not exist
	// on the reader at all, so there is no old value to transform.
	BlockRef      uint64 `protobuf:"varint,4,opt,name=block_ref,json=blockRef,proto3" json:"block_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationRef) Reset() {
	*x = TranslationRef{}
	mi := &file_llx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationRef) ProtoMessage() {}

func (x *TranslationRef) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationRef.ProtoReflect.Descriptor instead.
func (*TranslationRef) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{12}
}

func (x *TranslationRef) GetRef() uint64 {
	if x != nil {
		return x.Ref
	}
	return 0
}

func (x *TranslationRef) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TranslationRef) GetBelowVersion() string {
	if x != nil {
		return x.BelowVersion
	}
	return ""
}

func (x *TranslationRef) GetBlockRef() uint64 {
	if x != nil {
		return x.BlockRef
	}
	return 0
}

// ErrorDetail carries a kind and what a consumer needs to act on it. It rides
// beside the error message rather than replacing it: the message keeps the
// target's own words verbatim, which is what a human reads when the kind is not
// enough.
type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  ErrorKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=mql.llx.ErrorKind" json:"kind,omitempty"`
	Scope ErrorScope             `protobuf:"varint,2,opt,name=scope,proto3,enum=mql.llx.ErrorScope" json:"scope,omitempty"`
	// Names the partition for ERROR_SCOPE_PARTITION: a region, project, or
	// subscription. Empty for every other scope.
	ScopeId string `protobuf:"bytes,3,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	// Permissions the refused call needed, e.g. "ec2:DescribeInstances", or the
	// elevation an OS scan lacked. Possibly several, possibly none.
	Permissions []string `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Server-stated wait for 429 and 503. Zero means "no hint", not "retry now".
	// Carried, not acted on: nothing in mql retries on it.
	RetryAfterMs  int64 `protobuf:"varint,5,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_llx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{13}
}

func (x *ErrorDetail) GetKind() ErrorKind {
	if x != nil {
		return x.Kind
	}
	return ErrorKind_ERROR_KIND_UNSPECIFIED
}

func (x *ErrorDetail) GetScope() ErrorScope {
	if x != nil {
		return x.Scope
	}
	return ErrorScope_ERROR_SCOPE_UNSPECIFIED
}

func (x *ErrorDetail) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *ErrorDetail) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ErrorDetail) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

// A part of a result that could not be read (ADR 046 §8). The message is the
// upstream error, verbatim; the detail classifies it and names the partition.
type CoverageGap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Detail        *ErrorDetail           `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverageGap) Reset() {
	*x = CoverageGap{}
	mi := &file_llx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverageGap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverageGap) ProtoMessage() {}

func (x *CoverageGap) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverageGap.ProtoReflect.Descriptor instead.
func (*CoverageGap) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{14}
}

func (x *CoverageGap) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CoverageGap) GetDetail() *ErrorDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type Result struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Data   *Primitive             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error  string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	CodeId string                 `protobuf:"bytes,3,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	// Why this result failed, when the provider or the runtime could say (ADR
	// 046). Absent means unclassified, which is also what every result written
	// before this field existed carries.
	ErrorDetail *ErrorDetail `protobuf:"bytes,4,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	// The value in data is incomplete: these parts could not be read. Empty on
	// every complete result. It never means the result failed; that is error.
	CoverageGaps  []*CoverageGap `protobuf:"bytes,5,rep,name=coverage_gaps,json=coverageGaps,proto3" json:"coverage_gaps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_llx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{15}
}

func (x *Result) GetData() *Primitive {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Result) GetCodeId() string {
	if x != nil {
		return x.CodeId
	}
	return ""
}

func (x *Result) GetErrorDetail() *ErrorDetail {
	if x != nil {
		return x.ErrorDetail
	}
	return nil
}

func (x *Result) GetCoverageGaps() []*CoverageGap {
	if x != nil {
		return x.CoverageGaps
	}
	return nil
}

type ResourceRecording struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Fields        map[string]*Result     `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Created       int64                  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated       int64                  `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRecording) Reset() {
	*x = ResourceRecording{}
	mi := &file_llx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRecording) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRecording) ProtoMessage() {}

func (x *ResourceRecording) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRecording.ProtoReflect.Descriptor instead.
func (*ResourceRecording) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{16}
}

func (x *ResourceRecording) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ResourceRecording) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceRecording) GetFields() map[string]*Result {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ResourceRecording) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ResourceRecording) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type Rating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // can either be the collection or the query
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Tests         int32                  `protobuf:"varint,3,opt,name=tests,proto3" json:"tests,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Trend         int32                  `protobuf:"varint,5,opt,name=trend,proto3" json:"trend,omitempty"`
	Date          string                 `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rating) Reset() {
	*x = Rating{}
	mi := &file_llx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{17}
}

func (x *Rating) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rating) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Rating) GetTests() int32 {
	if x != nil {
		return x.Tests
	}
	return 0
}

func (x *Rating) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Rating) GetTrend() int32 {
	if x != nil {
		return x.Trend
	}
	return 0
}

func (x *Rating) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type AssessmentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Entrypoint    uint64                 `protobuf:"varint,3,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Ref           uint64                 `protobuf:"varint,9,opt,name=ref,proto3" json:"ref,omitempty"`
	Expected      *Primitive             `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	Actual        *Primitive             `protobuf:"bytes,5,opt,name=actual,proto3" json:"actual,omitempty"`
	Operation     string                 `protobuf:"bytes,6,opt,name=operation,proto3" json:"operation,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	IsAssertion   bool                   `protobuf:"varint,8,opt,name=is_assertion,json=isAssertion,proto3" json:"is_assertion,omitempty"`
	Template      string                 `protobuf:"bytes,20,opt,name=template,proto3" json:"template,omitempty"`
	Data          []*Primitive           `protobuf:"bytes,21,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentItem) Reset() {
	*x = AssessmentItem{}
	mi := &file_llx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentItem) ProtoMessage() {}

func (x *AssessmentItem) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentItem.ProtoReflect.Descriptor instead.
func (*AssessmentItem) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{18}
}

func (x *AssessmentItem) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssessmentItem) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *AssessmentItem) GetEntrypoint() uint64 {
	if x != nil {
		return x.Entrypoint
	}
	return 0
}

func (x *AssessmentItem) GetRef() uint64 {
	if x != nil {
		return x.Ref
	}
	return 0
}

func (x *AssessmentItem) GetExpected() *Primitive {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *AssessmentItem) GetActual() *Primitive {
	if x != nil {
		return x.Actual
	}
	return nil
}

func (x *AssessmentItem) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *AssessmentItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AssessmentItem) GetIsAssertion() bool {
	if x != nil {
		return x.IsAssertion
	}
	return false
}

func (x *AssessmentItem) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *AssessmentItem) GetData() []*Primitive {
	if x != nil {
		return x.Data
	}
	return nil
}

type Assessment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      string                 `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	IsAssertion   bool                   `protobuf:"varint,3,opt,name=is_assertion,json=isAssertion,proto3" json:"is_assertion,omitempty"`
	Results       []*AssessmentItem      `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assessment) Reset() {
	*x = Assessment{}
	mi := &file_llx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assessment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assessment) ProtoMessage() {}

func (x *Assessment) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assessment.ProtoReflect.Descriptor instead.
func (*Assessment) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{19}
}

func (x *Assessment) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Assessment) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Assessment) GetIsAssertion() bool {
	if x != nil {
		return x.IsAssertion
	}
	return false
}

func (x *Assessment) GetResults() []*AssessmentItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type IP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	HasPrefix     bool                   `protobuf:"varint,2,opt,name=has_prefix,json=hasPrefix,proto3" json:"has_prefix,omitempty"`
	PrefixLength  int32                  `protobuf:"varint,3,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IP) Reset() {
	*x = IP{}
	mi := &file_llx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IP) ProtoMessage() {}

func (x *IP) ProtoReflect() protoreflect.Message {
	mi := &file_llx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IP.ProtoReflect.Descriptor instead.
func (*IP) Descriptor() ([]byte, []int) {
	return file_llx_proto_rawDescGZIP(), []int{20}
}

func (x *IP) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *IP) GetHasPrefix() bool {
	if x != nil {
		return x.HasPrefix
	}
	return false
}

func (x *IP) GetPrefixLength() int32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

var File_llx_proto protoreflect.FileDescriptor

const file_llx_proto_rawDesc = "" +
	"\n" +
	"\tllx.proto\x12\amql.llx\"\xda\x01\n" +
	"\tPrimitive\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12(\n" +
	"\x05array\x18\x03 \x03(\v2\x12.mql.llx.PrimitiveR\x05array\x12-\n" +
	"\x03map\x18\x04 \x03(\v2\x1b.mql.llx.Primitive.MapEntryR\x03map\x1aJ\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.mql.llx.PrimitiveR\x05value:\x028\x01\"R\n" +
	"\n" +
	"AssetValue\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\"\x81\x02\n" +
	"\bFunction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12&\n" +
	"\x04args\x18\x03 \x03(\v2\x12.mql.llx.PrimitiveR\x04args\x12\x18\n" +
	"\abinding\x18\x04 \x01(\x04R\abinding\x12?\n" +
	"\vnullability\x18\x05 \x01(\x0e2\x1d.mql.llx.Function.NullabilityR\vnullability\"^\n" +
	"\vNullability\x12\x1b\n" +
	"\x17NULLABILITY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14NULLABILITY_REQUIRED\x10\x01\x12\x18\n" +
	"\x14NULLABILITY_OPTIONAL\x10\x02\"\xd4\x01\n" +
	"\x05Chunk\x12'\n" +
	"\x04call\x18\x01 \x01(\x0e2\x13.mql.llx.Chunk.CallR\x04call\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x120\n" +
	"\tprimitive\x18\x03 \x01(\v2\x12.mql.llx.PrimitiveR\tprimitive\x12-\n" +
	"\bfunction\x18\x04 \x01(\v2\x11.mql.llx.FunctionR\bfunction\"1\n" +
	"\x04Call\x12\r\n" +
	"\tPRIMITIVE\x10\x00\x12\f\n" +
	"\bFUNCTION\x10\x01\x12\f\n" +
	"\bPROPERTY\x10\x02\"\x83\x01\n" +
	"\x10AssertionMessage\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12\x12\n" +
	"\x04refs\x18\x02 \x03(\x04R\x04refs\x12\x1c\n" +
	"\tchecksums\x18\x03 \x03(\tR\tchecksums\x12!\n" +
	"\fdecode_block\x18\x15 \x01(\bR\vdecodeBlock\"\x86\x04\n" +
	"\x06CodeV1\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\x04code\x18\x02 \x03(\v2\x0e.mql.llx.ChunkR\x04code\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\x05R\n" +
	"parameters\x12 \n" +
	"\ventrypoints\x18\x04 \x03(\x05R\ventrypoints\x12\x1e\n" +
	"\n" +
	"datapoints\x18\x05 \x03(\x05R\n" +
	"datapoints\x12<\n" +
	"\tchecksums\x18\x06 \x03(\v2\x1e.mql.llx.CodeV1.ChecksumsEntryR\tchecksums\x12-\n" +
	"\tfunctions\x18\a \x03(\v2\x0f.mql.llx.CodeV1R\tfunctions\x12 \n" +
	"\vsingleValue\x18\b \x01(\bR\vsingleValue\x12?\n" +
	"\n" +
	"assertions\x18\x14 \x03(\v2\x1f.mql.llx.CodeV1.AssertionsEntryR\n" +
	"assertions\x1a<\n" +
	"\x0eChecksumsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aX\n" +
	"\x0fAssertionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.mql.llx.AssertionMessageR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x05Block\x12&\n" +
	"\x06chunks\x18\x01 \x03(\v2\x0e.mql.llx.ChunkR\x06chunks\x12 \n" +
	"\vsingleValue\x18\x02 \x01(\bR\vsingleValue\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\x05R\n" +
	"parameters\x12 \n" +
	"\ventrypoints\x18\x04 \x03(\x04R\ventrypoints\x12\x1e\n" +
	"\n" +
	"datapoints\x18\x05 \x03(\x04R\n" +
	"datapoints\"\xd7\x02\n" +
	"\x06CodeV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x06blocks\x18\x02 \x03(\v2\x0e.mql.llx.BlockR\x06blocks\x12<\n" +
	"\tchecksums\x18\x05 \x03(\v2\x1e.mql.llx.CodeV2.ChecksumsEntryR\tchecksums\x12?\n" +
	"\n" +
	"assertions\x18\x14 \x03(\v2\x1f.mql.llx.CodeV2.AssertionsEntryR\n" +
	"assertions\x1a<\n" +
	"\x0eChecksumsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aX\n" +
	"\x0fAssertionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.mql.llx.AssertionMessageR\x05value:\x028\x01\"x\n" +
	"\x06Labels\x123\n" +
	"\x06labels\x18\x01 \x03(\v2\x1b.mql.llx.Labels.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\rDocumentation\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\"\xbf\n" +
	"\n" +
	"\n" +
	"CodeBundle\x12(\n" +
	"\acode_v2\x18\x06 \x01(\v2\x0f.mql.llx.CodeV2R\x06codeV2\x128\n" +
	"\vsuggestions\x18\x02 \x03(\v2\x16.mql.llx.DocumentationR\vsuggestions\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12'\n" +
	"\x06labels\x18\x04 \x01(\v2\x0f.mql.llx.LabelsR\x06labels\x124\n" +
	"\x05props\x18\x05 \x03(\v2\x1e.mql.llx.CodeBundle.PropsEntryR\x05props\x12\x18\n" +
	"\aversion\x18\x14 \x01(\tR\aversion\x12,\n" +
	"\x12min_mondoo_version\x18\x16 \x01(\tR\x10minMondooVersion\x12C\n" +
	"\n" +
	"assertions\x18\x17 \x03(\v2#.mql.llx.CodeBundle.AssertionsEntryR\n" +
	"assertions\x12D\n" +
	"\vauto_expand\x18\x18 \x03(\v2#.mql.llx.CodeBundle.AutoExpandEntryR\n" +
	"autoExpand\x121\n" +
	"\x04vars\x18\x19 \x03(\v2\x1d.mql.llx.CodeBundle.VarsEntryR\x04vars\x12S\n" +
	"\x10provider_schemas\x18\x1a \x03(\v2(.mql.llx.CodeBundle.ProviderSchemasEntryR\x0fproviderSchemas\x12`\n" +
	"\x15min_provider_versions\x18\x1b \x03(\v2,.mql.llx.CodeBundle.MinProviderVersionsEntryR\x13minProviderVersions\x12;\n" +
	"\ftranslations\x18\x1c \x03(\v2\x17.mql.llx.TranslationRefR\ftranslations\x12-\n" +
	"\x12unrooted_resources\x18\x1d \x03(\tR\x11unrootedResources\x12\x1d\n" +
	"\n" +
	"asset_root\x18\x1e \x01(\tR\tassetRoot\x12)\n" +
	"\x10compatible_roots\x18\x1f \x03(\tR\x0fcompatibleRoots\x12?\n" +
	"\x0fdeprecated_uses\x18  \x03(\v2\x16.mql.llx.DeprecatedUseR\x0edeprecatedUses\x1a8\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aX\n" +
	"\x0fAssertionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.mql.llx.AssertionMessageR\x05value:\x028\x01\x1a=\n" +
	"\x0fAutoExpandEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ProviderSchemasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aF\n" +
	"\x18MinProviderVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02J\x04\b\x15\x10\x16\"3\n" +
	"\rDeprecatedUse\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\x80\x01\n" +
	"\x0eTranslationRef\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\x04R\x03ref\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12#\n" +
	"\rbelow_version\x18\x03 \x01(\tR\fbelowVersion\x12\x1b\n" +
	"\tblock_ref\x18\x04 \x01(\x04R\bblockRef\"\xc3\x01\n" +
	"\vErrorDetail\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.mql.llx.ErrorKindR\x04kind\x12)\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x13.mql.llx.ErrorScopeR\x05scope\x12\x19\n" +
	"\bscope_id\x18\x03 \x01(\tR\ascopeId\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x12$\n" +
	"\x0eretry_after_ms\x18\x05 \x01(\x03R\fretryAfterMs\"Q\n" +
	"\vCoverageGap\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12,\n" +
	"\x06detail\x18\x02 \x01(\v2\x14.mql.llx.ErrorDetailR\x06detail\"\xd3\x01\n" +
	"\x06Result\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.mql.llx.PrimitiveR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x17\n" +
	"\acode_id\x18\x03 \x01(\tR\x06codeId\x127\n" +
	"\ferror_detail\x18\x04 \x01(\v2\x14.mql.llx.ErrorDetailR\verrorDetail\x129\n" +
	"\rcoverage_gaps\x18\x05 \x03(\v2\x14.mql.llx.CoverageGapR\fcoverageGaps\"\xff\x01\n" +
	"\x11ResourceRecording\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12>\n" +
	"\x06fields\x18\x03 \x03(\v2&.mql.llx.ResourceRecording.FieldsEntryR\x06fields\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x03R\acreated\x12\x18\n" +
	"\aupdated\x18\x05 \x01(\x03R\aupdated\x1aJ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.mql.llx.ResultR\x05value:\x028\x01\"\x8a\x01\n" +
	"\x06Rating\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05tests\x18\x03 \x01(\x05R\x05tests\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x14\n" +
	"\x05trend\x18\x05 \x01(\x05R\x05trend\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\"\xef\x02\n" +
	"\x0eAssessmentItem\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x03 \x01(\x04R\n" +
	"entrypoint\x12\x10\n" +
	"\x03ref\x18\t \x01(\x04R\x03ref\x12.\n" +
	"\bexpected\x18\x04 \x01(\v2\x12.mql.llx.PrimitiveR\bexpected\x12*\n" +
	"\x06actual\x18\x05 \x01(\v2\x12.mql.llx.PrimitiveR\x06actual\x12\x1c\n" +
	"\toperation\x18\x06 \x01(\tR\toperation\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12!\n" +
	"\fis_assertion\x18\b \x01(\bR\visAssertion\x12\x1a\n" +
	"\btemplate\x18\x14 \x01(\tR\btemplate\x12&\n" +
	"\x04data\x18\x15 \x03(\v2\x12.mql.llx.PrimitiveR\x04data\"\x98\x01\n" +
	"\n" +
	"Assessment\x12\x1a\n" +
	"\bchecksum\x18\x01 \x01(\tR\bchecksum\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\fis_assertion\x18\x03 \x01(\bR\visAssertion\x121\n" +
	"\aresults\x18\x04 \x03(\v2\x17.mql.llx.AssessmentItemR\aresults\"b\n" +
	"\x02IP\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x1d\n" +
	"\n" +
	"has_prefix\x18\x02 \x01(\bR\thasPrefix\x12#\n" +
	"\rprefix_length\x18\x03 \x01(\x05R\fprefixLength*\xc4\x02\n" +
	"\tErrorKind\x12\x1a\n" +
	"\x16ERROR_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ERROR_KIND_NO_MATCH\x10\x01\x12\x1e\n" +
	"\x1aERROR_KIND_UNAUTHENTICATED\x10\x02\x12\x18\n" +
	"\x14ERROR_KIND_FORBIDDEN\x10\x03\x12\x18\n" +
	"\x14ERROR_KIND_NOT_FOUND\x10\x04\x12\x1d\n" +
	"\x19ERROR_KIND_NOT_APPLICABLE\x10\x05\x12\x13\n" +
	"\x0fERROR_KIND_GONE\x10\x06\x12 \n" +
	"\x1cERROR_KIND_TOO_MANY_REQUESTS\x10\a\x12\x1a\n" +
	"\x16ERROR_KIND_UNAVAILABLE\x10\b\x12\x1d\n" +
	"\x19ERROR_KIND_MALFORMED_DATA\x10\t\x12\x1d\n" +
	"\x19ERROR_KIND_ASSET_VANISHED\x10\n" +
	"*\x8c\x01\n" +
	"\n" +
	"ErrorScope\x12\x1b\n" +
	"\x17ERROR_SCOPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ERROR_SCOPE_FIELD\x10\x01\x12\x18\n" +
	"\x14ERROR_SCOPE_RESOURCE\x10\x02\x12\x19\n" +
	"\x15ERROR_SCOPE_PARTITION\x10\x03\x12\x15\n" +
	"\x11ERROR_SCOPE_ASSET\x10\x04B\x17Z\x15go.mondoo.com/mql/llxb\x06proto3"

var (
	file_llx_proto_rawDescOnce sync.Once
	file_llx_proto_rawDescData []byte
)

func file_llx_proto_rawDescGZIP() []byte {
	file_llx_proto_rawDescOnce.Do(func() {
		file_llx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llx_proto_rawDesc), len(file_llx_proto_rawDesc)))
	})
	return file_llx_proto_rawDescData
}

var file_llx_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_llx_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_llx_proto_goTypes = []any{
	(ErrorKind)(0),            // 0: mql.llx.ErrorKind
	(ErrorScope)(0),           // 1: mql.llx.ErrorScope
	(Function_Nullability)(0), // 2: mql.llx.Function.Nullability
	(Chunk_Call)(0),           // 3: mql.llx.Chunk.Call
	(*Primitive)(nil),         // 4: mql.llx.Primitive
	(*AssetValue)(nil),        // 5: mql.llx.AssetValue
	(*Function)(nil),          // 6: mql.llx.Function
	(*Chunk)(nil),             // 7: mql.llx.Chunk
	(*AssertionMessage)(nil),  // 8: mql.llx.AssertionMessage
	(*CodeV1)(nil),            // 9: mql.llx.CodeV1
	(*Block)(nil),             // 10: mql.llx.Block
	(*CodeV2)(nil),            // 11: mql.llx.CodeV2
	(*Labels)(nil),            // 12: mql.llx.Labels
	(*Documentation)(nil),     // 13: mql.llx.Documentation
	(*CodeBundle)(nil),        // 14: mql.llx.CodeBundle
	(*DeprecatedUse)(nil),     // 15: mql.llx.DeprecatedUse
	(*TranslationRef)(nil),    // 16: mql.llx.TranslationRef
	(*ErrorDetail)(nil),       // 17: mql.llx.ErrorDetail
	(*CoverageGap)(nil),       // 18: mql.llx.CoverageGap
	(*Result)(nil),            // 19: mql.llx.Result
	(*ResourceRecording)(nil), // 20: mql.llx.ResourceRecording
	(*Rating)(nil),            // 21: mql.llx.Rating
	(*AssessmentItem)(nil),    // 22: mql.llx.AssessmentItem
	(*Assessment)(nil),        // 23: mql.llx.Assessment
	(*IP)(nil),                // 24: mql.llx.IP
	nil,                       // 25: mql.llx.Primitive.MapEntry
	nil,                       // 26: mql.llx.CodeV1.ChecksumsEntry
	nil,                       // 27: mql.llx.CodeV1.AssertionsEntry
	nil,                       // 28: mql.llx.CodeV2.ChecksumsEntry
	nil,                       // 29: mql.llx.CodeV2.AssertionsEntry
	nil,                       // 30: mql.llx.Labels.LabelsEntry
	nil,                       // 31: mql.llx.CodeBundle.PropsEntry
	nil,                       // 32: mql.llx.CodeBundle.AssertionsEntry
	nil,                       // 33: mql.llx.CodeBundle.AutoExpandEntry
	nil,                       // 34: mql.llx.CodeBundle.VarsEntry
	nil,                       // 35: mql.llx.CodeBundle.ProviderSchemasEntry
	nil,                       // 36: mql.llx.CodeBundle.MinProviderVersionsEntry
	nil,                       // 37: mql.llx.ResourceRecording.FieldsEntry
}
var file_llx_proto_depIdxs = []int32{
	4,  // 0: mql.llx.Primitive.array:type_name -> mql.llx.Primitive
	25, // 1: mql.llx.Primitive.map:type_name -> mql.llx.Primitive.MapEntry
	4,  // 2: mql.llx.Function.args:type_name -> mql.llx.Primitive
	2,  // 3: mql.llx.Function.nullability:type_name -> mql.llx.Function.Nullability
	3,  // 4: mql.llx.Chunk.call:type_name -> mql.llx.Chunk.Call
	4,  // 5: mql.llx.Chunk.primitive:type_name -> mql.llx.Primitive
	6,  // 6: mql.llx.Chunk.function:type_name -> mql.llx.Function
	7,  // 7: mql.llx.CodeV1.code:type_name -> mql.llx.Chunk
	26, // 8: mql.llx.CodeV1.checksums:type_name -> mql.llx.CodeV1.ChecksumsEntry
	9,  // 9: mql.llx.CodeV1.functions:type_name -> mql.llx.CodeV1
	27, // 10: mql.llx.CodeV1.assertions:type_name -> mql.llx.CodeV1.AssertionsEntry
	7,  // 11: mql.llx.Block.chunks:type_name -> mql.llx.Chunk
	10, // 12: mql.llx.CodeV2.blocks:type_name -> mql.llx.Block
	28, // 13: mql.llx.CodeV2.checksums:type_name -> mql.llx.CodeV2.ChecksumsEntry
	29, // 14: mql.llx.CodeV2.assertions:type_name -> mql.llx.CodeV2.AssertionsEntry
	30, // 15: mql.llx.Labels.labels:type_name -> mql.llx.Labels.LabelsEntry
	11, // 16: mql.llx.CodeBundle.code_v2:type_name -> mql.llx.CodeV2
	13, // 17: mql.llx.CodeBundle.suggestions:type_name -> mql.llx.Documentation
	12, // 18: mql.llx.CodeBundle.labels:type_name -> mql.llx.Labels
	31, // 19: mql.llx.CodeBundle.props:type_name -> mql.llx.CodeBundle.PropsEntry
	32, // 20: mql.llx.CodeBundle.assertions:type_name -> mql.llx.CodeBundle.AssertionsEntry
	33, // 21: mql.llx.CodeBundle.auto_expand:type_name -> mql.llx.CodeBundle.AutoExpandEntry
	34, // 22: mql.llx.CodeBundle.vars:type_name -> mql.llx.CodeBundle.VarsEntry
	35, // 23: mql.llx.CodeBundle.provider_schemas:type_name -> mql.llx.CodeBundle.ProviderSchemasEntry
	36, // 24: mql.llx.CodeBundle.min_provider_versions:type_name -> mql.llx.CodeBundle.MinProviderVersionsEntry
	16, // 25: mql.llx.CodeBundle.translations:type_name -> mql.llx.TranslationRef
	15, // 26: mql.llx.CodeBundle.deprecated_uses:type_name -> mql.llx.DeprecatedUse
	0,  // 27: mql.llx.ErrorDetail.kind:type_name -> mql.llx.ErrorKind
	1,  // 28: mql.llx.ErrorDetail.scope:type_name -> mql.llx.ErrorScope
	17, // 29: mql.llx.CoverageGap.detail:type_name -> mql.llx.ErrorDetail
	4,  // 30: mql.llx.Result.data:type_name -> mql.llx.Primitive
	17, // 31: mql.llx.Result.error_detail:type_name -> mql.llx.ErrorDetail
	18, // 32: mql.llx.Result.coverage_gaps:type_name -> mql.llx.CoverageGap
	37, // 33: mql.llx.ResourceRecording.fields:type_name -> mql.llx.ResourceRecording.FieldsEntry
	4,  // 34: mql.llx.AssessmentItem.expected:type_name -> mql.llx.Primitive
	4,  // 35: mql.llx.AssessmentItem.actual:type_name -> mql.llx.Primitive
	4,  // 36: mql.llx.AssessmentItem.data:type_name -> mql.llx.Primitive
	22, // 37: mql.llx.Assessment.results:type_name -> mql.llx.AssessmentItem
	4,  // 38: mql.llx.Primitive.MapEntry.value:type_name -> mql.llx.Primitive
	8,  // 39: mql.llx.CodeV1.AssertionsEntry.value:type_name -> mql.llx.AssertionMessage
	8,  // 40: mql.llx.CodeV2.AssertionsEntry.value:type_name -> mql.llx.AssertionMessage
	8,  // 41: mql.llx.CodeBundle.AssertionsEntry.value:type_name -> mql.llx.AssertionMessage
	19, // 42: mql.llx.ResourceRecording.FieldsEntry.value:type_name -> mql.llx.Result
	43, // [43:43] is the sub-list for method output_type
	43, // [43:43] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_llx_proto_init() }
func file_llx_proto_init() {
	if File_llx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llx_proto_rawDesc), len(file_llx_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llx_proto_goTypes,
		DependencyIndexes: file_llx_proto_depIdxs,
		EnumInfos:         file_llx_proto_enumTypes,
		MessageInfos:      file_llx_proto_msgTypes,
	}.Build()
	File_llx_proto = out.File
	file_llx_proto_goTypes = nil
	file_llx_proto_depIdxs = nil
}
